// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/lbialy/pulumi-contabo/sdk/go/contabo/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// The api endpoint is https://api.contabo.com.
func GetApi(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "contabo:api")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "CNTB_API", "CONTABO_API"); d != nil {
		value = d.(string)
	}
	return value
}

// Your oauth2 client id can be found in the [Customer Control Panel](https://new.contabo.com/account/security) under the menu item account secret.
func GetOauth2ClientId(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "contabo:oauth2ClientId")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "CNTB_OAUTH2_CLIENT_ID", "CONTABO_OAUTH2_CLIENT_ID"); d != nil {
		value = d.(string)
	}
	return value
}

// Your oauth2 client secret can be found in the [Customer Control Panel](https://new.contabo.com/account/security) under the menu item account secret.
func GetOauth2ClientSecret(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "contabo:oauth2ClientSecret")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "CNTB_OAUTH2_CLIENT_SECRET", "CONTABO_OAUTH2_CLIENT_SECRET"); d != nil {
		value = d.(string)
	}
	return value
}

// API Password (this is a new password which you'll set or change in the [Customer Control Panel](https://new.contabo.com/account/security) under the menu item account secret.)
func GetOauth2Pass(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "contabo:oauth2Pass")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "CNTB_OAUTH2_PASS", "CONTABO_OAUTH2_PASS"); d != nil {
		value = d.(string)
	}
	return value
}

// The oauth2 token url is https://auth.contabo.com/auth/realms/contabo/protocol/openid-connect/token.
func GetOauth2TokenUrl(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "contabo:oauth2TokenUrl")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "CNTB_OAUTH2_TOKEN_URL", "CONTABO_OAUTH2_TOKEN_URL"); d != nil {
		value = d.(string)
	}
	return value
}

// API User (your email address to login to the [Customer Control Panel](https://new.contabo.com/account/security) under the menu item account secret.
func GetOauth2User(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "contabo:oauth2User")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "CNTB_OAUTH2_USER", "CONTABO_OAUTH2_USER"); d != nil {
		value = d.(string)
	}
	return value
}
