// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbialy.Contabo
{
    public static class GetInstanceSnapshot
    {
        /// <summary>
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Contabo = Lbialy.Contabo;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // Search for a specific instance snapshot by ID
        ///     var testSnapshot = Contabo.GetInstanceSnapshot.Invoke(new()
        ///     {
        ///         Id = "66abf39a-ba8b-425e-a385-8eb347ceac10",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["myTestSnapshot"] = testSnapshot,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetInstanceSnapshotResult> InvokeAsync(GetInstanceSnapshotArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetInstanceSnapshotResult>("contabo:index/getInstanceSnapshot:getInstanceSnapshot", args ?? new GetInstanceSnapshotArgs(), options.WithDefaults());

        /// <summary>
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Contabo = Lbialy.Contabo;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // Search for a specific instance snapshot by ID
        ///     var testSnapshot = Contabo.GetInstanceSnapshot.Invoke(new()
        ///     {
        ///         Id = "66abf39a-ba8b-425e-a385-8eb347ceac10",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["myTestSnapshot"] = testSnapshot,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetInstanceSnapshotResult> Invoke(GetInstanceSnapshotInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetInstanceSnapshotResult>("contabo:index/getInstanceSnapshot:getInstanceSnapshot", args ?? new GetInstanceSnapshotInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Contabo = Lbialy.Contabo;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // Search for a specific instance snapshot by ID
        ///     var testSnapshot = Contabo.GetInstanceSnapshot.Invoke(new()
        ///     {
        ///         Id = "66abf39a-ba8b-425e-a385-8eb347ceac10",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["myTestSnapshot"] = testSnapshot,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetInstanceSnapshotResult> Invoke(GetInstanceSnapshotInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetInstanceSnapshotResult>("contabo:index/getInstanceSnapshot:getInstanceSnapshot", args ?? new GetInstanceSnapshotInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetInstanceSnapshotArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Description of this snapshot.
        /// </summary>
        [Input("description")]
        public string? Description { get; set; }

        /// <summary>
        /// The identifier of the instance snapshot. Use it to manage it!
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        /// <summary>
        /// Instance identifier associated with the snapshot
        /// </summary>
        [Input("instanceId")]
        public string? InstanceId { get; set; }

        /// <summary>
        /// Name of the snapshot.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        public GetInstanceSnapshotArgs()
        {
        }
        public static new GetInstanceSnapshotArgs Empty => new GetInstanceSnapshotArgs();
    }

    public sealed class GetInstanceSnapshotInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Description of this snapshot.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The identifier of the instance snapshot. Use it to manage it!
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        /// <summary>
        /// Instance identifier associated with the snapshot
        /// </summary>
        [Input("instanceId")]
        public Input<string>? InstanceId { get; set; }

        /// <summary>
        /// Name of the snapshot.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetInstanceSnapshotInvokeArgs()
        {
        }
        public static new GetInstanceSnapshotInvokeArgs Empty => new GetInstanceSnapshotInvokeArgs();
    }


    [OutputType]
    public sealed class GetInstanceSnapshotResult
    {
        /// <summary>
        /// The date when the snapshot will be autmatically deleted.
        /// </summary>
        public readonly string AutoDeleteDate;
        /// <summary>
        /// The creation date of this instance snapshot.
        /// </summary>
        public readonly string CreatedDate;
        /// <summary>
        /// Description of this snapshot.
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// The identifier of the instance snapshot. Use it to manage it!
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Id of the Image the snapshot was taken from.
        /// </summary>
        public readonly string ImageId;
        /// <summary>
        /// Name of the Image the snapshot was taken from.
        /// </summary>
        public readonly string ImageName;
        /// <summary>
        /// Instance identifier associated with the snapshot
        /// </summary>
        public readonly string? InstanceId;
        /// <summary>
        /// Name of the snapshot.
        /// </summary>
        public readonly string? Name;

        [OutputConstructor]
        private GetInstanceSnapshotResult(
            string autoDeleteDate,

            string createdDate,

            string? description,

            string id,

            string imageId,

            string imageName,

            string? instanceId,

            string? name)
        {
            AutoDeleteDate = autoDeleteDate;
            CreatedDate = createdDate;
            Description = description;
            Id = id;
            ImageId = imageId;
            ImageName = imageName;
            InstanceId = instanceId;
            Name = name;
        }
    }
}
