// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbialy.Contabo
{
    public static class GetInstance
    {
        /// <summary>
        /// The Compute Management API allows you to manage compute resources (e.g. creation, deletion, starting, stopping) as well as managing snapshots and custom images. It also supports [cloud-init](https://cloud-init.io/) at least on our default images (for custom images you will need to provide cloud-init support packages). The API offers providing cloud-init scripts via the UserData field. Custom images must be provided in .qcow2 or .iso format.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Contabo = Lbialy.Contabo;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // Search for a specific instance by ID
        ///     var testInstance = Contabo.GetInstance.Invoke(new()
        ///     {
        ///         Id = "123455",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["myTestInstance"] = testInstance,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetInstanceResult> InvokeAsync(GetInstanceArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetInstanceResult>("contabo:index/getInstance:getInstance", args ?? new GetInstanceArgs(), options.WithDefaults());

        /// <summary>
        /// The Compute Management API allows you to manage compute resources (e.g. creation, deletion, starting, stopping) as well as managing snapshots and custom images. It also supports [cloud-init](https://cloud-init.io/) at least on our default images (for custom images you will need to provide cloud-init support packages). The API offers providing cloud-init scripts via the UserData field. Custom images must be provided in .qcow2 or .iso format.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Contabo = Lbialy.Contabo;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // Search for a specific instance by ID
        ///     var testInstance = Contabo.GetInstance.Invoke(new()
        ///     {
        ///         Id = "123455",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["myTestInstance"] = testInstance,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetInstanceResult> Invoke(GetInstanceInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetInstanceResult>("contabo:index/getInstance:getInstance", args ?? new GetInstanceInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// The Compute Management API allows you to manage compute resources (e.g. creation, deletion, starting, stopping) as well as managing snapshots and custom images. It also supports [cloud-init](https://cloud-init.io/) at least on our default images (for custom images you will need to provide cloud-init support packages). The API offers providing cloud-init scripts via the UserData field. Custom images must be provided in .qcow2 or .iso format.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Contabo = Lbialy.Contabo;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // Search for a specific instance by ID
        ///     var testInstance = Contabo.GetInstance.Invoke(new()
        ///     {
        ///         Id = "123455",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["myTestInstance"] = testInstance,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetInstanceResult> Invoke(GetInstanceInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetInstanceResult>("contabo:index/getInstance:getInstance", args ?? new GetInstanceInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetInstanceArgs : global::Pulumi.InvokeArgs
    {
        [Input("addOns")]
        private List<Inputs.GetInstanceAddOnArgs>? _addOns;
        public List<Inputs.GetInstanceAddOnArgs> AddOns
        {
            get => _addOns ?? (_addOns = new List<Inputs.GetInstanceAddOnArgs>());
            set => _addOns = value;
        }

        /// <summary>
        /// The date on which the instance will be cancelled.
        /// </summary>
        [Input("cancelDate")]
        public string? CancelDate { get; set; }

        /// <summary>
        /// Default user name created for login during (re-)installation with administrative privileges. Allowed values for Linux/BSD are admin (use sudo to apply administrative privileges like root) or root. Allowed values for Windows are admin (has administrative privileges like administrator) or administrator.See our [api documentation](https://api.contabo.com/#tag/Instances/operation/createInstance) for available default users.
        /// </summary>
        [Input("defaultUser")]
        public string? DefaultUser { get; set; }

        /// <summary>
        /// Image Id is used to set up the compute instance. Ubuntu 20.04 is the default.
        /// </summary>
        [Input("displayName")]
        public string? DisplayName { get; set; }

        /// <summary>
        /// The identifier of the compute instance. Use it to manage it!
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        /// <summary>
        /// Image Id is used to set up the compute instance. Ubuntu 20.04 is the default.
        /// </summary>
        [Input("imageId")]
        public string? ImageId { get; set; }

        /// <summary>
        /// Additional license in order to enhance your chosen product. It is mainly needed for software licenses on your product (not needed for windows). See our [api documentation](https://api.contabo.com/#tag/Instances/operation/createInstance) for all available licenses.
        /// </summary>
        [Input("license")]
        public string? License { get; set; }

        /// <summary>
        /// Choose the VPS/VDS product you want to buy. See our products [here](https://api.contabo.com/#tag/Instances/operation/createInstance).
        /// </summary>
        [Input("productId")]
        public string? ProductId { get; set; }

        /// <summary>
        /// Instance Region where the compute instance should be located. Default region is the EU. Following regions are available: `EU`,`US-central`,`US-east`,`US-west`,`SIN`.
        /// </summary>
        [Input("region")]
        public string? Region { get; set; }

        [Input("sshKeys")]
        private List<int>? _sshKeys;

        /// <summary>
        /// Array of `secretIds` of public SSH keys for logging into as defaultUser with administrator/root privileges. Applies to Linux/BSD systems. Please refer to Secrets Management API.
        /// </summary>
        public List<int> SshKeys
        {
            get => _sshKeys ?? (_sshKeys = new List<int>());
            set => _sshKeys = value;
        }

        /// <summary>
        /// Cloud-Init Config in order to customize during start of compute instance.
        /// </summary>
        [Input("userData")]
        public string? UserData { get; set; }

        public GetInstanceArgs()
        {
        }
        public static new GetInstanceArgs Empty => new GetInstanceArgs();
    }

    public sealed class GetInstanceInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("addOns")]
        private InputList<Inputs.GetInstanceAddOnInputArgs>? _addOns;
        public InputList<Inputs.GetInstanceAddOnInputArgs> AddOns
        {
            get => _addOns ?? (_addOns = new InputList<Inputs.GetInstanceAddOnInputArgs>());
            set => _addOns = value;
        }

        /// <summary>
        /// The date on which the instance will be cancelled.
        /// </summary>
        [Input("cancelDate")]
        public Input<string>? CancelDate { get; set; }

        /// <summary>
        /// Default user name created for login during (re-)installation with administrative privileges. Allowed values for Linux/BSD are admin (use sudo to apply administrative privileges like root) or root. Allowed values for Windows are admin (has administrative privileges like administrator) or administrator.See our [api documentation](https://api.contabo.com/#tag/Instances/operation/createInstance) for available default users.
        /// </summary>
        [Input("defaultUser")]
        public Input<string>? DefaultUser { get; set; }

        /// <summary>
        /// Image Id is used to set up the compute instance. Ubuntu 20.04 is the default.
        /// </summary>
        [Input("displayName")]
        public Input<string>? DisplayName { get; set; }

        /// <summary>
        /// The identifier of the compute instance. Use it to manage it!
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        /// <summary>
        /// Image Id is used to set up the compute instance. Ubuntu 20.04 is the default.
        /// </summary>
        [Input("imageId")]
        public Input<string>? ImageId { get; set; }

        /// <summary>
        /// Additional license in order to enhance your chosen product. It is mainly needed for software licenses on your product (not needed for windows). See our [api documentation](https://api.contabo.com/#tag/Instances/operation/createInstance) for all available licenses.
        /// </summary>
        [Input("license")]
        public Input<string>? License { get; set; }

        /// <summary>
        /// Choose the VPS/VDS product you want to buy. See our products [here](https://api.contabo.com/#tag/Instances/operation/createInstance).
        /// </summary>
        [Input("productId")]
        public Input<string>? ProductId { get; set; }

        /// <summary>
        /// Instance Region where the compute instance should be located. Default region is the EU. Following regions are available: `EU`,`US-central`,`US-east`,`US-west`,`SIN`.
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        [Input("sshKeys")]
        private InputList<int>? _sshKeys;

        /// <summary>
        /// Array of `secretIds` of public SSH keys for logging into as defaultUser with administrator/root privileges. Applies to Linux/BSD systems. Please refer to Secrets Management API.
        /// </summary>
        public InputList<int> SshKeys
        {
            get => _sshKeys ?? (_sshKeys = new InputList<int>());
            set => _sshKeys = value;
        }

        /// <summary>
        /// Cloud-Init Config in order to customize during start of compute instance.
        /// </summary>
        [Input("userData")]
        public Input<string>? UserData { get; set; }

        public GetInstanceInvokeArgs()
        {
        }
        public static new GetInstanceInvokeArgs Empty => new GetInstanceInvokeArgs();
    }


    [OutputType]
    public sealed class GetInstanceResult
    {
        public readonly ImmutableArray<Outputs.GetInstanceAddOnResult> AddOns;
        /// <summary>
        /// All other additional IP addresses of the instance.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetInstanceAdditionalIpsV4Result> AdditionalIpsV4s;
        /// <summary>
        /// The date on which the instance will be cancelled.
        /// </summary>
        public readonly string CancelDate;
        /// <summary>
        /// CPU core count of the instance.
        /// </summary>
        public readonly int CpuCores;
        /// <summary>
        /// The creation date of the compute instance.
        /// </summary>
        public readonly string CreatedDate;
        /// <summary>
        /// Default user name created for login during (re-)installation with administrative privileges. Allowed values for Linux/BSD are admin (use sudo to apply administrative privileges like root) or root. Allowed values for Windows are admin (has administrative privileges like administrator) or administrator.See our [api documentation](https://api.contabo.com/#tag/Instances/operation/createInstance) for available default users.
        /// </summary>
        public readonly string DefaultUser;
        /// <summary>
        /// Image disk size of the instance in megabyte.
        /// </summary>
        public readonly int DiskMb;
        /// <summary>
        /// Image Id is used to set up the compute instance. Ubuntu 20.04 is the default.
        /// </summary>
        public readonly string DisplayName;
        /// <summary>
        /// If the instance is in an error state (see status property), the error message can be seen in this field.
        /// </summary>
        public readonly string ErrorMessage;
        /// <summary>
        /// The identifier of the compute instance. Use it to manage it!
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Image Id is used to set up the compute instance. Ubuntu 20.04 is the default.
        /// </summary>
        public readonly string ImageId;
        public readonly ImmutableArray<Outputs.GetInstanceIpConfigResult> IpConfigs;
        /// <summary>
        /// Time of the last update of the compute instance.
        /// </summary>
        public readonly string LastUpdated;
        /// <summary>
        /// Additional license in order to enhance your chosen product. It is mainly needed for software licenses on your product (not needed for windows). See our [api documentation](https://api.contabo.com/#tag/Instances/operation/createInstance) for all available licenses.
        /// </summary>
        public readonly string License;
        /// <summary>
        /// Mac address of the instance.
        /// </summary>
        public readonly string MacAddress;
        /// <summary>
        /// Name of the compute instance.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Type of operating system (OS) installed on the instance.
        /// </summary>
        public readonly string OsType;
        /// <summary>
        /// Initial contract period in months. Available periods are: 1, 3, 6 and 12 months. The default setting is 1 month.
        /// </summary>
        public readonly int Period;
        /// <summary>
        /// Choose the VPS/VDS product you want to buy. See our products [here](https://api.contabo.com/#tag/Instances/operation/createInstance).
        /// </summary>
        public readonly string ProductId;
        /// <summary>
        /// InsInstance's category depending on Product Id. Following product types are available: `Hdd`,`Ssd`,`Vds`,`Nvme`.
        /// </summary>
        public readonly string ProductType;
        /// <summary>
        /// Image ram size in megabyte.
        /// </summary>
        public readonly int RamMb;
        /// <summary>
        /// Instance Region where the compute instance should be located. Default region is the EU. Following regions are available: `EU`,`US-central`,`US-east`,`US-west`,`SIN`.
        /// </summary>
        public readonly string Region;
        /// <summary>
        /// Array of `secretIds` of public SSH keys for logging into as defaultUser with administrator/root privileges. Applies to Linux/BSD systems. Please refer to Secrets Management API.
        /// </summary>
        public readonly ImmutableArray<int> SshKeys;
        /// <summary>
        /// Status of the compute instance. The status can be set to `Provisioning`, `Uninstalled`, `Running`, `Stopped`, `Error`, `Installing`, `Unknown`, or `Installed`.
        /// </summary>
        public readonly string Status;
        /// <summary>
        /// Cloud-Init Config in order to customize during start of compute instance.
        /// </summary>
        public readonly string UserData;
        /// <summary>
        /// Identifier of the host system.
        /// </summary>
        public readonly int VHostId;

        [OutputConstructor]
        private GetInstanceResult(
            ImmutableArray<Outputs.GetInstanceAddOnResult> addOns,

            ImmutableArray<Outputs.GetInstanceAdditionalIpsV4Result> additionalIpsV4s,

            string cancelDate,

            int cpuCores,

            string createdDate,

            string defaultUser,

            int diskMb,

            string displayName,

            string errorMessage,

            string id,

            string imageId,

            ImmutableArray<Outputs.GetInstanceIpConfigResult> ipConfigs,

            string lastUpdated,

            string license,

            string macAddress,

            string name,

            string osType,

            int period,

            string productId,

            string productType,

            int ramMb,

            string region,

            ImmutableArray<int> sshKeys,

            string status,

            string userData,

            int vHostId)
        {
            AddOns = addOns;
            AdditionalIpsV4s = additionalIpsV4s;
            CancelDate = cancelDate;
            CpuCores = cpuCores;
            CreatedDate = createdDate;
            DefaultUser = defaultUser;
            DiskMb = diskMb;
            DisplayName = displayName;
            ErrorMessage = errorMessage;
            Id = id;
            ImageId = imageId;
            IpConfigs = ipConfigs;
            LastUpdated = lastUpdated;
            License = license;
            MacAddress = macAddress;
            Name = name;
            OsType = osType;
            Period = period;
            ProductId = productId;
            ProductType = productType;
            RamMb = ramMb;
            Region = region;
            SshKeys = sshKeys;
            Status = status;
            UserData = userData;
            VHostId = vHostId;
        }
    }
}
