// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbialy.Contabo
{
    public static class GetImage
    {
        /// <summary>
        /// In order to provide a custom image, please specify an URL from which the image can be downloaded directly. A custom image must be in either `.iso` or `.qcow2` format. Other formats will be rejected. Please note that downloading can take a while depending on network speed resp. bandwidth and size of image. You can check the status by retrieving information about the image via a GET request. Download will be rejected if you have exceeded your limits.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Contabo = Lbialy.Contabo;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // Search for a specific image by ID
        ///     var debian11 = Contabo.GetImage.Invoke(new()
        ///     {
        ///         Id = "66abf39a-ba8b-425e-a385-8eb347ceac10",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["myTestImage"] = debian11,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetImageResult> InvokeAsync(GetImageArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetImageResult>("contabo:index/getImage:getImage", args ?? new GetImageArgs(), options.WithDefaults());

        /// <summary>
        /// In order to provide a custom image, please specify an URL from which the image can be downloaded directly. A custom image must be in either `.iso` or `.qcow2` format. Other formats will be rejected. Please note that downloading can take a while depending on network speed resp. bandwidth and size of image. You can check the status by retrieving information about the image via a GET request. Download will be rejected if you have exceeded your limits.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Contabo = Lbialy.Contabo;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // Search for a specific image by ID
        ///     var debian11 = Contabo.GetImage.Invoke(new()
        ///     {
        ///         Id = "66abf39a-ba8b-425e-a385-8eb347ceac10",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["myTestImage"] = debian11,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetImageResult> Invoke(GetImageInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetImageResult>("contabo:index/getImage:getImage", args ?? new GetImageInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// In order to provide a custom image, please specify an URL from which the image can be downloaded directly. A custom image must be in either `.iso` or `.qcow2` format. Other formats will be rejected. Please note that downloading can take a while depending on network speed resp. bandwidth and size of image. You can check the status by retrieving information about the image via a GET request. Download will be rejected if you have exceeded your limits.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Contabo = Lbialy.Contabo;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // Search for a specific image by ID
        ///     var debian11 = Contabo.GetImage.Invoke(new()
        ///     {
        ///         Id = "66abf39a-ba8b-425e-a385-8eb347ceac10",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["myTestImage"] = debian11,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetImageResult> Invoke(GetImageInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetImageResult>("contabo:index/getImage:getImage", args ?? new GetImageInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetImageArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Description of the image.
        /// </summary>
        [Input("description")]
        public string? Description { get; set; }

        /// <summary>
        /// The identifier of the image. Use it to manage it!
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        public GetImageArgs()
        {
        }
        public static new GetImageArgs Empty => new GetImageArgs();
    }

    public sealed class GetImageInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Description of the image.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The identifier of the image. Use it to manage it!
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        public GetImageInvokeArgs()
        {
        }
        public static new GetImageInvokeArgs Empty => new GetImageInvokeArgs();
    }


    [OutputType]
    public sealed class GetImageResult
    {
        /// <summary>
        /// The creation date of the image.
        /// </summary>
        public readonly string CreationDate;
        /// <summary>
        /// Description of the image.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// If the image is in an error state (see status property), the error message can be seen in this field.
        /// </summary>
        public readonly string ErrorMessage;
        /// <summary>
        /// Format of your image `Iso` or `Qcow`.
        /// </summary>
        public readonly string Format;
        /// <summary>
        /// The identifier of the image. Use it to manage it!
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Time of the last update of the image.
        /// </summary>
        public readonly string LastUpdated;
        /// <summary>
        /// Name of the image.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Provided type of operating system (OS). Please specify Windows for MS `Windows` and `Linux` for other OS. Specifying wrong OS type may lead to disfunctional cloud instance.
        /// </summary>
        public readonly string OsType;
        /// <summary>
        /// Flag indicating that the image is either a standard (true) or a custom image (false).
        /// </summary>
        public readonly bool StandardImage;
        /// <summary>
        /// Downloading status of the image (`Downloading`, `Downloaded` or `Error`).
        /// </summary>
        public readonly string Status;
        /// <summary>
        /// The size of the uploaded image in megabyte.
        /// </summary>
        public readonly int UploadedSizeMb;
        /// <summary>
        /// Version number to distinguish the contents of an image e.g. the version of the operating system.
        /// </summary>
        public readonly string Version;

        [OutputConstructor]
        private GetImageResult(
            string creationDate,

            string description,

            string errorMessage,

            string format,

            string id,

            string lastUpdated,

            string name,

            string osType,

            bool standardImage,

            string status,

            int uploadedSizeMb,

            string version)
        {
            CreationDate = creationDate;
            Description = description;
            ErrorMessage = errorMessage;
            Format = format;
            Id = id;
            LastUpdated = lastUpdated;
            Name = name;
            OsType = osType;
            StandardImage = standardImage;
            Status = status;
            UploadedSizeMb = uploadedSizeMb;
            Version = version;
        }
    }
}
