// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbialy.Contabo
{
    public static class GetTag
    {
        /// <summary>
        /// Tags are Customer-defined labels which can be attached to any resource in your account. Tag API represent simple CRUD functions and allow you to manage your tags. Use tags to group your resources. For example you can define some user group with tag and give them permission to create compute instance.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Contabo = Lbialy.Contabo;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // Get a specific tag by ID
        ///     var defaultTag = Contabo.GetTag.Invoke(new()
        ///     {
        ///         Id = "26878",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["output"] = defaultTag,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetTagResult> InvokeAsync(GetTagArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetTagResult>("contabo:index/getTag:getTag", args ?? new GetTagArgs(), options.WithDefaults());

        /// <summary>
        /// Tags are Customer-defined labels which can be attached to any resource in your account. Tag API represent simple CRUD functions and allow you to manage your tags. Use tags to group your resources. For example you can define some user group with tag and give them permission to create compute instance.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Contabo = Lbialy.Contabo;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // Get a specific tag by ID
        ///     var defaultTag = Contabo.GetTag.Invoke(new()
        ///     {
        ///         Id = "26878",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["output"] = defaultTag,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetTagResult> Invoke(GetTagInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetTagResult>("contabo:index/getTag:getTag", args ?? new GetTagInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Tags are Customer-defined labels which can be attached to any resource in your account. Tag API represent simple CRUD functions and allow you to manage your tags. Use tags to group your resources. For example you can define some user group with tag and give them permission to create compute instance.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Contabo = Lbialy.Contabo;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // Get a specific tag by ID
        ///     var defaultTag = Contabo.GetTag.Invoke(new()
        ///     {
        ///         Id = "26878",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["output"] = defaultTag,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetTagResult> Invoke(GetTagInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetTagResult>("contabo:index/getTag:getTag", args ?? new GetTagInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetTagArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The tag color.
        /// </summary>
        [Input("color")]
        public string? Color { get; set; }

        /// <summary>
        /// The identifier of the tag. Use it to manage it!
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        /// <summary>
        /// The tag name.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        public GetTagArgs()
        {
        }
        public static new GetTagArgs Empty => new GetTagArgs();
    }

    public sealed class GetTagInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The tag color.
        /// </summary>
        [Input("color")]
        public Input<string>? Color { get; set; }

        /// <summary>
        /// The identifier of the tag. Use it to manage it!
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        /// <summary>
        /// The tag name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetTagInvokeArgs()
        {
        }
        public static new GetTagInvokeArgs Empty => new GetTagInvokeArgs();
    }


    [OutputType]
    public sealed class GetTagResult
    {
        /// <summary>
        /// The tag color.
        /// </summary>
        public readonly string Color;
        /// <summary>
        /// The identifier of the tag. Use it to manage it!
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The tag name.
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private GetTagResult(
            string color,

            string id,

            string name)
        {
            Color = color;
            Id = id;
            Name = name;
        }
    }
}
