// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbialy.Contabo
{
    public static class GetTagAssignment
    {
        /// <summary>
        /// Tag assignment marks the specified resource with the specified tag for organizing purposes or to restrict access to that resource.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Contabo = Lbialy.Contabo;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // Get a specific tag assignment by tagId_resourceType_resourceId
        ///     var defaultTagAssignment = Contabo.GetTagAssignment.Invoke(new()
        ///     {
        ///         Id = "178478_image_35ee288f-21ea-420c-a074-ce0a968b59c0",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["output"] = defaultTagAssignment,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetTagAssignmentResult> InvokeAsync(GetTagAssignmentArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetTagAssignmentResult>("contabo:index/getTagAssignment:getTagAssignment", args ?? new GetTagAssignmentArgs(), options.WithDefaults());

        /// <summary>
        /// Tag assignment marks the specified resource with the specified tag for organizing purposes or to restrict access to that resource.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Contabo = Lbialy.Contabo;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // Get a specific tag assignment by tagId_resourceType_resourceId
        ///     var defaultTagAssignment = Contabo.GetTagAssignment.Invoke(new()
        ///     {
        ///         Id = "178478_image_35ee288f-21ea-420c-a074-ce0a968b59c0",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["output"] = defaultTagAssignment,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetTagAssignmentResult> Invoke(GetTagAssignmentInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetTagAssignmentResult>("contabo:index/getTagAssignment:getTagAssignment", args ?? new GetTagAssignmentInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Tag assignment marks the specified resource with the specified tag for organizing purposes or to restrict access to that resource.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Contabo = Lbialy.Contabo;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // Get a specific tag assignment by tagId_resourceType_resourceId
        ///     var defaultTagAssignment = Contabo.GetTagAssignment.Invoke(new()
        ///     {
        ///         Id = "178478_image_35ee288f-21ea-420c-a074-ce0a968b59c0",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["output"] = defaultTagAssignment,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetTagAssignmentResult> Invoke(GetTagAssignmentInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetTagAssignmentResult>("contabo:index/getTagAssignment:getTagAssignment", args ?? new GetTagAssignmentInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetTagAssignmentArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The identifier of the tag assignment. Use it to manage it!
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        /// <summary>
        /// The resource id.
        /// </summary>
        [Input("resourceId")]
        public string? ResourceId { get; set; }

        /// <summary>
        /// The resource type.
        /// </summary>
        [Input("resourceType")]
        public string? ResourceType { get; set; }

        /// <summary>
        /// The identifier of the tag.
        /// </summary>
        [Input("tagId")]
        public int? TagId { get; set; }

        public GetTagAssignmentArgs()
        {
        }
        public static new GetTagAssignmentArgs Empty => new GetTagAssignmentArgs();
    }

    public sealed class GetTagAssignmentInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The identifier of the tag assignment. Use it to manage it!
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        /// <summary>
        /// The resource id.
        /// </summary>
        [Input("resourceId")]
        public Input<string>? ResourceId { get; set; }

        /// <summary>
        /// The resource type.
        /// </summary>
        [Input("resourceType")]
        public Input<string>? ResourceType { get; set; }

        /// <summary>
        /// The identifier of the tag.
        /// </summary>
        [Input("tagId")]
        public Input<int>? TagId { get; set; }

        public GetTagAssignmentInvokeArgs()
        {
        }
        public static new GetTagAssignmentInvokeArgs Empty => new GetTagAssignmentInvokeArgs();
    }


    [OutputType]
    public sealed class GetTagAssignmentResult
    {
        /// <summary>
        /// The identifier of the tag assignment. Use it to manage it!
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The resource id.
        /// </summary>
        public readonly string ResourceId;
        /// <summary>
        /// The resource name.
        /// </summary>
        public readonly string ResourceName;
        /// <summary>
        /// The resource type.
        /// </summary>
        public readonly string ResourceType;
        /// <summary>
        /// The identifier of the tag.
        /// </summary>
        public readonly int TagId;
        /// <summary>
        /// The name of the tag.
        /// </summary>
        public readonly string TagName;

        [OutputConstructor]
        private GetTagAssignmentResult(
            string id,

            string resourceId,

            string resourceName,

            string resourceType,

            int tagId,

            string tagName)
        {
            Id = id;
            ResourceId = resourceId;
            ResourceName = resourceName;
            ResourceType = resourceType;
            TagId = tagId;
            TagName = tagName;
        }
    }
}
