// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbialy.Contabo
{
    /// <summary>
    /// Manage S3 compatible Object Storage. With the Object Storage API you can create Object Storages in different locations. Please note that you can only have one Object Storage per location. Furthermore, you can increase the amount of storage space and control the autoscaling feature which allows you to automatically perform a monthly upgrade of the disk space to the specified maximum. You might also inspect the usage. This API is not the S3 API itself. For accessing the S3 API directly or with S3 compatible tools like `Aws` cli and after having created / upgraded your Object Storage please use the S3 URL from this Storage API and refer to the User Mangement API to retrieve the S3 credentials.
    /// </summary>
    [ContaboResourceType("contabo:index/objectStorage:ObjectStorage")]
    public partial class ObjectStorage : global::Pulumi.CustomResource
    {
        [Output("autoScalings")]
        public Output<ImmutableArray<Outputs.ObjectStorageAutoScaling>> AutoScalings { get; private set; } = null!;

        /// <summary>
        /// The date on which the Object Storage will be cancelled and therefore no longer available.
        /// </summary>
        [Output("cancelDate")]
        public Output<string> CancelDate { get; private set; } = null!;

        /// <summary>
        /// The creation date of the Object Storage.
        /// </summary>
        [Output("createdDate")]
        public Output<string> CreatedDate { get; private set; } = null!;

        /// <summary>
        /// Your customer number.
        /// </summary>
        [Output("customerId")]
        public Output<string> CustomerId { get; private set; } = null!;

        /// <summary>
        /// Data center the object storage is located in.
        /// </summary>
        [Output("dataCenter")]
        public Output<string> DataCenter { get; private set; } = null!;

        /// <summary>
        /// Display name for object storage.
        /// </summary>
        [Output("displayName")]
        public Output<string> DisplayName { get; private set; } = null!;

        /// <summary>
        /// Region where the Object Storage should be located. Default region is the EU. Following regions are available: `EU`,`US-central`, `SIN`.
        /// </summary>
        [Output("region")]
        public Output<string> Region { get; private set; } = null!;

        /// <summary>
        /// Your S3 tenant Id. Only required for public sharing.
        /// </summary>
        [Output("s3TenantId")]
        public Output<string> S3TenantId { get; private set; } = null!;

        /// <summary>
        /// S3 URL to connect to your S3 compatible Object Storage.
        /// </summary>
        [Output("s3Url")]
        public Output<string> S3Url { get; private set; } = null!;

        /// <summary>
        /// The object storage status. It can be set to `PROVISIONING`,`READY`,`UPGRADING`,`CANCELLED`,`ERROR` or `DISABLED`.
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        /// <summary>
        /// Your customer tenant Id.
        /// </summary>
        [Output("tenantId")]
        public Output<string> TenantId { get; private set; } = null!;

        /// <summary>
        /// Amount of purchased / requested object storage in terabyte.
        /// </summary>
        [Output("totalPurchasedSpaceTb")]
        public Output<double> TotalPurchasedSpaceTb { get; private set; } = null!;


        /// <summary>
        /// Create a ObjectStorage resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ObjectStorage(string name, ObjectStorageArgs args, CustomResourceOptions? options = null)
            : base("contabo:index/objectStorage:ObjectStorage", name, args ?? new ObjectStorageArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ObjectStorage(string name, Input<string> id, ObjectStorageState? state = null, CustomResourceOptions? options = null)
            : base("contabo:index/objectStorage:ObjectStorage", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/lbialy/pulumi-contabo",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ObjectStorage resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ObjectStorage Get(string name, Input<string> id, ObjectStorageState? state = null, CustomResourceOptions? options = null)
        {
            return new ObjectStorage(name, id, state, options);
        }
    }

    public sealed class ObjectStorageArgs : global::Pulumi.ResourceArgs
    {
        [Input("autoScalings")]
        private InputList<Inputs.ObjectStorageAutoScalingArgs>? _autoScalings;
        public InputList<Inputs.ObjectStorageAutoScalingArgs> AutoScalings
        {
            get => _autoScalings ?? (_autoScalings = new InputList<Inputs.ObjectStorageAutoScalingArgs>());
            set => _autoScalings = value;
        }

        /// <summary>
        /// Display name for object storage.
        /// </summary>
        [Input("displayName")]
        public Input<string>? DisplayName { get; set; }

        /// <summary>
        /// Region where the Object Storage should be located. Default region is the EU. Following regions are available: `EU`,`US-central`, `SIN`.
        /// </summary>
        [Input("region", required: true)]
        public Input<string> Region { get; set; } = null!;

        /// <summary>
        /// Amount of purchased / requested object storage in terabyte.
        /// </summary>
        [Input("totalPurchasedSpaceTb", required: true)]
        public Input<double> TotalPurchasedSpaceTb { get; set; } = null!;

        public ObjectStorageArgs()
        {
        }
        public static new ObjectStorageArgs Empty => new ObjectStorageArgs();
    }

    public sealed class ObjectStorageState : global::Pulumi.ResourceArgs
    {
        [Input("autoScalings")]
        private InputList<Inputs.ObjectStorageAutoScalingGetArgs>? _autoScalings;
        public InputList<Inputs.ObjectStorageAutoScalingGetArgs> AutoScalings
        {
            get => _autoScalings ?? (_autoScalings = new InputList<Inputs.ObjectStorageAutoScalingGetArgs>());
            set => _autoScalings = value;
        }

        /// <summary>
        /// The date on which the Object Storage will be cancelled and therefore no longer available.
        /// </summary>
        [Input("cancelDate")]
        public Input<string>? CancelDate { get; set; }

        /// <summary>
        /// The creation date of the Object Storage.
        /// </summary>
        [Input("createdDate")]
        public Input<string>? CreatedDate { get; set; }

        /// <summary>
        /// Your customer number.
        /// </summary>
        [Input("customerId")]
        public Input<string>? CustomerId { get; set; }

        /// <summary>
        /// Data center the object storage is located in.
        /// </summary>
        [Input("dataCenter")]
        public Input<string>? DataCenter { get; set; }

        /// <summary>
        /// Display name for object storage.
        /// </summary>
        [Input("displayName")]
        public Input<string>? DisplayName { get; set; }

        /// <summary>
        /// Region where the Object Storage should be located. Default region is the EU. Following regions are available: `EU`,`US-central`, `SIN`.
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        /// <summary>
        /// Your S3 tenant Id. Only required for public sharing.
        /// </summary>
        [Input("s3TenantId")]
        public Input<string>? S3TenantId { get; set; }

        /// <summary>
        /// S3 URL to connect to your S3 compatible Object Storage.
        /// </summary>
        [Input("s3Url")]
        public Input<string>? S3Url { get; set; }

        /// <summary>
        /// The object storage status. It can be set to `PROVISIONING`,`READY`,`UPGRADING`,`CANCELLED`,`ERROR` or `DISABLED`.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        /// <summary>
        /// Your customer tenant Id.
        /// </summary>
        [Input("tenantId")]
        public Input<string>? TenantId { get; set; }

        /// <summary>
        /// Amount of purchased / requested object storage in terabyte.
        /// </summary>
        [Input("totalPurchasedSpaceTb")]
        public Input<double>? TotalPurchasedSpaceTb { get; set; }

        public ObjectStorageState()
        {
        }
        public static new ObjectStorageState Empty => new ObjectStorageState();
    }
}
