// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbialy.Contabo
{
    /// <summary>
    /// Provides a Contabo [Private Network](https://api.contabo.com/#tag/Private-Networks) resource.  Private Networks can contain your compute instances whereby they are able to communicate with each other in full usolation, using private IP addresses.
    /// </summary>
    [ContaboResourceType("contabo:index/privateNetwork:PrivateNetwork")]
    public partial class PrivateNetwork : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The totality of available IPs in the Private Network.
        /// </summary>
        [Output("availableIps")]
        public Output<int> AvailableIps { get; private set; } = null!;

        /// <summary>
        /// The cidr range of the Private Network.
        /// </summary>
        [Output("cidr")]
        public Output<string> Cidr { get; private set; } = null!;

        /// <summary>
        /// The creation date of the Private Network.
        /// </summary>
        [Output("createdDate")]
        public Output<string> CreatedDate { get; private set; } = null!;

        /// <summary>
        /// The specific data center where the Private Network is located.
        /// </summary>
        [Output("dataCenter")]
        public Output<string> DataCenter { get; private set; } = null!;

        /// <summary>
        /// The description of the Private Network. There is a limit of 255 characters per Private Network.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// Add the instace Ids to the private network here. If you do not add any instance Ids an empty private network will be created.
        /// </summary>
        [Output("instanceIds")]
        public Output<ImmutableArray<int>> InstanceIds { get; private set; } = null!;

        [Output("instances")]
        public Output<ImmutableArray<Outputs.PrivateNetworkInstance>> Instances { get; private set; } = null!;

        /// <summary>
        /// The name of the Private Network. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Private Network name.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The region where the Private Network should be located. Default region is the EU.
        /// </summary>
        [Output("region")]
        public Output<string?> Region { get; private set; } = null!;

        /// <summary>
        /// The name of the region where the Private Network is located.
        /// </summary>
        [Output("regionName")]
        public Output<string> RegionName { get; private set; } = null!;

        /// <summary>
        /// Time of the last update of the private network.
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;


        /// <summary>
        /// Create a PrivateNetwork resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PrivateNetwork(string name, PrivateNetworkArgs? args = null, CustomResourceOptions? options = null)
            : base("contabo:index/privateNetwork:PrivateNetwork", name, args ?? new PrivateNetworkArgs(), MakeResourceOptions(options, ""))
        {
        }

        private PrivateNetwork(string name, Input<string> id, PrivateNetworkState? state = null, CustomResourceOptions? options = null)
            : base("contabo:index/privateNetwork:PrivateNetwork", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/lbialy/pulumi-contabo",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing PrivateNetwork resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static PrivateNetwork Get(string name, Input<string> id, PrivateNetworkState? state = null, CustomResourceOptions? options = null)
        {
            return new PrivateNetwork(name, id, state, options);
        }
    }

    public sealed class PrivateNetworkArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The creation date of the Private Network.
        /// </summary>
        [Input("createdDate")]
        public Input<string>? CreatedDate { get; set; }

        /// <summary>
        /// The description of the Private Network. There is a limit of 255 characters per Private Network.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("instanceIds")]
        private InputList<int>? _instanceIds;

        /// <summary>
        /// Add the instace Ids to the private network here. If you do not add any instance Ids an empty private network will be created.
        /// </summary>
        public InputList<int> InstanceIds
        {
            get => _instanceIds ?? (_instanceIds = new InputList<int>());
            set => _instanceIds = value;
        }

        /// <summary>
        /// The name of the Private Network. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Private Network name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The region where the Private Network should be located. Default region is the EU.
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        /// <summary>
        /// The name of the region where the Private Network is located.
        /// </summary>
        [Input("regionName")]
        public Input<string>? RegionName { get; set; }

        /// <summary>
        /// Time of the last update of the private network.
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        public PrivateNetworkArgs()
        {
        }
        public static new PrivateNetworkArgs Empty => new PrivateNetworkArgs();
    }

    public sealed class PrivateNetworkState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The totality of available IPs in the Private Network.
        /// </summary>
        [Input("availableIps")]
        public Input<int>? AvailableIps { get; set; }

        /// <summary>
        /// The cidr range of the Private Network.
        /// </summary>
        [Input("cidr")]
        public Input<string>? Cidr { get; set; }

        /// <summary>
        /// The creation date of the Private Network.
        /// </summary>
        [Input("createdDate")]
        public Input<string>? CreatedDate { get; set; }

        /// <summary>
        /// The specific data center where the Private Network is located.
        /// </summary>
        [Input("dataCenter")]
        public Input<string>? DataCenter { get; set; }

        /// <summary>
        /// The description of the Private Network. There is a limit of 255 characters per Private Network.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("instanceIds")]
        private InputList<int>? _instanceIds;

        /// <summary>
        /// Add the instace Ids to the private network here. If you do not add any instance Ids an empty private network will be created.
        /// </summary>
        public InputList<int> InstanceIds
        {
            get => _instanceIds ?? (_instanceIds = new InputList<int>());
            set => _instanceIds = value;
        }

        [Input("instances")]
        private InputList<Inputs.PrivateNetworkInstanceGetArgs>? _instances;
        public InputList<Inputs.PrivateNetworkInstanceGetArgs> Instances
        {
            get => _instances ?? (_instances = new InputList<Inputs.PrivateNetworkInstanceGetArgs>());
            set => _instances = value;
        }

        /// <summary>
        /// The name of the Private Network. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Private Network name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The region where the Private Network should be located. Default region is the EU.
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        /// <summary>
        /// The name of the region where the Private Network is located.
        /// </summary>
        [Input("regionName")]
        public Input<string>? RegionName { get; set; }

        /// <summary>
        /// Time of the last update of the private network.
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        public PrivateNetworkState()
        {
        }
        public static new PrivateNetworkState Empty => new PrivateNetworkState();
    }
}
