// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbialy.Contabo
{
    /// <summary>
    /// The provider type for the contabo package. By default, resources use package-wide configuration
    /// settings, however an explicit `Provider` instance may be created and passed during resource
    /// construction to achieve fine-grained programmatic control over provider settings. See the
    /// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
    /// </summary>
    [ContaboResourceType("pulumi:providers:contabo")]
    public partial class Provider : global::Pulumi.ProviderResource
    {
        /// <summary>
        /// The api endpoint is https://api.contabo.com.
        /// </summary>
        [Output("api")]
        public Output<string?> Api { get; private set; } = null!;

        /// <summary>
        /// Your oauth2 client id can be found in the [Customer Control Panel](https://new.contabo.com/account/security) under the menu item account secret.
        /// </summary>
        [Output("oauth2ClientId")]
        public Output<string?> Oauth2ClientId { get; private set; } = null!;

        /// <summary>
        /// Your oauth2 client secret can be found in the [Customer Control Panel](https://new.contabo.com/account/security) under the menu item account secret.
        /// </summary>
        [Output("oauth2ClientSecret")]
        public Output<string?> Oauth2ClientSecret { get; private set; } = null!;

        /// <summary>
        /// API Password (this is a new password which you'll set or change in the [Customer Control Panel](https://new.contabo.com/account/security) under the menu item account secret.)
        /// </summary>
        [Output("oauth2Pass")]
        public Output<string?> Oauth2Pass { get; private set; } = null!;

        /// <summary>
        /// The oauth2 token url is https://auth.contabo.com/auth/realms/contabo/protocol/openid-connect/token.
        /// </summary>
        [Output("oauth2TokenUrl")]
        public Output<string?> Oauth2TokenUrl { get; private set; } = null!;

        /// <summary>
        /// API User (your email address to login to the [Customer Control Panel](https://new.contabo.com/account/security) under the menu item account secret.
        /// </summary>
        [Output("oauth2User")]
        public Output<string?> Oauth2User { get; private set; } = null!;


        /// <summary>
        /// Create a Provider resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Provider(string name, ProviderArgs? args = null, CustomResourceOptions? options = null)
            : base("contabo", name, args ?? new ProviderArgs(), MakeResourceOptions(options, ""))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/lbialy/pulumi-contabo",
                AdditionalSecretOutputs =
                {
                    "oauth2ClientSecret",
                    "oauth2Pass",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }

        /// <summary>
        /// This function returns a Terraform config object with terraform-namecased keys,to be used with the Terraform Module Provider.
        /// </summary>
        public global::Pulumi.Output<ProviderTerraformConfigResult> TerraformConfig()
            => global::Pulumi.Deployment.Instance.Call<ProviderTerraformConfigResult>("pulumi:providers:contabo/terraformConfig", CallArgs.Empty, this);
    }

    public sealed class ProviderArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The api endpoint is https://api.contabo.com.
        /// </summary>
        [Input("api")]
        public Input<string>? Api { get; set; }

        /// <summary>
        /// Your oauth2 client id can be found in the [Customer Control Panel](https://new.contabo.com/account/security) under the menu item account secret.
        /// </summary>
        [Input("oauth2ClientId")]
        public Input<string>? Oauth2ClientId { get; set; }

        [Input("oauth2ClientSecret")]
        private Input<string>? _oauth2ClientSecret;

        /// <summary>
        /// Your oauth2 client secret can be found in the [Customer Control Panel](https://new.contabo.com/account/security) under the menu item account secret.
        /// </summary>
        public Input<string>? Oauth2ClientSecret
        {
            get => _oauth2ClientSecret;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _oauth2ClientSecret = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("oauth2Pass")]
        private Input<string>? _oauth2Pass;

        /// <summary>
        /// API Password (this is a new password which you'll set or change in the [Customer Control Panel](https://new.contabo.com/account/security) under the menu item account secret.)
        /// </summary>
        public Input<string>? Oauth2Pass
        {
            get => _oauth2Pass;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _oauth2Pass = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The oauth2 token url is https://auth.contabo.com/auth/realms/contabo/protocol/openid-connect/token.
        /// </summary>
        [Input("oauth2TokenUrl")]
        public Input<string>? Oauth2TokenUrl { get; set; }

        /// <summary>
        /// API User (your email address to login to the [Customer Control Panel](https://new.contabo.com/account/security) under the menu item account secret.
        /// </summary>
        [Input("oauth2User")]
        public Input<string>? Oauth2User { get; set; }

        public ProviderArgs()
        {
            Api = Utilities.GetEnv("CNTB_API", "CONTABO_API");
            Oauth2ClientId = Utilities.GetEnv("CNTB_OAUTH2_CLIENT_ID", "CONTABO_OAUTH2_CLIENT_ID");
            Oauth2ClientSecret = Utilities.GetEnv("CNTB_OAUTH2_CLIENT_SECRET", "CONTABO_OAUTH2_CLIENT_SECRET");
            Oauth2Pass = Utilities.GetEnv("CNTB_OAUTH2_PASS", "CONTABO_OAUTH2_PASS");
            Oauth2TokenUrl = Utilities.GetEnv("CNTB_OAUTH2_TOKEN_URL", "CONTABO_OAUTH2_TOKEN_URL");
            Oauth2User = Utilities.GetEnv("CNTB_OAUTH2_USER", "CONTABO_OAUTH2_USER");
        }
        public static new ProviderArgs Empty => new ProviderArgs();
    }

    /// <summary>
    /// The results of the <see cref="Provider.TerraformConfig"/> method.
    /// </summary>
    [OutputType]
    public sealed class ProviderTerraformConfigResult
    {
        public readonly ImmutableDictionary<string, object> Result;

        [OutputConstructor]
        private ProviderTerraformConfigResult(ImmutableDictionary<string, object> result)
        {
            Result = result;
        }
    }
}
