// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Immutable;

namespace Lbialy.Contabo
{
    public static class Config
    {
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "IDE1006", Justification = 
        "Double underscore prefix used to avoid conflicts with variable names.")]
        private sealed class __Value<T>
        {
            private readonly Func<T> _getter;
            private T _value = default!;
            private bool _set;

            public __Value(Func<T> getter)
            {
                _getter = getter;
            }

            public T Get() => _set ? _value : _getter();

            public void Set(T value)
            {
                _value = value;
                _set = true;
            }
        }

        private static readonly global::Pulumi.Config __config = new global::Pulumi.Config("contabo");

        private static readonly __Value<string?> _api = new __Value<string?>(() => __config.Get("api") ?? Utilities.GetEnv("CNTB_API", "CONTABO_API"));
        /// <summary>
        /// The api endpoint is https://api.contabo.com.
        /// </summary>
        public static string? Api
        {
            get => _api.Get();
            set => _api.Set(value);
        }

        private static readonly __Value<string?> _oauth2ClientId = new __Value<string?>(() => __config.Get("oauth2ClientId") ?? Utilities.GetEnv("CNTB_OAUTH2_CLIENT_ID", "CONTABO_OAUTH2_CLIENT_ID"));
        /// <summary>
        /// Your oauth2 client id can be found in the [Customer Control Panel](https://new.contabo.com/account/security) under the menu item account secret.
        /// </summary>
        public static string? Oauth2ClientId
        {
            get => _oauth2ClientId.Get();
            set => _oauth2ClientId.Set(value);
        }

        private static readonly __Value<string?> _oauth2ClientSecret = new __Value<string?>(() => __config.Get("oauth2ClientSecret") ?? Utilities.GetEnv("CNTB_OAUTH2_CLIENT_SECRET", "CONTABO_OAUTH2_CLIENT_SECRET"));
        /// <summary>
        /// Your oauth2 client secret can be found in the [Customer Control Panel](https://new.contabo.com/account/security) under the menu item account secret.
        /// </summary>
        public static string? Oauth2ClientSecret
        {
            get => _oauth2ClientSecret.Get();
            set => _oauth2ClientSecret.Set(value);
        }

        private static readonly __Value<string?> _oauth2Pass = new __Value<string?>(() => __config.Get("oauth2Pass") ?? Utilities.GetEnv("CNTB_OAUTH2_PASS", "CONTABO_OAUTH2_PASS"));
        /// <summary>
        /// API Password (this is a new password which you'll set or change in the [Customer Control Panel](https://new.contabo.com/account/security) under the menu item account secret.)
        /// </summary>
        public static string? Oauth2Pass
        {
            get => _oauth2Pass.Get();
            set => _oauth2Pass.Set(value);
        }

        private static readonly __Value<string?> _oauth2TokenUrl = new __Value<string?>(() => __config.Get("oauth2TokenUrl") ?? Utilities.GetEnv("CNTB_OAUTH2_TOKEN_URL", "CONTABO_OAUTH2_TOKEN_URL"));
        /// <summary>
        /// The oauth2 token url is https://auth.contabo.com/auth/realms/contabo/protocol/openid-connect/token.
        /// </summary>
        public static string? Oauth2TokenUrl
        {
            get => _oauth2TokenUrl.Get();
            set => _oauth2TokenUrl.Set(value);
        }

        private static readonly __Value<string?> _oauth2User = new __Value<string?>(() => __config.Get("oauth2User") ?? Utilities.GetEnv("CNTB_OAUTH2_USER", "CONTABO_OAUTH2_USER"));
        /// <summary>
        /// API User (your email address to login to the [Customer Control Panel](https://new.contabo.com/account/security) under the menu item account secret.
        /// </summary>
        public static string? Oauth2User
        {
            get => _oauth2User.Get();
            set => _oauth2User.Set(value);
        }

    }
}
