// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package contabo

import (
	"context"
	"reflect"

	"errors"
	"github.com/lbialy/pulumi-contabo/sdk/v2/go/contabo/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
type Firewall struct {
	pulumi.CustomResourceState

	// The creation date of the Firewall.
	CreatedDate pulumi.StringOutput `pulumi:"createdDate"`
	// The description of the Firewall. There is a limit of 255 characters per Firewall.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Add the instace Ids to the firewall here. If you do not add any instance Ids an empty firewall will be created.
	InstanceIds pulumi.IntArrayOutput `pulumi:"instanceIds"`
	// The status of every instance in the firewall
	InstancesStatuses FirewallInstancesStatusArrayOutput `pulumi:"instancesStatuses"`
	// The name of the Firewall. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Firewall name.
	Name  pulumi.StringOutput     `pulumi:"name"`
	Rules FirewallRuleArrayOutput `pulumi:"rules"`
	// Status of the Firewall. It can be `active`, or `inactive`.
	Status pulumi.StringOutput `pulumi:"status"`
}

// NewFirewall registers a new resource with the given unique name, arguments, and options.
func NewFirewall(ctx *pulumi.Context,
	name string, args *FirewallArgs, opts ...pulumi.ResourceOption) (*Firewall, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Status == nil {
		return nil, errors.New("invalid value for required argument 'Status'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Firewall
	err := ctx.RegisterResource("contabo:index/firewall:Firewall", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetFirewall gets an existing Firewall resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetFirewall(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *FirewallState, opts ...pulumi.ResourceOption) (*Firewall, error) {
	var resource Firewall
	err := ctx.ReadResource("contabo:index/firewall:Firewall", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Firewall resources.
type firewallState struct {
	// The creation date of the Firewall.
	CreatedDate *string `pulumi:"createdDate"`
	// The description of the Firewall. There is a limit of 255 characters per Firewall.
	Description *string `pulumi:"description"`
	// Add the instace Ids to the firewall here. If you do not add any instance Ids an empty firewall will be created.
	InstanceIds []int `pulumi:"instanceIds"`
	// The status of every instance in the firewall
	InstancesStatuses []FirewallInstancesStatus `pulumi:"instancesStatuses"`
	// The name of the Firewall. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Firewall name.
	Name  *string        `pulumi:"name"`
	Rules []FirewallRule `pulumi:"rules"`
	// Status of the Firewall. It can be `active`, or `inactive`.
	Status *string `pulumi:"status"`
}

type FirewallState struct {
	// The creation date of the Firewall.
	CreatedDate pulumi.StringPtrInput
	// The description of the Firewall. There is a limit of 255 characters per Firewall.
	Description pulumi.StringPtrInput
	// Add the instace Ids to the firewall here. If you do not add any instance Ids an empty firewall will be created.
	InstanceIds pulumi.IntArrayInput
	// The status of every instance in the firewall
	InstancesStatuses FirewallInstancesStatusArrayInput
	// The name of the Firewall. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Firewall name.
	Name  pulumi.StringPtrInput
	Rules FirewallRuleArrayInput
	// Status of the Firewall. It can be `active`, or `inactive`.
	Status pulumi.StringPtrInput
}

func (FirewallState) ElementType() reflect.Type {
	return reflect.TypeOf((*firewallState)(nil)).Elem()
}

type firewallArgs struct {
	// The creation date of the Firewall.
	CreatedDate *string `pulumi:"createdDate"`
	// The description of the Firewall. There is a limit of 255 characters per Firewall.
	Description *string `pulumi:"description"`
	// Add the instace Ids to the firewall here. If you do not add any instance Ids an empty firewall will be created.
	InstanceIds []int `pulumi:"instanceIds"`
	// The status of every instance in the firewall
	InstancesStatuses []FirewallInstancesStatus `pulumi:"instancesStatuses"`
	// The name of the Firewall. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Firewall name.
	Name  *string        `pulumi:"name"`
	Rules []FirewallRule `pulumi:"rules"`
	// Status of the Firewall. It can be `active`, or `inactive`.
	Status string `pulumi:"status"`
}

// The set of arguments for constructing a Firewall resource.
type FirewallArgs struct {
	// The creation date of the Firewall.
	CreatedDate pulumi.StringPtrInput
	// The description of the Firewall. There is a limit of 255 characters per Firewall.
	Description pulumi.StringPtrInput
	// Add the instace Ids to the firewall here. If you do not add any instance Ids an empty firewall will be created.
	InstanceIds pulumi.IntArrayInput
	// The status of every instance in the firewall
	InstancesStatuses FirewallInstancesStatusArrayInput
	// The name of the Firewall. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Firewall name.
	Name  pulumi.StringPtrInput
	Rules FirewallRuleArrayInput
	// Status of the Firewall. It can be `active`, or `inactive`.
	Status pulumi.StringInput
}

func (FirewallArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*firewallArgs)(nil)).Elem()
}

type FirewallInput interface {
	pulumi.Input

	ToFirewallOutput() FirewallOutput
	ToFirewallOutputWithContext(ctx context.Context) FirewallOutput
}

func (*Firewall) ElementType() reflect.Type {
	return reflect.TypeOf((**Firewall)(nil)).Elem()
}

func (i *Firewall) ToFirewallOutput() FirewallOutput {
	return i.ToFirewallOutputWithContext(context.Background())
}

func (i *Firewall) ToFirewallOutputWithContext(ctx context.Context) FirewallOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FirewallOutput)
}

// FirewallArrayInput is an input type that accepts FirewallArray and FirewallArrayOutput values.
// You can construct a concrete instance of `FirewallArrayInput` via:
//
//	FirewallArray{ FirewallArgs{...} }
type FirewallArrayInput interface {
	pulumi.Input

	ToFirewallArrayOutput() FirewallArrayOutput
	ToFirewallArrayOutputWithContext(context.Context) FirewallArrayOutput
}

type FirewallArray []FirewallInput

func (FirewallArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Firewall)(nil)).Elem()
}

func (i FirewallArray) ToFirewallArrayOutput() FirewallArrayOutput {
	return i.ToFirewallArrayOutputWithContext(context.Background())
}

func (i FirewallArray) ToFirewallArrayOutputWithContext(ctx context.Context) FirewallArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FirewallArrayOutput)
}

// FirewallMapInput is an input type that accepts FirewallMap and FirewallMapOutput values.
// You can construct a concrete instance of `FirewallMapInput` via:
//
//	FirewallMap{ "key": FirewallArgs{...} }
type FirewallMapInput interface {
	pulumi.Input

	ToFirewallMapOutput() FirewallMapOutput
	ToFirewallMapOutputWithContext(context.Context) FirewallMapOutput
}

type FirewallMap map[string]FirewallInput

func (FirewallMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Firewall)(nil)).Elem()
}

func (i FirewallMap) ToFirewallMapOutput() FirewallMapOutput {
	return i.ToFirewallMapOutputWithContext(context.Background())
}

func (i FirewallMap) ToFirewallMapOutputWithContext(ctx context.Context) FirewallMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FirewallMapOutput)
}

type FirewallOutput struct{ *pulumi.OutputState }

func (FirewallOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Firewall)(nil)).Elem()
}

func (o FirewallOutput) ToFirewallOutput() FirewallOutput {
	return o
}

func (o FirewallOutput) ToFirewallOutputWithContext(ctx context.Context) FirewallOutput {
	return o
}

// The creation date of the Firewall.
func (o FirewallOutput) CreatedDate() pulumi.StringOutput {
	return o.ApplyT(func(v *Firewall) pulumi.StringOutput { return v.CreatedDate }).(pulumi.StringOutput)
}

// The description of the Firewall. There is a limit of 255 characters per Firewall.
func (o FirewallOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Firewall) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Add the instace Ids to the firewall here. If you do not add any instance Ids an empty firewall will be created.
func (o FirewallOutput) InstanceIds() pulumi.IntArrayOutput {
	return o.ApplyT(func(v *Firewall) pulumi.IntArrayOutput { return v.InstanceIds }).(pulumi.IntArrayOutput)
}

// The status of every instance in the firewall
func (o FirewallOutput) InstancesStatuses() FirewallInstancesStatusArrayOutput {
	return o.ApplyT(func(v *Firewall) FirewallInstancesStatusArrayOutput { return v.InstancesStatuses }).(FirewallInstancesStatusArrayOutput)
}

// The name of the Firewall. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Firewall name.
func (o FirewallOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Firewall) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o FirewallOutput) Rules() FirewallRuleArrayOutput {
	return o.ApplyT(func(v *Firewall) FirewallRuleArrayOutput { return v.Rules }).(FirewallRuleArrayOutput)
}

// Status of the Firewall. It can be `active`, or `inactive`.
func (o FirewallOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *Firewall) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

type FirewallArrayOutput struct{ *pulumi.OutputState }

func (FirewallArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Firewall)(nil)).Elem()
}

func (o FirewallArrayOutput) ToFirewallArrayOutput() FirewallArrayOutput {
	return o
}

func (o FirewallArrayOutput) ToFirewallArrayOutputWithContext(ctx context.Context) FirewallArrayOutput {
	return o
}

func (o FirewallArrayOutput) Index(i pulumi.IntInput) FirewallOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Firewall {
		return vs[0].([]*Firewall)[vs[1].(int)]
	}).(FirewallOutput)
}

type FirewallMapOutput struct{ *pulumi.OutputState }

func (FirewallMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Firewall)(nil)).Elem()
}

func (o FirewallMapOutput) ToFirewallMapOutput() FirewallMapOutput {
	return o
}

func (o FirewallMapOutput) ToFirewallMapOutputWithContext(ctx context.Context) FirewallMapOutput {
	return o
}

func (o FirewallMapOutput) MapIndex(k pulumi.StringInput) FirewallOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Firewall {
		return vs[0].(map[string]*Firewall)[vs[1].(string)]
	}).(FirewallOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*FirewallInput)(nil)).Elem(), &Firewall{})
	pulumi.RegisterInputType(reflect.TypeOf((*FirewallArrayInput)(nil)).Elem(), FirewallArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*FirewallMapInput)(nil)).Elem(), FirewallMap{})
	pulumi.RegisterOutputType(FirewallOutput{})
	pulumi.RegisterOutputType(FirewallArrayOutput{})
	pulumi.RegisterOutputType(FirewallMapOutput{})
}
