// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package contabo

import (
	"context"
	"reflect"

	"github.com/lbialy/pulumi-contabo/sdk/v2/go/contabo/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupFirewall(ctx *pulumi.Context, args *LookupFirewallArgs, opts ...pulumi.InvokeOption) (*LookupFirewallResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupFirewallResult
	err := ctx.Invoke("contabo:index/getFirewall:getFirewall", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getFirewall.
type LookupFirewallArgs struct {
	// The creation date of the Firewall.
	CreatedDate *string `pulumi:"createdDate"`
	// The description of the Firewall. There is a limit of 255 characters per Firewall.
	Description *string `pulumi:"description"`
	// Add the instace Ids to the firewall here. If you do not add any instance Ids an empty firewall will be created.
	InstanceIds []int `pulumi:"instanceIds"`
	// The status of every instance in the firewall
	InstancesStatuses []GetFirewallInstancesStatus `pulumi:"instancesStatuses"`
	// The name of the Firewall. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Firewall name.
	Name  string            `pulumi:"name"`
	Rules []GetFirewallRule `pulumi:"rules"`
	// Status of the Firewall. It can be `active`, or `inactive`.
	Status string `pulumi:"status"`
}

// A collection of values returned by getFirewall.
type LookupFirewallResult struct {
	// The creation date of the Firewall.
	CreatedDate string `pulumi:"createdDate"`
	// The description of the Firewall. There is a limit of 255 characters per Firewall.
	Description *string `pulumi:"description"`
	// The identifier of the Firewall. Use it to manage it!
	Id string `pulumi:"id"`
	// Add the instace Ids to the firewall here. If you do not add any instance Ids an empty firewall will be created.
	InstanceIds []int `pulumi:"instanceIds"`
	// The status of every instance in the firewall
	InstancesStatuses []GetFirewallInstancesStatus `pulumi:"instancesStatuses"`
	// The name of the Firewall. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Firewall name.
	Name  string            `pulumi:"name"`
	Rules []GetFirewallRule `pulumi:"rules"`
	// Status of the Firewall. It can be `active`, or `inactive`.
	Status string `pulumi:"status"`
}

func LookupFirewallOutput(ctx *pulumi.Context, args LookupFirewallOutputArgs, opts ...pulumi.InvokeOption) LookupFirewallResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupFirewallResultOutput, error) {
			args := v.(LookupFirewallArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("contabo:index/getFirewall:getFirewall", args, LookupFirewallResultOutput{}, options).(LookupFirewallResultOutput), nil
		}).(LookupFirewallResultOutput)
}

// A collection of arguments for invoking getFirewall.
type LookupFirewallOutputArgs struct {
	// The creation date of the Firewall.
	CreatedDate pulumi.StringPtrInput `pulumi:"createdDate"`
	// The description of the Firewall. There is a limit of 255 characters per Firewall.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// Add the instace Ids to the firewall here. If you do not add any instance Ids an empty firewall will be created.
	InstanceIds pulumi.IntArrayInput `pulumi:"instanceIds"`
	// The status of every instance in the firewall
	InstancesStatuses GetFirewallInstancesStatusArrayInput `pulumi:"instancesStatuses"`
	// The name of the Firewall. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Firewall name.
	Name  pulumi.StringInput        `pulumi:"name"`
	Rules GetFirewallRuleArrayInput `pulumi:"rules"`
	// Status of the Firewall. It can be `active`, or `inactive`.
	Status pulumi.StringInput `pulumi:"status"`
}

func (LookupFirewallOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFirewallArgs)(nil)).Elem()
}

// A collection of values returned by getFirewall.
type LookupFirewallResultOutput struct{ *pulumi.OutputState }

func (LookupFirewallResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFirewallResult)(nil)).Elem()
}

func (o LookupFirewallResultOutput) ToLookupFirewallResultOutput() LookupFirewallResultOutput {
	return o
}

func (o LookupFirewallResultOutput) ToLookupFirewallResultOutputWithContext(ctx context.Context) LookupFirewallResultOutput {
	return o
}

// The creation date of the Firewall.
func (o LookupFirewallResultOutput) CreatedDate() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFirewallResult) string { return v.CreatedDate }).(pulumi.StringOutput)
}

// The description of the Firewall. There is a limit of 255 characters per Firewall.
func (o LookupFirewallResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupFirewallResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// The identifier of the Firewall. Use it to manage it!
func (o LookupFirewallResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFirewallResult) string { return v.Id }).(pulumi.StringOutput)
}

// Add the instace Ids to the firewall here. If you do not add any instance Ids an empty firewall will be created.
func (o LookupFirewallResultOutput) InstanceIds() pulumi.IntArrayOutput {
	return o.ApplyT(func(v LookupFirewallResult) []int { return v.InstanceIds }).(pulumi.IntArrayOutput)
}

// The status of every instance in the firewall
func (o LookupFirewallResultOutput) InstancesStatuses() GetFirewallInstancesStatusArrayOutput {
	return o.ApplyT(func(v LookupFirewallResult) []GetFirewallInstancesStatus { return v.InstancesStatuses }).(GetFirewallInstancesStatusArrayOutput)
}

// The name of the Firewall. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Firewall name.
func (o LookupFirewallResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFirewallResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupFirewallResultOutput) Rules() GetFirewallRuleArrayOutput {
	return o.ApplyT(func(v LookupFirewallResult) []GetFirewallRule { return v.Rules }).(GetFirewallRuleArrayOutput)
}

// Status of the Firewall. It can be `active`, or `inactive`.
func (o LookupFirewallResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFirewallResult) string { return v.Status }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupFirewallResultOutput{})
}
