// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package contabo

import (
	"context"
	"reflect"

	"github.com/lbialy/pulumi-contabo/sdk/v2/go/contabo/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manage S3 compatible Object Storage. With the Object Storage API you can create Object Storages in different locations. Please note that you can only have one Object Storage per location. Furthermore, you can increase the amount of storage space and control the autoscaling feature which allows you to automatically perform a monthly upgrade of the disk space to the specified maximum. You might also inspect the usage. This API is not the S3 API itself. For accessing the S3 API directly or with S3 compatible tools like `aws` cli and after having created / upgraded your Object Storage please use the S3 URL from this Storage API and refer to the User Mangement API to retrieve the S3 credentials.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/lbialy/pulumi-contabo/sdk/v2/go/contabo"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Search object storage by ID
//			example1, err := contabo.GetObjectStorage(ctx, &contabo.LookupObjectStorageArgs{
//				Id: pulumi.StringRef("3a6e5301-fc71-42ce-b60c-49841681c2da"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			// Search object storage by display name
//			_, err = contabo.GetObjectStorage(ctx, &contabo.LookupObjectStorageArgs{
//				DisplayName: pulumi.StringRef("example2"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("myObjectStorage1", example1)
//			ctx.Export("myObjectStorage2", example1)
//			return nil
//		})
//	}
//
// ```
func LookupObjectStorage(ctx *pulumi.Context, args *LookupObjectStorageArgs, opts ...pulumi.InvokeOption) (*LookupObjectStorageResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupObjectStorageResult
	err := ctx.Invoke("contabo:index/getObjectStorage:getObjectStorage", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getObjectStorage.
type LookupObjectStorageArgs struct {
	AutoScalings []GetObjectStorageAutoScaling `pulumi:"autoScalings"`
	// Display name for object storage. Use it to manage it!
	DisplayName *string `pulumi:"displayName"`
	// The identifier of the Object Storage. Use it to manage it!
	Id *string `pulumi:"id"`
}

// A collection of values returned by getObjectStorage.
type LookupObjectStorageResult struct {
	AutoScalings []GetObjectStorageAutoScaling `pulumi:"autoScalings"`
	// The date on which the Object Storage will be cancelled and therefore no longer available.
	CancelDate string `pulumi:"cancelDate"`
	// The creation date of the Object Storage.
	CreatedDate string `pulumi:"createdDate"`
	// Your customer number.
	CustomerId string `pulumi:"customerId"`
	// Data center the object storage is located in.
	DataCenter string `pulumi:"dataCenter"`
	// Display name for object storage. Use it to manage it!
	DisplayName *string `pulumi:"displayName"`
	// The identifier of the Object Storage. Use it to manage it!
	Id *string `pulumi:"id"`
	// Region where the Object Storage should be located. Default region is the EU. Following regions are available: `EU`,`US-central`, `SIN`.
	Region string `pulumi:"region"`
	// Your S3 tenant Id. Only required for public sharing.
	S3TenantId string `pulumi:"s3TenantId"`
	// S3 URL to connect to your S3 compatible Object Storage.
	S3Url string `pulumi:"s3Url"`
	// The object storage status. It can be set to `PROVISIONING`,`READY`,`UPGRADING`,`CANCELLED`,`ERROR` or `DISABLED`.
	Status string `pulumi:"status"`
	// Your customer tenant Id.
	TenantId string `pulumi:"tenantId"`
	// Amount of purchased / requested object storage in terabyte.
	TotalPurchasedSpaceTb float64 `pulumi:"totalPurchasedSpaceTb"`
}

func LookupObjectStorageOutput(ctx *pulumi.Context, args LookupObjectStorageOutputArgs, opts ...pulumi.InvokeOption) LookupObjectStorageResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupObjectStorageResultOutput, error) {
			args := v.(LookupObjectStorageArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("contabo:index/getObjectStorage:getObjectStorage", args, LookupObjectStorageResultOutput{}, options).(LookupObjectStorageResultOutput), nil
		}).(LookupObjectStorageResultOutput)
}

// A collection of arguments for invoking getObjectStorage.
type LookupObjectStorageOutputArgs struct {
	AutoScalings GetObjectStorageAutoScalingArrayInput `pulumi:"autoScalings"`
	// Display name for object storage. Use it to manage it!
	DisplayName pulumi.StringPtrInput `pulumi:"displayName"`
	// The identifier of the Object Storage. Use it to manage it!
	Id pulumi.StringPtrInput `pulumi:"id"`
}

func (LookupObjectStorageOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupObjectStorageArgs)(nil)).Elem()
}

// A collection of values returned by getObjectStorage.
type LookupObjectStorageResultOutput struct{ *pulumi.OutputState }

func (LookupObjectStorageResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupObjectStorageResult)(nil)).Elem()
}

func (o LookupObjectStorageResultOutput) ToLookupObjectStorageResultOutput() LookupObjectStorageResultOutput {
	return o
}

func (o LookupObjectStorageResultOutput) ToLookupObjectStorageResultOutputWithContext(ctx context.Context) LookupObjectStorageResultOutput {
	return o
}

func (o LookupObjectStorageResultOutput) AutoScalings() GetObjectStorageAutoScalingArrayOutput {
	return o.ApplyT(func(v LookupObjectStorageResult) []GetObjectStorageAutoScaling { return v.AutoScalings }).(GetObjectStorageAutoScalingArrayOutput)
}

// The date on which the Object Storage will be cancelled and therefore no longer available.
func (o LookupObjectStorageResultOutput) CancelDate() pulumi.StringOutput {
	return o.ApplyT(func(v LookupObjectStorageResult) string { return v.CancelDate }).(pulumi.StringOutput)
}

// The creation date of the Object Storage.
func (o LookupObjectStorageResultOutput) CreatedDate() pulumi.StringOutput {
	return o.ApplyT(func(v LookupObjectStorageResult) string { return v.CreatedDate }).(pulumi.StringOutput)
}

// Your customer number.
func (o LookupObjectStorageResultOutput) CustomerId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupObjectStorageResult) string { return v.CustomerId }).(pulumi.StringOutput)
}

// Data center the object storage is located in.
func (o LookupObjectStorageResultOutput) DataCenter() pulumi.StringOutput {
	return o.ApplyT(func(v LookupObjectStorageResult) string { return v.DataCenter }).(pulumi.StringOutput)
}

// Display name for object storage. Use it to manage it!
func (o LookupObjectStorageResultOutput) DisplayName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupObjectStorageResult) *string { return v.DisplayName }).(pulumi.StringPtrOutput)
}

// The identifier of the Object Storage. Use it to manage it!
func (o LookupObjectStorageResultOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupObjectStorageResult) *string { return v.Id }).(pulumi.StringPtrOutput)
}

// Region where the Object Storage should be located. Default region is the EU. Following regions are available: `EU`,`US-central`, `SIN`.
func (o LookupObjectStorageResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v LookupObjectStorageResult) string { return v.Region }).(pulumi.StringOutput)
}

// Your S3 tenant Id. Only required for public sharing.
func (o LookupObjectStorageResultOutput) S3TenantId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupObjectStorageResult) string { return v.S3TenantId }).(pulumi.StringOutput)
}

// S3 URL to connect to your S3 compatible Object Storage.
func (o LookupObjectStorageResultOutput) S3Url() pulumi.StringOutput {
	return o.ApplyT(func(v LookupObjectStorageResult) string { return v.S3Url }).(pulumi.StringOutput)
}

// The object storage status. It can be set to `PROVISIONING`,`READY`,`UPGRADING`,`CANCELLED`,`ERROR` or `DISABLED`.
func (o LookupObjectStorageResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupObjectStorageResult) string { return v.Status }).(pulumi.StringOutput)
}

// Your customer tenant Id.
func (o LookupObjectStorageResultOutput) TenantId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupObjectStorageResult) string { return v.TenantId }).(pulumi.StringOutput)
}

// Amount of purchased / requested object storage in terabyte.
func (o LookupObjectStorageResultOutput) TotalPurchasedSpaceTb() pulumi.Float64Output {
	return o.ApplyT(func(v LookupObjectStorageResult) float64 { return v.TotalPurchasedSpaceTb }).(pulumi.Float64Output)
}

func init() {
	pulumi.RegisterOutputType(LookupObjectStorageResultOutput{})
}
