// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package contabo

import (
	"context"
	"reflect"

	"github.com/lbialy/pulumi-contabo/sdk/go/contabo/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manage buckets on your contabo Object Storage. With this resource you are able to manage your buckets the same way your are able to manage them in your contabo customer panel.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/lbialy/pulumi-contabo/sdk/go/contabo"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Search object storage bucket by Object Storage ID and name
//			bucket1, err := contabo.GetObjectStorageBucket(ctx, &contabo.LookupObjectStorageBucketArgs{
//				ObjectStorageId: "3a6e5301-fc71-42ce-b60c-49841681c2da",
//				Name:            pulumi.StringRef("testbucket"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("myTestBucket", bucket1)
//			return nil
//		})
//	}
//
// ```
func LookupObjectStorageBucket(ctx *pulumi.Context, args *LookupObjectStorageBucketArgs, opts ...pulumi.InvokeOption) (*LookupObjectStorageBucketResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupObjectStorageBucketResult
	err := ctx.Invoke("contabo:index/getObjectStorageBucket:getObjectStorageBucket", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getObjectStorageBucket.
type LookupObjectStorageBucketArgs struct {
	// The name of your bucket, consider the naming restriction https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-s3-bucket-naming-requirements.html.
	Name *string `pulumi:"name"`
	// The contabo objectStorageId on which the bucket should be created.
	ObjectStorageId string `pulumi:"objectStorageId"`
	// Choose the access to your bucket. You can not share it at all or share it publicly.
	PublicSharing *bool `pulumi:"publicSharing"`
}

// A collection of values returned by getObjectStorageBucket.
type LookupObjectStorageBucketResult struct {
	// The creation date of the bucket.
	CreationDate string `pulumi:"creationDate"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The name of your bucket, consider the naming restriction https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-s3-bucket-naming-requirements.html.
	Name *string `pulumi:"name"`
	// The contabo objectStorageId on which the bucket should be created.
	ObjectStorageId string `pulumi:"objectStorageId"`
	// Choose the access to your bucket. You can not share it at all or share it publicly.
	PublicSharing *bool `pulumi:"publicSharing"`
	// If your bucket is publicly shared, you can access it with this link.
	PublicSharingLink string `pulumi:"publicSharingLink"`
}

func LookupObjectStorageBucketOutput(ctx *pulumi.Context, args LookupObjectStorageBucketOutputArgs, opts ...pulumi.InvokeOption) LookupObjectStorageBucketResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupObjectStorageBucketResultOutput, error) {
			args := v.(LookupObjectStorageBucketArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("contabo:index/getObjectStorageBucket:getObjectStorageBucket", args, LookupObjectStorageBucketResultOutput{}, options).(LookupObjectStorageBucketResultOutput), nil
		}).(LookupObjectStorageBucketResultOutput)
}

// A collection of arguments for invoking getObjectStorageBucket.
type LookupObjectStorageBucketOutputArgs struct {
	// The name of your bucket, consider the naming restriction https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-s3-bucket-naming-requirements.html.
	Name pulumi.StringPtrInput `pulumi:"name"`
	// The contabo objectStorageId on which the bucket should be created.
	ObjectStorageId pulumi.StringInput `pulumi:"objectStorageId"`
	// Choose the access to your bucket. You can not share it at all or share it publicly.
	PublicSharing pulumi.BoolPtrInput `pulumi:"publicSharing"`
}

func (LookupObjectStorageBucketOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupObjectStorageBucketArgs)(nil)).Elem()
}

// A collection of values returned by getObjectStorageBucket.
type LookupObjectStorageBucketResultOutput struct{ *pulumi.OutputState }

func (LookupObjectStorageBucketResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupObjectStorageBucketResult)(nil)).Elem()
}

func (o LookupObjectStorageBucketResultOutput) ToLookupObjectStorageBucketResultOutput() LookupObjectStorageBucketResultOutput {
	return o
}

func (o LookupObjectStorageBucketResultOutput) ToLookupObjectStorageBucketResultOutputWithContext(ctx context.Context) LookupObjectStorageBucketResultOutput {
	return o
}

// The creation date of the bucket.
func (o LookupObjectStorageBucketResultOutput) CreationDate() pulumi.StringOutput {
	return o.ApplyT(func(v LookupObjectStorageBucketResult) string { return v.CreationDate }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupObjectStorageBucketResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupObjectStorageBucketResult) string { return v.Id }).(pulumi.StringOutput)
}

// The name of your bucket, consider the naming restriction https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-s3-bucket-naming-requirements.html.
func (o LookupObjectStorageBucketResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupObjectStorageBucketResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// The contabo objectStorageId on which the bucket should be created.
func (o LookupObjectStorageBucketResultOutput) ObjectStorageId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupObjectStorageBucketResult) string { return v.ObjectStorageId }).(pulumi.StringOutput)
}

// Choose the access to your bucket. You can not share it at all or share it publicly.
func (o LookupObjectStorageBucketResultOutput) PublicSharing() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupObjectStorageBucketResult) *bool { return v.PublicSharing }).(pulumi.BoolPtrOutput)
}

// If your bucket is publicly shared, you can access it with this link.
func (o LookupObjectStorageBucketResultOutput) PublicSharingLink() pulumi.StringOutput {
	return o.ApplyT(func(v LookupObjectStorageBucketResult) string { return v.PublicSharingLink }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupObjectStorageBucketResultOutput{})
}
