// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package contabo

import (
	"context"
	"reflect"

	"github.com/lbialy/pulumi-contabo/sdk/v2/go/contabo/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Tags are Customer-defined labels which can be attached to any resource in your account. Tag API represent simple CRUD functions and allow you to manage your tags. Use tags to group your resources. For example you can define some user group with tag and give them permission to create compute instance.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/lbialy/pulumi-contabo/sdk/v2/go/contabo"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Get a specific tag by ID
//			defaultTag, err := contabo.GetTag(ctx, &contabo.LookupTagArgs{
//				Id: "26878",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("output", defaultTag)
//			return nil
//		})
//	}
//
// ```
func LookupTag(ctx *pulumi.Context, args *LookupTagArgs, opts ...pulumi.InvokeOption) (*LookupTagResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupTagResult
	err := ctx.Invoke("contabo:index/getTag:getTag", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getTag.
type LookupTagArgs struct {
	// The tag color.
	Color *string `pulumi:"color"`
	// The identifier of the tag. Use it to manage it!
	Id string `pulumi:"id"`
	// The tag name.
	Name *string `pulumi:"name"`
}

// A collection of values returned by getTag.
type LookupTagResult struct {
	// The tag color.
	Color string `pulumi:"color"`
	// The identifier of the tag. Use it to manage it!
	Id string `pulumi:"id"`
	// The tag name.
	Name string `pulumi:"name"`
}

func LookupTagOutput(ctx *pulumi.Context, args LookupTagOutputArgs, opts ...pulumi.InvokeOption) LookupTagResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupTagResultOutput, error) {
			args := v.(LookupTagArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("contabo:index/getTag:getTag", args, LookupTagResultOutput{}, options).(LookupTagResultOutput), nil
		}).(LookupTagResultOutput)
}

// A collection of arguments for invoking getTag.
type LookupTagOutputArgs struct {
	// The tag color.
	Color pulumi.StringPtrInput `pulumi:"color"`
	// The identifier of the tag. Use it to manage it!
	Id pulumi.StringInput `pulumi:"id"`
	// The tag name.
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (LookupTagOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupTagArgs)(nil)).Elem()
}

// A collection of values returned by getTag.
type LookupTagResultOutput struct{ *pulumi.OutputState }

func (LookupTagResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupTagResult)(nil)).Elem()
}

func (o LookupTagResultOutput) ToLookupTagResultOutput() LookupTagResultOutput {
	return o
}

func (o LookupTagResultOutput) ToLookupTagResultOutputWithContext(ctx context.Context) LookupTagResultOutput {
	return o
}

// The tag color.
func (o LookupTagResultOutput) Color() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTagResult) string { return v.Color }).(pulumi.StringOutput)
}

// The identifier of the tag. Use it to manage it!
func (o LookupTagResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTagResult) string { return v.Id }).(pulumi.StringOutput)
}

// The tag name.
func (o LookupTagResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTagResult) string { return v.Name }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupTagResultOutput{})
}
