// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package contabo

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/lbialy/pulumi-contabo/sdk/go/contabo/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "contabo:index/firewall:Firewall":
		r = &Firewall{}
	case "contabo:index/image:Image":
		r = &Image{}
	case "contabo:index/instance:Instance":
		r = &Instance{}
	case "contabo:index/instanceSnapshot:InstanceSnapshot":
		r = &InstanceSnapshot{}
	case "contabo:index/objectStorage:ObjectStorage":
		r = &ObjectStorage{}
	case "contabo:index/objectStorageBucket:ObjectStorageBucket":
		r = &ObjectStorageBucket{}
	case "contabo:index/privateNetwork:PrivateNetwork":
		r = &PrivateNetwork{}
	case "contabo:index/secret:Secret":
		r = &Secret{}
	case "contabo:index/tag:Tag":
		r = &Tag{}
	case "contabo:index/tagAssignment:TagAssignment":
		r = &TagAssignment{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:contabo" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"contabo",
		"index/firewall",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"contabo",
		"index/image",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"contabo",
		"index/instance",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"contabo",
		"index/instanceSnapshot",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"contabo",
		"index/objectStorage",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"contabo",
		"index/objectStorageBucket",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"contabo",
		"index/privateNetwork",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"contabo",
		"index/secret",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"contabo",
		"index/tag",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"contabo",
		"index/tagAssignment",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"contabo",
		&pkg{version},
	)
}
