// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package contabo

import (
	"context"
	"reflect"

	"github.com/lbialy/pulumi-contabo/sdk/v2/go/contabo/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
type InstanceSnapshot struct {
	pulumi.CustomResourceState

	// The date when the snapshot will be autmatically deleted.
	AutoDeleteDate pulumi.StringOutput `pulumi:"autoDeleteDate"`
	// The creation date of this instance snapshot.
	CreatedDate pulumi.StringOutput `pulumi:"createdDate"`
	// Description of this snapshot.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Id of the Image the snapshot was taken from.
	ImageId pulumi.StringOutput `pulumi:"imageId"`
	// Name of the Image the snapshot was taken from.
	ImageName pulumi.StringOutput `pulumi:"imageName"`
	// Instance identifier associated with the snapshot.
	InstanceId pulumi.IntPtrOutput `pulumi:"instanceId"`
	// Name of the snapshot.
	Name pulumi.StringOutput `pulumi:"name"`
}

// NewInstanceSnapshot registers a new resource with the given unique name, arguments, and options.
func NewInstanceSnapshot(ctx *pulumi.Context,
	name string, args *InstanceSnapshotArgs, opts ...pulumi.ResourceOption) (*InstanceSnapshot, error) {
	if args == nil {
		args = &InstanceSnapshotArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource InstanceSnapshot
	err := ctx.RegisterResource("contabo:index/instanceSnapshot:InstanceSnapshot", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetInstanceSnapshot gets an existing InstanceSnapshot resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetInstanceSnapshot(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *InstanceSnapshotState, opts ...pulumi.ResourceOption) (*InstanceSnapshot, error) {
	var resource InstanceSnapshot
	err := ctx.ReadResource("contabo:index/instanceSnapshot:InstanceSnapshot", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering InstanceSnapshot resources.
type instanceSnapshotState struct {
	// The date when the snapshot will be autmatically deleted.
	AutoDeleteDate *string `pulumi:"autoDeleteDate"`
	// The creation date of this instance snapshot.
	CreatedDate *string `pulumi:"createdDate"`
	// Description of this snapshot.
	Description *string `pulumi:"description"`
	// Id of the Image the snapshot was taken from.
	ImageId *string `pulumi:"imageId"`
	// Name of the Image the snapshot was taken from.
	ImageName *string `pulumi:"imageName"`
	// Instance identifier associated with the snapshot.
	InstanceId *int `pulumi:"instanceId"`
	// Name of the snapshot.
	Name *string `pulumi:"name"`
}

type InstanceSnapshotState struct {
	// The date when the snapshot will be autmatically deleted.
	AutoDeleteDate pulumi.StringPtrInput
	// The creation date of this instance snapshot.
	CreatedDate pulumi.StringPtrInput
	// Description of this snapshot.
	Description pulumi.StringPtrInput
	// Id of the Image the snapshot was taken from.
	ImageId pulumi.StringPtrInput
	// Name of the Image the snapshot was taken from.
	ImageName pulumi.StringPtrInput
	// Instance identifier associated with the snapshot.
	InstanceId pulumi.IntPtrInput
	// Name of the snapshot.
	Name pulumi.StringPtrInput
}

func (InstanceSnapshotState) ElementType() reflect.Type {
	return reflect.TypeOf((*instanceSnapshotState)(nil)).Elem()
}

type instanceSnapshotArgs struct {
	// The creation date of this instance snapshot.
	CreatedDate *string `pulumi:"createdDate"`
	// Description of this snapshot.
	Description *string `pulumi:"description"`
	// Instance identifier associated with the snapshot.
	InstanceId *int `pulumi:"instanceId"`
	// Name of the snapshot.
	Name *string `pulumi:"name"`
}

// The set of arguments for constructing a InstanceSnapshot resource.
type InstanceSnapshotArgs struct {
	// The creation date of this instance snapshot.
	CreatedDate pulumi.StringPtrInput
	// Description of this snapshot.
	Description pulumi.StringPtrInput
	// Instance identifier associated with the snapshot.
	InstanceId pulumi.IntPtrInput
	// Name of the snapshot.
	Name pulumi.StringPtrInput
}

func (InstanceSnapshotArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*instanceSnapshotArgs)(nil)).Elem()
}

type InstanceSnapshotInput interface {
	pulumi.Input

	ToInstanceSnapshotOutput() InstanceSnapshotOutput
	ToInstanceSnapshotOutputWithContext(ctx context.Context) InstanceSnapshotOutput
}

func (*InstanceSnapshot) ElementType() reflect.Type {
	return reflect.TypeOf((**InstanceSnapshot)(nil)).Elem()
}

func (i *InstanceSnapshot) ToInstanceSnapshotOutput() InstanceSnapshotOutput {
	return i.ToInstanceSnapshotOutputWithContext(context.Background())
}

func (i *InstanceSnapshot) ToInstanceSnapshotOutputWithContext(ctx context.Context) InstanceSnapshotOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceSnapshotOutput)
}

// InstanceSnapshotArrayInput is an input type that accepts InstanceSnapshotArray and InstanceSnapshotArrayOutput values.
// You can construct a concrete instance of `InstanceSnapshotArrayInput` via:
//
//	InstanceSnapshotArray{ InstanceSnapshotArgs{...} }
type InstanceSnapshotArrayInput interface {
	pulumi.Input

	ToInstanceSnapshotArrayOutput() InstanceSnapshotArrayOutput
	ToInstanceSnapshotArrayOutputWithContext(context.Context) InstanceSnapshotArrayOutput
}

type InstanceSnapshotArray []InstanceSnapshotInput

func (InstanceSnapshotArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*InstanceSnapshot)(nil)).Elem()
}

func (i InstanceSnapshotArray) ToInstanceSnapshotArrayOutput() InstanceSnapshotArrayOutput {
	return i.ToInstanceSnapshotArrayOutputWithContext(context.Background())
}

func (i InstanceSnapshotArray) ToInstanceSnapshotArrayOutputWithContext(ctx context.Context) InstanceSnapshotArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceSnapshotArrayOutput)
}

// InstanceSnapshotMapInput is an input type that accepts InstanceSnapshotMap and InstanceSnapshotMapOutput values.
// You can construct a concrete instance of `InstanceSnapshotMapInput` via:
//
//	InstanceSnapshotMap{ "key": InstanceSnapshotArgs{...} }
type InstanceSnapshotMapInput interface {
	pulumi.Input

	ToInstanceSnapshotMapOutput() InstanceSnapshotMapOutput
	ToInstanceSnapshotMapOutputWithContext(context.Context) InstanceSnapshotMapOutput
}

type InstanceSnapshotMap map[string]InstanceSnapshotInput

func (InstanceSnapshotMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*InstanceSnapshot)(nil)).Elem()
}

func (i InstanceSnapshotMap) ToInstanceSnapshotMapOutput() InstanceSnapshotMapOutput {
	return i.ToInstanceSnapshotMapOutputWithContext(context.Background())
}

func (i InstanceSnapshotMap) ToInstanceSnapshotMapOutputWithContext(ctx context.Context) InstanceSnapshotMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceSnapshotMapOutput)
}

type InstanceSnapshotOutput struct{ *pulumi.OutputState }

func (InstanceSnapshotOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**InstanceSnapshot)(nil)).Elem()
}

func (o InstanceSnapshotOutput) ToInstanceSnapshotOutput() InstanceSnapshotOutput {
	return o
}

func (o InstanceSnapshotOutput) ToInstanceSnapshotOutputWithContext(ctx context.Context) InstanceSnapshotOutput {
	return o
}

// The date when the snapshot will be autmatically deleted.
func (o InstanceSnapshotOutput) AutoDeleteDate() pulumi.StringOutput {
	return o.ApplyT(func(v *InstanceSnapshot) pulumi.StringOutput { return v.AutoDeleteDate }).(pulumi.StringOutput)
}

// The creation date of this instance snapshot.
func (o InstanceSnapshotOutput) CreatedDate() pulumi.StringOutput {
	return o.ApplyT(func(v *InstanceSnapshot) pulumi.StringOutput { return v.CreatedDate }).(pulumi.StringOutput)
}

// Description of this snapshot.
func (o InstanceSnapshotOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *InstanceSnapshot) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Id of the Image the snapshot was taken from.
func (o InstanceSnapshotOutput) ImageId() pulumi.StringOutput {
	return o.ApplyT(func(v *InstanceSnapshot) pulumi.StringOutput { return v.ImageId }).(pulumi.StringOutput)
}

// Name of the Image the snapshot was taken from.
func (o InstanceSnapshotOutput) ImageName() pulumi.StringOutput {
	return o.ApplyT(func(v *InstanceSnapshot) pulumi.StringOutput { return v.ImageName }).(pulumi.StringOutput)
}

// Instance identifier associated with the snapshot.
func (o InstanceSnapshotOutput) InstanceId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *InstanceSnapshot) pulumi.IntPtrOutput { return v.InstanceId }).(pulumi.IntPtrOutput)
}

// Name of the snapshot.
func (o InstanceSnapshotOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *InstanceSnapshot) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

type InstanceSnapshotArrayOutput struct{ *pulumi.OutputState }

func (InstanceSnapshotArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*InstanceSnapshot)(nil)).Elem()
}

func (o InstanceSnapshotArrayOutput) ToInstanceSnapshotArrayOutput() InstanceSnapshotArrayOutput {
	return o
}

func (o InstanceSnapshotArrayOutput) ToInstanceSnapshotArrayOutputWithContext(ctx context.Context) InstanceSnapshotArrayOutput {
	return o
}

func (o InstanceSnapshotArrayOutput) Index(i pulumi.IntInput) InstanceSnapshotOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *InstanceSnapshot {
		return vs[0].([]*InstanceSnapshot)[vs[1].(int)]
	}).(InstanceSnapshotOutput)
}

type InstanceSnapshotMapOutput struct{ *pulumi.OutputState }

func (InstanceSnapshotMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*InstanceSnapshot)(nil)).Elem()
}

func (o InstanceSnapshotMapOutput) ToInstanceSnapshotMapOutput() InstanceSnapshotMapOutput {
	return o
}

func (o InstanceSnapshotMapOutput) ToInstanceSnapshotMapOutputWithContext(ctx context.Context) InstanceSnapshotMapOutput {
	return o
}

func (o InstanceSnapshotMapOutput) MapIndex(k pulumi.StringInput) InstanceSnapshotOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *InstanceSnapshot {
		return vs[0].(map[string]*InstanceSnapshot)[vs[1].(string)]
	}).(InstanceSnapshotOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*InstanceSnapshotInput)(nil)).Elem(), &InstanceSnapshot{})
	pulumi.RegisterInputType(reflect.TypeOf((*InstanceSnapshotArrayInput)(nil)).Elem(), InstanceSnapshotArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*InstanceSnapshotMapInput)(nil)).Elem(), InstanceSnapshotMap{})
	pulumi.RegisterOutputType(InstanceSnapshotOutput{})
	pulumi.RegisterOutputType(InstanceSnapshotArrayOutput{})
	pulumi.RegisterOutputType(InstanceSnapshotMapOutput{})
}
