// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package contabo

import (
	"context"
	"reflect"

	"github.com/lbialy/pulumi-contabo/sdk/go/contabo/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Provides a Contabo [Private Network](https://api.contabo.com/#tag/Private-Networks) resource.  Private Networks can contain your compute instances whereby they are able to communicate with each other in full usolation, using private IP addresses.
type PrivateNetwork struct {
	pulumi.CustomResourceState

	// The totality of available IPs in the Private Network.
	AvailableIps pulumi.IntOutput `pulumi:"availableIps"`
	// The cidr range of the Private Network.
	Cidr pulumi.StringOutput `pulumi:"cidr"`
	// The creation date of the Private Network.
	CreatedDate pulumi.StringOutput `pulumi:"createdDate"`
	// The specific data center where the Private Network is located.
	DataCenter pulumi.StringOutput `pulumi:"dataCenter"`
	// The description of the Private Network. There is a limit of 255 characters per Private Network.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Add the instace Ids to the private network here. If you do not add any instance Ids an empty private network will be created.
	InstanceIds pulumi.IntArrayOutput             `pulumi:"instanceIds"`
	Instances   PrivateNetworkInstanceArrayOutput `pulumi:"instances"`
	// The name of the Private Network. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Private Network name.
	Name pulumi.StringOutput `pulumi:"name"`
	// The region where the Private Network should be located. Default region is the EU.
	Region pulumi.StringPtrOutput `pulumi:"region"`
	// The name of the region where the Private Network is located.
	RegionName pulumi.StringOutput `pulumi:"regionName"`
	// Time of the last update of the private network.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
}

// NewPrivateNetwork registers a new resource with the given unique name, arguments, and options.
func NewPrivateNetwork(ctx *pulumi.Context,
	name string, args *PrivateNetworkArgs, opts ...pulumi.ResourceOption) (*PrivateNetwork, error) {
	if args == nil {
		args = &PrivateNetworkArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource PrivateNetwork
	err := ctx.RegisterResource("contabo:index/privateNetwork:PrivateNetwork", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPrivateNetwork gets an existing PrivateNetwork resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPrivateNetwork(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PrivateNetworkState, opts ...pulumi.ResourceOption) (*PrivateNetwork, error) {
	var resource PrivateNetwork
	err := ctx.ReadResource("contabo:index/privateNetwork:PrivateNetwork", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PrivateNetwork resources.
type privateNetworkState struct {
	// The totality of available IPs in the Private Network.
	AvailableIps *int `pulumi:"availableIps"`
	// The cidr range of the Private Network.
	Cidr *string `pulumi:"cidr"`
	// The creation date of the Private Network.
	CreatedDate *string `pulumi:"createdDate"`
	// The specific data center where the Private Network is located.
	DataCenter *string `pulumi:"dataCenter"`
	// The description of the Private Network. There is a limit of 255 characters per Private Network.
	Description *string `pulumi:"description"`
	// Add the instace Ids to the private network here. If you do not add any instance Ids an empty private network will be created.
	InstanceIds []int                    `pulumi:"instanceIds"`
	Instances   []PrivateNetworkInstance `pulumi:"instances"`
	// The name of the Private Network. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Private Network name.
	Name *string `pulumi:"name"`
	// The region where the Private Network should be located. Default region is the EU.
	Region *string `pulumi:"region"`
	// The name of the region where the Private Network is located.
	RegionName *string `pulumi:"regionName"`
	// Time of the last update of the private network.
	UpdatedAt *string `pulumi:"updatedAt"`
}

type PrivateNetworkState struct {
	// The totality of available IPs in the Private Network.
	AvailableIps pulumi.IntPtrInput
	// The cidr range of the Private Network.
	Cidr pulumi.StringPtrInput
	// The creation date of the Private Network.
	CreatedDate pulumi.StringPtrInput
	// The specific data center where the Private Network is located.
	DataCenter pulumi.StringPtrInput
	// The description of the Private Network. There is a limit of 255 characters per Private Network.
	Description pulumi.StringPtrInput
	// Add the instace Ids to the private network here. If you do not add any instance Ids an empty private network will be created.
	InstanceIds pulumi.IntArrayInput
	Instances   PrivateNetworkInstanceArrayInput
	// The name of the Private Network. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Private Network name.
	Name pulumi.StringPtrInput
	// The region where the Private Network should be located. Default region is the EU.
	Region pulumi.StringPtrInput
	// The name of the region where the Private Network is located.
	RegionName pulumi.StringPtrInput
	// Time of the last update of the private network.
	UpdatedAt pulumi.StringPtrInput
}

func (PrivateNetworkState) ElementType() reflect.Type {
	return reflect.TypeOf((*privateNetworkState)(nil)).Elem()
}

type privateNetworkArgs struct {
	// The creation date of the Private Network.
	CreatedDate *string `pulumi:"createdDate"`
	// The description of the Private Network. There is a limit of 255 characters per Private Network.
	Description *string `pulumi:"description"`
	// Add the instace Ids to the private network here. If you do not add any instance Ids an empty private network will be created.
	InstanceIds []int `pulumi:"instanceIds"`
	// The name of the Private Network. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Private Network name.
	Name *string `pulumi:"name"`
	// The region where the Private Network should be located. Default region is the EU.
	Region *string `pulumi:"region"`
	// The name of the region where the Private Network is located.
	RegionName *string `pulumi:"regionName"`
	// Time of the last update of the private network.
	UpdatedAt *string `pulumi:"updatedAt"`
}

// The set of arguments for constructing a PrivateNetwork resource.
type PrivateNetworkArgs struct {
	// The creation date of the Private Network.
	CreatedDate pulumi.StringPtrInput
	// The description of the Private Network. There is a limit of 255 characters per Private Network.
	Description pulumi.StringPtrInput
	// Add the instace Ids to the private network here. If you do not add any instance Ids an empty private network will be created.
	InstanceIds pulumi.IntArrayInput
	// The name of the Private Network. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Private Network name.
	Name pulumi.StringPtrInput
	// The region where the Private Network should be located. Default region is the EU.
	Region pulumi.StringPtrInput
	// The name of the region where the Private Network is located.
	RegionName pulumi.StringPtrInput
	// Time of the last update of the private network.
	UpdatedAt pulumi.StringPtrInput
}

func (PrivateNetworkArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*privateNetworkArgs)(nil)).Elem()
}

type PrivateNetworkInput interface {
	pulumi.Input

	ToPrivateNetworkOutput() PrivateNetworkOutput
	ToPrivateNetworkOutputWithContext(ctx context.Context) PrivateNetworkOutput
}

func (*PrivateNetwork) ElementType() reflect.Type {
	return reflect.TypeOf((**PrivateNetwork)(nil)).Elem()
}

func (i *PrivateNetwork) ToPrivateNetworkOutput() PrivateNetworkOutput {
	return i.ToPrivateNetworkOutputWithContext(context.Background())
}

func (i *PrivateNetwork) ToPrivateNetworkOutputWithContext(ctx context.Context) PrivateNetworkOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PrivateNetworkOutput)
}

// PrivateNetworkArrayInput is an input type that accepts PrivateNetworkArray and PrivateNetworkArrayOutput values.
// You can construct a concrete instance of `PrivateNetworkArrayInput` via:
//
//	PrivateNetworkArray{ PrivateNetworkArgs{...} }
type PrivateNetworkArrayInput interface {
	pulumi.Input

	ToPrivateNetworkArrayOutput() PrivateNetworkArrayOutput
	ToPrivateNetworkArrayOutputWithContext(context.Context) PrivateNetworkArrayOutput
}

type PrivateNetworkArray []PrivateNetworkInput

func (PrivateNetworkArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PrivateNetwork)(nil)).Elem()
}

func (i PrivateNetworkArray) ToPrivateNetworkArrayOutput() PrivateNetworkArrayOutput {
	return i.ToPrivateNetworkArrayOutputWithContext(context.Background())
}

func (i PrivateNetworkArray) ToPrivateNetworkArrayOutputWithContext(ctx context.Context) PrivateNetworkArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PrivateNetworkArrayOutput)
}

// PrivateNetworkMapInput is an input type that accepts PrivateNetworkMap and PrivateNetworkMapOutput values.
// You can construct a concrete instance of `PrivateNetworkMapInput` via:
//
//	PrivateNetworkMap{ "key": PrivateNetworkArgs{...} }
type PrivateNetworkMapInput interface {
	pulumi.Input

	ToPrivateNetworkMapOutput() PrivateNetworkMapOutput
	ToPrivateNetworkMapOutputWithContext(context.Context) PrivateNetworkMapOutput
}

type PrivateNetworkMap map[string]PrivateNetworkInput

func (PrivateNetworkMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PrivateNetwork)(nil)).Elem()
}

func (i PrivateNetworkMap) ToPrivateNetworkMapOutput() PrivateNetworkMapOutput {
	return i.ToPrivateNetworkMapOutputWithContext(context.Background())
}

func (i PrivateNetworkMap) ToPrivateNetworkMapOutputWithContext(ctx context.Context) PrivateNetworkMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PrivateNetworkMapOutput)
}

type PrivateNetworkOutput struct{ *pulumi.OutputState }

func (PrivateNetworkOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PrivateNetwork)(nil)).Elem()
}

func (o PrivateNetworkOutput) ToPrivateNetworkOutput() PrivateNetworkOutput {
	return o
}

func (o PrivateNetworkOutput) ToPrivateNetworkOutputWithContext(ctx context.Context) PrivateNetworkOutput {
	return o
}

// The totality of available IPs in the Private Network.
func (o PrivateNetworkOutput) AvailableIps() pulumi.IntOutput {
	return o.ApplyT(func(v *PrivateNetwork) pulumi.IntOutput { return v.AvailableIps }).(pulumi.IntOutput)
}

// The cidr range of the Private Network.
func (o PrivateNetworkOutput) Cidr() pulumi.StringOutput {
	return o.ApplyT(func(v *PrivateNetwork) pulumi.StringOutput { return v.Cidr }).(pulumi.StringOutput)
}

// The creation date of the Private Network.
func (o PrivateNetworkOutput) CreatedDate() pulumi.StringOutput {
	return o.ApplyT(func(v *PrivateNetwork) pulumi.StringOutput { return v.CreatedDate }).(pulumi.StringOutput)
}

// The specific data center where the Private Network is located.
func (o PrivateNetworkOutput) DataCenter() pulumi.StringOutput {
	return o.ApplyT(func(v *PrivateNetwork) pulumi.StringOutput { return v.DataCenter }).(pulumi.StringOutput)
}

// The description of the Private Network. There is a limit of 255 characters per Private Network.
func (o PrivateNetworkOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PrivateNetwork) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Add the instace Ids to the private network here. If you do not add any instance Ids an empty private network will be created.
func (o PrivateNetworkOutput) InstanceIds() pulumi.IntArrayOutput {
	return o.ApplyT(func(v *PrivateNetwork) pulumi.IntArrayOutput { return v.InstanceIds }).(pulumi.IntArrayOutput)
}

func (o PrivateNetworkOutput) Instances() PrivateNetworkInstanceArrayOutput {
	return o.ApplyT(func(v *PrivateNetwork) PrivateNetworkInstanceArrayOutput { return v.Instances }).(PrivateNetworkInstanceArrayOutput)
}

// The name of the Private Network. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Private Network name.
func (o PrivateNetworkOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *PrivateNetwork) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The region where the Private Network should be located. Default region is the EU.
func (o PrivateNetworkOutput) Region() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PrivateNetwork) pulumi.StringPtrOutput { return v.Region }).(pulumi.StringPtrOutput)
}

// The name of the region where the Private Network is located.
func (o PrivateNetworkOutput) RegionName() pulumi.StringOutput {
	return o.ApplyT(func(v *PrivateNetwork) pulumi.StringOutput { return v.RegionName }).(pulumi.StringOutput)
}

// Time of the last update of the private network.
func (o PrivateNetworkOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *PrivateNetwork) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

type PrivateNetworkArrayOutput struct{ *pulumi.OutputState }

func (PrivateNetworkArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PrivateNetwork)(nil)).Elem()
}

func (o PrivateNetworkArrayOutput) ToPrivateNetworkArrayOutput() PrivateNetworkArrayOutput {
	return o
}

func (o PrivateNetworkArrayOutput) ToPrivateNetworkArrayOutputWithContext(ctx context.Context) PrivateNetworkArrayOutput {
	return o
}

func (o PrivateNetworkArrayOutput) Index(i pulumi.IntInput) PrivateNetworkOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *PrivateNetwork {
		return vs[0].([]*PrivateNetwork)[vs[1].(int)]
	}).(PrivateNetworkOutput)
}

type PrivateNetworkMapOutput struct{ *pulumi.OutputState }

func (PrivateNetworkMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PrivateNetwork)(nil)).Elem()
}

func (o PrivateNetworkMapOutput) ToPrivateNetworkMapOutput() PrivateNetworkMapOutput {
	return o
}

func (o PrivateNetworkMapOutput) ToPrivateNetworkMapOutputWithContext(ctx context.Context) PrivateNetworkMapOutput {
	return o
}

func (o PrivateNetworkMapOutput) MapIndex(k pulumi.StringInput) PrivateNetworkOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *PrivateNetwork {
		return vs[0].(map[string]*PrivateNetwork)[vs[1].(string)]
	}).(PrivateNetworkOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PrivateNetworkInput)(nil)).Elem(), &PrivateNetwork{})
	pulumi.RegisterInputType(reflect.TypeOf((*PrivateNetworkArrayInput)(nil)).Elem(), PrivateNetworkArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*PrivateNetworkMapInput)(nil)).Elem(), PrivateNetworkMap{})
	pulumi.RegisterOutputType(PrivateNetworkOutput{})
	pulumi.RegisterOutputType(PrivateNetworkArrayOutput{})
	pulumi.RegisterOutputType(PrivateNetworkMapOutput{})
}
