// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package contabo

import (
	"context"
	"reflect"

	"github.com/lbialy/pulumi-contabo/sdk/v2/go/contabo/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Tag assignment marks the specified resource with the specified tag for organizing purposes or to restrict access to that resource.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/lbialy/pulumi-contabo/sdk/v2/go/contabo"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Create a new tag assignment
//			_, err := contabo.NewTagAssignment(ctx, "default_tag_assignment", &contabo.TagAssignmentArgs{
//				TagId:        pulumi.Int(178478),
//				ResourceType: pulumi.String("image"),
//				ResourceId:   pulumi.String("35ee288f-21ea-420c-a074-ce0a968b59c0"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type TagAssignment struct {
	pulumi.CustomResourceState

	// The resource id.
	ResourceId pulumi.StringOutput `pulumi:"resourceId"`
	// The resource name.
	ResourceName pulumi.StringOutput `pulumi:"resourceName"`
	// The resource type.
	ResourceType pulumi.StringOutput `pulumi:"resourceType"`
	// The identifier of the tag.
	TagId pulumi.IntOutput `pulumi:"tagId"`
	// The name of the tag.
	TagName pulumi.StringOutput `pulumi:"tagName"`
}

// NewTagAssignment registers a new resource with the given unique name, arguments, and options.
func NewTagAssignment(ctx *pulumi.Context,
	name string, args *TagAssignmentArgs, opts ...pulumi.ResourceOption) (*TagAssignment, error) {
	if args == nil {
		args = &TagAssignmentArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource TagAssignment
	err := ctx.RegisterResource("contabo:index/tagAssignment:TagAssignment", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetTagAssignment gets an existing TagAssignment resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetTagAssignment(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *TagAssignmentState, opts ...pulumi.ResourceOption) (*TagAssignment, error) {
	var resource TagAssignment
	err := ctx.ReadResource("contabo:index/tagAssignment:TagAssignment", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering TagAssignment resources.
type tagAssignmentState struct {
	// The resource id.
	ResourceId *string `pulumi:"resourceId"`
	// The resource name.
	ResourceName *string `pulumi:"resourceName"`
	// The resource type.
	ResourceType *string `pulumi:"resourceType"`
	// The identifier of the tag.
	TagId *int `pulumi:"tagId"`
	// The name of the tag.
	TagName *string `pulumi:"tagName"`
}

type TagAssignmentState struct {
	// The resource id.
	ResourceId pulumi.StringPtrInput
	// The resource name.
	ResourceName pulumi.StringPtrInput
	// The resource type.
	ResourceType pulumi.StringPtrInput
	// The identifier of the tag.
	TagId pulumi.IntPtrInput
	// The name of the tag.
	TagName pulumi.StringPtrInput
}

func (TagAssignmentState) ElementType() reflect.Type {
	return reflect.TypeOf((*tagAssignmentState)(nil)).Elem()
}

type tagAssignmentArgs struct {
	// The resource id.
	ResourceId *string `pulumi:"resourceId"`
	// The resource type.
	ResourceType *string `pulumi:"resourceType"`
	// The identifier of the tag.
	TagId *int `pulumi:"tagId"`
}

// The set of arguments for constructing a TagAssignment resource.
type TagAssignmentArgs struct {
	// The resource id.
	ResourceId pulumi.StringPtrInput
	// The resource type.
	ResourceType pulumi.StringPtrInput
	// The identifier of the tag.
	TagId pulumi.IntPtrInput
}

func (TagAssignmentArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*tagAssignmentArgs)(nil)).Elem()
}

type TagAssignmentInput interface {
	pulumi.Input

	ToTagAssignmentOutput() TagAssignmentOutput
	ToTagAssignmentOutputWithContext(ctx context.Context) TagAssignmentOutput
}

func (*TagAssignment) ElementType() reflect.Type {
	return reflect.TypeOf((**TagAssignment)(nil)).Elem()
}

func (i *TagAssignment) ToTagAssignmentOutput() TagAssignmentOutput {
	return i.ToTagAssignmentOutputWithContext(context.Background())
}

func (i *TagAssignment) ToTagAssignmentOutputWithContext(ctx context.Context) TagAssignmentOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TagAssignmentOutput)
}

// TagAssignmentArrayInput is an input type that accepts TagAssignmentArray and TagAssignmentArrayOutput values.
// You can construct a concrete instance of `TagAssignmentArrayInput` via:
//
//	TagAssignmentArray{ TagAssignmentArgs{...} }
type TagAssignmentArrayInput interface {
	pulumi.Input

	ToTagAssignmentArrayOutput() TagAssignmentArrayOutput
	ToTagAssignmentArrayOutputWithContext(context.Context) TagAssignmentArrayOutput
}

type TagAssignmentArray []TagAssignmentInput

func (TagAssignmentArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*TagAssignment)(nil)).Elem()
}

func (i TagAssignmentArray) ToTagAssignmentArrayOutput() TagAssignmentArrayOutput {
	return i.ToTagAssignmentArrayOutputWithContext(context.Background())
}

func (i TagAssignmentArray) ToTagAssignmentArrayOutputWithContext(ctx context.Context) TagAssignmentArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TagAssignmentArrayOutput)
}

// TagAssignmentMapInput is an input type that accepts TagAssignmentMap and TagAssignmentMapOutput values.
// You can construct a concrete instance of `TagAssignmentMapInput` via:
//
//	TagAssignmentMap{ "key": TagAssignmentArgs{...} }
type TagAssignmentMapInput interface {
	pulumi.Input

	ToTagAssignmentMapOutput() TagAssignmentMapOutput
	ToTagAssignmentMapOutputWithContext(context.Context) TagAssignmentMapOutput
}

type TagAssignmentMap map[string]TagAssignmentInput

func (TagAssignmentMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*TagAssignment)(nil)).Elem()
}

func (i TagAssignmentMap) ToTagAssignmentMapOutput() TagAssignmentMapOutput {
	return i.ToTagAssignmentMapOutputWithContext(context.Background())
}

func (i TagAssignmentMap) ToTagAssignmentMapOutputWithContext(ctx context.Context) TagAssignmentMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TagAssignmentMapOutput)
}

type TagAssignmentOutput struct{ *pulumi.OutputState }

func (TagAssignmentOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**TagAssignment)(nil)).Elem()
}

func (o TagAssignmentOutput) ToTagAssignmentOutput() TagAssignmentOutput {
	return o
}

func (o TagAssignmentOutput) ToTagAssignmentOutputWithContext(ctx context.Context) TagAssignmentOutput {
	return o
}

// The resource id.
func (o TagAssignmentOutput) ResourceId() pulumi.StringOutput {
	return o.ApplyT(func(v *TagAssignment) pulumi.StringOutput { return v.ResourceId }).(pulumi.StringOutput)
}

// The resource name.
func (o TagAssignmentOutput) ResourceName() pulumi.StringOutput {
	return o.ApplyT(func(v *TagAssignment) pulumi.StringOutput { return v.ResourceName }).(pulumi.StringOutput)
}

// The resource type.
func (o TagAssignmentOutput) ResourceType() pulumi.StringOutput {
	return o.ApplyT(func(v *TagAssignment) pulumi.StringOutput { return v.ResourceType }).(pulumi.StringOutput)
}

// The identifier of the tag.
func (o TagAssignmentOutput) TagId() pulumi.IntOutput {
	return o.ApplyT(func(v *TagAssignment) pulumi.IntOutput { return v.TagId }).(pulumi.IntOutput)
}

// The name of the tag.
func (o TagAssignmentOutput) TagName() pulumi.StringOutput {
	return o.ApplyT(func(v *TagAssignment) pulumi.StringOutput { return v.TagName }).(pulumi.StringOutput)
}

type TagAssignmentArrayOutput struct{ *pulumi.OutputState }

func (TagAssignmentArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*TagAssignment)(nil)).Elem()
}

func (o TagAssignmentArrayOutput) ToTagAssignmentArrayOutput() TagAssignmentArrayOutput {
	return o
}

func (o TagAssignmentArrayOutput) ToTagAssignmentArrayOutputWithContext(ctx context.Context) TagAssignmentArrayOutput {
	return o
}

func (o TagAssignmentArrayOutput) Index(i pulumi.IntInput) TagAssignmentOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *TagAssignment {
		return vs[0].([]*TagAssignment)[vs[1].(int)]
	}).(TagAssignmentOutput)
}

type TagAssignmentMapOutput struct{ *pulumi.OutputState }

func (TagAssignmentMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*TagAssignment)(nil)).Elem()
}

func (o TagAssignmentMapOutput) ToTagAssignmentMapOutput() TagAssignmentMapOutput {
	return o
}

func (o TagAssignmentMapOutput) ToTagAssignmentMapOutputWithContext(ctx context.Context) TagAssignmentMapOutput {
	return o
}

func (o TagAssignmentMapOutput) MapIndex(k pulumi.StringInput) TagAssignmentOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *TagAssignment {
		return vs[0].(map[string]*TagAssignment)[vs[1].(string)]
	}).(TagAssignmentOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TagAssignmentInput)(nil)).Elem(), &TagAssignment{})
	pulumi.RegisterInputType(reflect.TypeOf((*TagAssignmentArrayInput)(nil)).Elem(), TagAssignmentArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*TagAssignmentMapInput)(nil)).Elem(), TagAssignmentMap{})
	pulumi.RegisterOutputType(TagAssignmentOutput{})
	pulumi.RegisterOutputType(TagAssignmentArrayOutput{})
	pulumi.RegisterOutputType(TagAssignmentMapOutput{})
}
