// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbialy.Contabo.Outputs
{

    [OutputType]
    public sealed class FirewallInstancesStatus
    {
        /// <summary>
        /// Status of the instance.
        /// </summary>
        public readonly string? ErrorMessage;
        /// <summary>
        /// The instance
        /// </summary>
        public readonly int? InstanceId;
        /// <summary>
        /// Status of the instance.
        /// </summary>
        public readonly string? Status;

        [OutputConstructor]
        private FirewallInstancesStatus(
            string? errorMessage,

            int? instanceId,

            string? status)
        {
            ErrorMessage = errorMessage;
            InstanceId = instanceId;
            Status = status;
        }
    }
}
