// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbialy.Contabo.Outputs
{

    [OutputType]
    public sealed class FirewallRuleInboundSrcCidr
    {
        /// <summary>
        /// Provide allowed IPv4 addresses as string array for this rule
        /// </summary>
        public readonly ImmutableArray<string> Ipv4s;
        /// <summary>
        /// Provide allowed IPv6 addresses as string array for this rule
        /// </summary>
        public readonly ImmutableArray<string> Ipv6s;

        [OutputConstructor]
        private FirewallRuleInboundSrcCidr(
            ImmutableArray<string> ipv4s,

            ImmutableArray<string> ipv6s)
        {
            Ipv4s = ipv4s;
            Ipv6s = ipv6s;
        }
    }
}
