// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbialy.Contabo.Outputs
{

    [OutputType]
    public sealed class GetInstanceIpConfigV6Result
    {
        /// <summary>
        /// Gateway
        /// </summary>
        public readonly string Gateway;
        /// <summary>
        /// IP Address
        /// </summary>
        public readonly string Ip;
        /// <summary>
        /// Netmask CIDR
        /// </summary>
        public readonly int NetmaskCidr;

        [OutputConstructor]
        private GetInstanceIpConfigV6Result(
            string gateway,

            string ip,

            int netmaskCidr)
        {
            Gateway = gateway;
            Ip = ip;
            NetmaskCidr = netmaskCidr;
        }
    }
}
