// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbialy.Contabo.Outputs
{

    [OutputType]
    public sealed class GetInstanceAddOnResult
    {
        /// <summary>
        /// Id of the Addon. Please refer to list [here](https://contabo.com/en/product-list/?show_ids=true).
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The number of Addons you wish to aquire.
        /// </summary>
        public readonly int Quantity;

        [OutputConstructor]
        private GetInstanceAddOnResult(
            string id,

            int quantity)
        {
            Id = id;
            Quantity = quantity;
        }
    }
}
