// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbialy.Contabo.Outputs
{

    [OutputType]
    public sealed class GetInstanceIpConfigResult
    {
        public readonly ImmutableArray<Outputs.GetInstanceIpConfigV4Result> V4s;
        public readonly ImmutableArray<Outputs.GetInstanceIpConfigV6Result> V6s;

        [OutputConstructor]
        private GetInstanceIpConfigResult(
            ImmutableArray<Outputs.GetInstanceIpConfigV4Result> v4s,

            ImmutableArray<Outputs.GetInstanceIpConfigV6Result> v6s)
        {
            V4s = v4s;
            V6s = v6s;
        }
    }
}
