// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbialy.Contabo.Outputs
{

    [OutputType]
    public sealed class GetObjectStorageAutoScalingResult
    {
        /// <summary>
        /// If the autoscaling is in an error state (see status property), the error message can be seen in this field.
        /// </summary>
        public readonly string ErrorMessage;
        /// <summary>
        /// Autoscaling size limit for the current object storage.
        /// </summary>
        public readonly double SizeLimitTb;
        /// <summary>
        /// Status of this object storage.  It can be set to `Enabled`, `Disabled` or `Error`.
        /// </summary>
        public readonly string State;

        [OutputConstructor]
        private GetObjectStorageAutoScalingResult(
            string errorMessage,

            double sizeLimitTb,

            string state)
        {
            ErrorMessage = errorMessage;
            SizeLimitTb = sizeLimitTb;
            State = state;
        }
    }
}
