// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbialy.Contabo.Outputs
{

    [OutputType]
    public sealed class PrivateNetworkInstancePrivateIpConfig
    {
        public readonly ImmutableArray<Outputs.PrivateNetworkInstancePrivateIpConfigV4> V4s;

        [OutputConstructor]
        private PrivateNetworkInstancePrivateIpConfig(ImmutableArray<Outputs.PrivateNetworkInstancePrivateIpConfigV4> v4s)
        {
            V4s = v4s;
        }
    }
}
