# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .firewall import *
from .get_firewall import *
from .get_image import *
from .get_instance import *
from .get_instance_snapshot import *
from .get_object_storage import *
from .get_object_storage_bucket import *
from .get_private_network import *
from .get_secret import *
from .get_tag import *
from .get_tag_assignment import *
from .image import *
from .instance import *
from .instance_snapshot import *
from .object_storage import *
from .object_storage_bucket import *
from .private_network import *
from .provider import *
from .secret import *
from .tag import *
from .tag_assignment import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_contabo.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_contabo.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "contabo",
  "mod": "index/firewall",
  "fqn": "pulumi_contabo",
  "classes": {
   "contabo:index/firewall:Firewall": "Firewall"
  }
 },
 {
  "pkg": "contabo",
  "mod": "index/image",
  "fqn": "pulumi_contabo",
  "classes": {
   "contabo:index/image:Image": "Image"
  }
 },
 {
  "pkg": "contabo",
  "mod": "index/instance",
  "fqn": "pulumi_contabo",
  "classes": {
   "contabo:index/instance:Instance": "Instance"
  }
 },
 {
  "pkg": "contabo",
  "mod": "index/instanceSnapshot",
  "fqn": "pulumi_contabo",
  "classes": {
   "contabo:index/instanceSnapshot:InstanceSnapshot": "InstanceSnapshot"
  }
 },
 {
  "pkg": "contabo",
  "mod": "index/objectStorage",
  "fqn": "pulumi_contabo",
  "classes": {
   "contabo:index/objectStorage:ObjectStorage": "ObjectStorage"
  }
 },
 {
  "pkg": "contabo",
  "mod": "index/objectStorageBucket",
  "fqn": "pulumi_contabo",
  "classes": {
   "contabo:index/objectStorageBucket:ObjectStorageBucket": "ObjectStorageBucket"
  }
 },
 {
  "pkg": "contabo",
  "mod": "index/privateNetwork",
  "fqn": "pulumi_contabo",
  "classes": {
   "contabo:index/privateNetwork:PrivateNetwork": "PrivateNetwork"
  }
 },
 {
  "pkg": "contabo",
  "mod": "index/secret",
  "fqn": "pulumi_contabo",
  "classes": {
   "contabo:index/secret:Secret": "Secret"
  }
 },
 {
  "pkg": "contabo",
  "mod": "index/tag",
  "fqn": "pulumi_contabo",
  "classes": {
   "contabo:index/tag:Tag": "Tag"
  }
 },
 {
  "pkg": "contabo",
  "mod": "index/tagAssignment",
  "fqn": "pulumi_contabo",
  "classes": {
   "contabo:index/tagAssignment:TagAssignment": "TagAssignment"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "contabo",
  "token": "pulumi:providers:contabo",
  "fqn": "pulumi_contabo",
  "class": "Provider"
 }
]
"""
)
