# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'FirewallInstancesStatusArgs',
    'FirewallInstancesStatusArgsDict',
    'FirewallRuleArgs',
    'FirewallRuleArgsDict',
    'FirewallRuleInboundArgs',
    'FirewallRuleInboundArgsDict',
    'FirewallRuleInboundSrcCidrArgs',
    'FirewallRuleInboundSrcCidrArgsDict',
    'InstanceAddOnArgs',
    'InstanceAddOnArgsDict',
    'InstanceAdditionalIpArgs',
    'InstanceAdditionalIpArgsDict',
    'InstanceAdditionalIpV4Args',
    'InstanceAdditionalIpV4ArgsDict',
    'InstanceIpConfigArgs',
    'InstanceIpConfigArgsDict',
    'InstanceIpConfigV4Args',
    'InstanceIpConfigV4ArgsDict',
    'InstanceIpConfigV6Args',
    'InstanceIpConfigV6ArgsDict',
    'ObjectStorageAutoScalingArgs',
    'ObjectStorageAutoScalingArgsDict',
    'PrivateNetworkInstanceArgs',
    'PrivateNetworkInstanceArgsDict',
    'PrivateNetworkInstancePrivateIpConfigArgs',
    'PrivateNetworkInstancePrivateIpConfigArgsDict',
    'PrivateNetworkInstancePrivateIpConfigV4Args',
    'PrivateNetworkInstancePrivateIpConfigV4ArgsDict',
    'GetFirewallInstancesStatusArgs',
    'GetFirewallInstancesStatusArgsDict',
    'GetFirewallRuleArgs',
    'GetFirewallRuleArgsDict',
    'GetFirewallRuleInboundArgs',
    'GetFirewallRuleInboundArgsDict',
    'GetFirewallRuleInboundSrcCidrArgs',
    'GetFirewallRuleInboundSrcCidrArgsDict',
    'GetInstanceAddOnArgs',
    'GetInstanceAddOnArgsDict',
    'GetObjectStorageAutoScalingArgs',
    'GetObjectStorageAutoScalingArgsDict',
]

class FirewallInstancesStatusArgsDict(TypedDict):
    error_message: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    Status of the instance.
    """
    instance_id: NotRequired[pulumi.Input[Optional[_builtins.int]]]
    """
    The instance
    """
    status: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    Status of the instance.
    """

@pulumi.input_type
class FirewallInstancesStatusArgs:
    def __init__(__self__, *,
                 error_message: pulumi.Input[Optional[_builtins.str]] = None,
                 instance_id: pulumi.Input[Optional[_builtins.int]] = None,
                 status: pulumi.Input[Optional[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] error_message: Status of the instance.
        :param pulumi.Input[_builtins.int] instance_id: The instance
        :param pulumi.Input[_builtins.str] status: Status of the instance.
        """
        if error_message is not None:
            pulumi.set(__self__, "error_message", error_message)
        if instance_id is not None:
            pulumi.set(__self__, "instance_id", instance_id)
        if status is not None:
            pulumi.set(__self__, "status", status)

    @_builtins.property
    @pulumi.getter(name="errorMessage")
    def error_message(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Status of the instance.
        """
        return pulumi.get(self, "error_message")

    @error_message.setter
    def error_message(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "error_message", value)

    @_builtins.property
    @pulumi.getter(name="instanceId")
    def instance_id(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        The instance
        """
        return pulumi.get(self, "instance_id")

    @instance_id.setter
    def instance_id(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "instance_id", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Status of the instance.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "status", value)


class FirewallRuleArgsDict(TypedDict):
    inbounds: NotRequired[pulumi.Input[Optional[Sequence[pulumi.Input['FirewallRuleInboundArgsDict']]]]]
    """
    Inbound rules for this Firewall
    """

@pulumi.input_type
class FirewallRuleArgs:
    def __init__(__self__, *,
                 inbounds: pulumi.Input[Optional[Sequence[pulumi.Input['FirewallRuleInboundArgs']]]] = None):
        """
        :param pulumi.Input[Sequence[pulumi.Input['FirewallRuleInboundArgs']]] inbounds: Inbound rules for this Firewall
        """
        if inbounds is not None:
            pulumi.set(__self__, "inbounds", inbounds)

    @_builtins.property
    @pulumi.getter
    def inbounds(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['FirewallRuleInboundArgs']]]]:
        """
        Inbound rules for this Firewall
        """
        return pulumi.get(self, "inbounds")

    @inbounds.setter
    def inbounds(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['FirewallRuleInboundArgs']]]]):
        pulumi.set(self, "inbounds", value)


class FirewallRuleInboundArgsDict(TypedDict):
    action: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    Action of the rule, currently there is just `accept`.
    """
    dest_ports: NotRequired[pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]]
    protocol: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    Define the protocol for the rule. Allowed protocols are `tcp`, `udp` and `icmp`.
    """
    src_cidrs: NotRequired[pulumi.Input[Optional[Sequence[pulumi.Input['FirewallRuleInboundSrcCidrArgsDict']]]]]
    status: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    Status of the rule. It can be `active`, or `inactive`.
    """

@pulumi.input_type
class FirewallRuleInboundArgs:
    def __init__(__self__, *,
                 action: pulumi.Input[Optional[_builtins.str]] = None,
                 dest_ports: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 protocol: pulumi.Input[Optional[_builtins.str]] = None,
                 src_cidrs: pulumi.Input[Optional[Sequence[pulumi.Input['FirewallRuleInboundSrcCidrArgs']]]] = None,
                 status: pulumi.Input[Optional[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] action: Action of the rule, currently there is just `accept`.
        :param pulumi.Input[_builtins.str] protocol: Define the protocol for the rule. Allowed protocols are `tcp`, `udp` and `icmp`.
        :param pulumi.Input[_builtins.str] status: Status of the rule. It can be `active`, or `inactive`.
        """
        if action is not None:
            pulumi.set(__self__, "action", action)
        if dest_ports is not None:
            pulumi.set(__self__, "dest_ports", dest_ports)
        if protocol is not None:
            pulumi.set(__self__, "protocol", protocol)
        if src_cidrs is not None:
            pulumi.set(__self__, "src_cidrs", src_cidrs)
        if status is not None:
            pulumi.set(__self__, "status", status)

    @_builtins.property
    @pulumi.getter
    def action(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Action of the rule, currently there is just `accept`.
        """
        return pulumi.get(self, "action")

    @action.setter
    def action(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "action", value)

    @_builtins.property
    @pulumi.getter(name="destPorts")
    def dest_ports(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "dest_ports")

    @dest_ports.setter
    def dest_ports(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "dest_ports", value)

    @_builtins.property
    @pulumi.getter
    def protocol(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Define the protocol for the rule. Allowed protocols are `tcp`, `udp` and `icmp`.
        """
        return pulumi.get(self, "protocol")

    @protocol.setter
    def protocol(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "protocol", value)

    @_builtins.property
    @pulumi.getter(name="srcCidrs")
    def src_cidrs(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['FirewallRuleInboundSrcCidrArgs']]]]:
        return pulumi.get(self, "src_cidrs")

    @src_cidrs.setter
    def src_cidrs(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['FirewallRuleInboundSrcCidrArgs']]]]):
        pulumi.set(self, "src_cidrs", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Status of the rule. It can be `active`, or `inactive`.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "status", value)


class FirewallRuleInboundSrcCidrArgsDict(TypedDict):
    ipv4s: NotRequired[pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]]
    """
    Provide allowed IPv4 addresses as string array for this rule
    """
    ipv6s: NotRequired[pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]]
    """
    Provide allowed IPv6 addresses as string array for this rule
    """

@pulumi.input_type
class FirewallRuleInboundSrcCidrArgs:
    def __init__(__self__, *,
                 ipv4s: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 ipv6s: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] ipv4s: Provide allowed IPv4 addresses as string array for this rule
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] ipv6s: Provide allowed IPv6 addresses as string array for this rule
        """
        if ipv4s is not None:
            pulumi.set(__self__, "ipv4s", ipv4s)
        if ipv6s is not None:
            pulumi.set(__self__, "ipv6s", ipv6s)

    @_builtins.property
    @pulumi.getter
    def ipv4s(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Provide allowed IPv4 addresses as string array for this rule
        """
        return pulumi.get(self, "ipv4s")

    @ipv4s.setter
    def ipv4s(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "ipv4s", value)

    @_builtins.property
    @pulumi.getter
    def ipv6s(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Provide allowed IPv6 addresses as string array for this rule
        """
        return pulumi.get(self, "ipv6s")

    @ipv6s.setter
    def ipv6s(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "ipv6s", value)


class InstanceAddOnArgsDict(TypedDict):
    id: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    Id of the Addon. Please refer to list [here](https://contabo.com/en/product-list/?show_ids=true).
    """
    quantity: NotRequired[pulumi.Input[Optional[_builtins.int]]]
    """
    The number of Addons you wish to aquire.
    """

@pulumi.input_type
class InstanceAddOnArgs:
    def __init__(__self__, *,
                 id: pulumi.Input[Optional[_builtins.str]] = None,
                 quantity: pulumi.Input[Optional[_builtins.int]] = None):
        """
        :param pulumi.Input[_builtins.str] id: Id of the Addon. Please refer to list [here](https://contabo.com/en/product-list/?show_ids=true).
        :param pulumi.Input[_builtins.int] quantity: The number of Addons you wish to aquire.
        """
        if id is not None:
            pulumi.set(__self__, "id", id)
        if quantity is not None:
            pulumi.set(__self__, "quantity", quantity)

    @_builtins.property
    @pulumi.getter
    def id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Id of the Addon. Please refer to list [here](https://contabo.com/en/product-list/?show_ids=true).
        """
        return pulumi.get(self, "id")

    @id.setter
    def id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "id", value)

    @_builtins.property
    @pulumi.getter
    def quantity(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        The number of Addons you wish to aquire.
        """
        return pulumi.get(self, "quantity")

    @quantity.setter
    def quantity(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "quantity", value)


class InstanceAdditionalIpArgsDict(TypedDict):
    v4s: NotRequired[pulumi.Input[Optional[Sequence[pulumi.Input['InstanceAdditionalIpV4ArgsDict']]]]]

@pulumi.input_type
class InstanceAdditionalIpArgs:
    def __init__(__self__, *,
                 v4s: pulumi.Input[Optional[Sequence[pulumi.Input['InstanceAdditionalIpV4Args']]]] = None):
        if v4s is not None:
            pulumi.set(__self__, "v4s", v4s)

    @_builtins.property
    @pulumi.getter
    def v4s(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['InstanceAdditionalIpV4Args']]]]:
        return pulumi.get(self, "v4s")

    @v4s.setter
    def v4s(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['InstanceAdditionalIpV4Args']]]]):
        pulumi.set(self, "v4s", value)


class InstanceAdditionalIpV4ArgsDict(TypedDict):
    gateway: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    Gateway
    """
    ip: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    IP Address
    """
    netmask_cidr: NotRequired[pulumi.Input[Optional[_builtins.int]]]
    """
    Netmask CIDR
    """

@pulumi.input_type
class InstanceAdditionalIpV4Args:
    def __init__(__self__, *,
                 gateway: pulumi.Input[Optional[_builtins.str]] = None,
                 ip: pulumi.Input[Optional[_builtins.str]] = None,
                 netmask_cidr: pulumi.Input[Optional[_builtins.int]] = None):
        """
        :param pulumi.Input[_builtins.str] gateway: Gateway
        :param pulumi.Input[_builtins.str] ip: IP Address
        :param pulumi.Input[_builtins.int] netmask_cidr: Netmask CIDR
        """
        if gateway is not None:
            pulumi.set(__self__, "gateway", gateway)
        if ip is not None:
            pulumi.set(__self__, "ip", ip)
        if netmask_cidr is not None:
            pulumi.set(__self__, "netmask_cidr", netmask_cidr)

    @_builtins.property
    @pulumi.getter
    def gateway(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Gateway
        """
        return pulumi.get(self, "gateway")

    @gateway.setter
    def gateway(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "gateway", value)

    @_builtins.property
    @pulumi.getter
    def ip(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        IP Address
        """
        return pulumi.get(self, "ip")

    @ip.setter
    def ip(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ip", value)

    @_builtins.property
    @pulumi.getter(name="netmaskCidr")
    def netmask_cidr(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Netmask CIDR
        """
        return pulumi.get(self, "netmask_cidr")

    @netmask_cidr.setter
    def netmask_cidr(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "netmask_cidr", value)


class InstanceIpConfigArgsDict(TypedDict):
    v4s: NotRequired[pulumi.Input[Optional[Sequence[pulumi.Input['InstanceIpConfigV4ArgsDict']]]]]
    v6s: NotRequired[pulumi.Input[Optional[Sequence[pulumi.Input['InstanceIpConfigV6ArgsDict']]]]]

@pulumi.input_type
class InstanceIpConfigArgs:
    def __init__(__self__, *,
                 v4s: pulumi.Input[Optional[Sequence[pulumi.Input['InstanceIpConfigV4Args']]]] = None,
                 v6s: pulumi.Input[Optional[Sequence[pulumi.Input['InstanceIpConfigV6Args']]]] = None):
        if v4s is not None:
            pulumi.set(__self__, "v4s", v4s)
        if v6s is not None:
            pulumi.set(__self__, "v6s", v6s)

    @_builtins.property
    @pulumi.getter
    def v4s(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['InstanceIpConfigV4Args']]]]:
        return pulumi.get(self, "v4s")

    @v4s.setter
    def v4s(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['InstanceIpConfigV4Args']]]]):
        pulumi.set(self, "v4s", value)

    @_builtins.property
    @pulumi.getter
    def v6s(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['InstanceIpConfigV6Args']]]]:
        return pulumi.get(self, "v6s")

    @v6s.setter
    def v6s(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['InstanceIpConfigV6Args']]]]):
        pulumi.set(self, "v6s", value)


class InstanceIpConfigV4ArgsDict(TypedDict):
    gateway: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    Gateway
    """
    ip: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    IP Address
    """
    netmask_cidr: NotRequired[pulumi.Input[Optional[_builtins.int]]]
    """
    Netmask CIDR
    """

@pulumi.input_type
class InstanceIpConfigV4Args:
    def __init__(__self__, *,
                 gateway: pulumi.Input[Optional[_builtins.str]] = None,
                 ip: pulumi.Input[Optional[_builtins.str]] = None,
                 netmask_cidr: pulumi.Input[Optional[_builtins.int]] = None):
        """
        :param pulumi.Input[_builtins.str] gateway: Gateway
        :param pulumi.Input[_builtins.str] ip: IP Address
        :param pulumi.Input[_builtins.int] netmask_cidr: Netmask CIDR
        """
        if gateway is not None:
            pulumi.set(__self__, "gateway", gateway)
        if ip is not None:
            pulumi.set(__self__, "ip", ip)
        if netmask_cidr is not None:
            pulumi.set(__self__, "netmask_cidr", netmask_cidr)

    @_builtins.property
    @pulumi.getter
    def gateway(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Gateway
        """
        return pulumi.get(self, "gateway")

    @gateway.setter
    def gateway(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "gateway", value)

    @_builtins.property
    @pulumi.getter
    def ip(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        IP Address
        """
        return pulumi.get(self, "ip")

    @ip.setter
    def ip(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ip", value)

    @_builtins.property
    @pulumi.getter(name="netmaskCidr")
    def netmask_cidr(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Netmask CIDR
        """
        return pulumi.get(self, "netmask_cidr")

    @netmask_cidr.setter
    def netmask_cidr(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "netmask_cidr", value)


class InstanceIpConfigV6ArgsDict(TypedDict):
    gateway: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    Gateway
    """
    ip: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    IP Address
    """
    netmask_cidr: NotRequired[pulumi.Input[Optional[_builtins.int]]]
    """
    Netmask CIDR
    """

@pulumi.input_type
class InstanceIpConfigV6Args:
    def __init__(__self__, *,
                 gateway: pulumi.Input[Optional[_builtins.str]] = None,
                 ip: pulumi.Input[Optional[_builtins.str]] = None,
                 netmask_cidr: pulumi.Input[Optional[_builtins.int]] = None):
        """
        :param pulumi.Input[_builtins.str] gateway: Gateway
        :param pulumi.Input[_builtins.str] ip: IP Address
        :param pulumi.Input[_builtins.int] netmask_cidr: Netmask CIDR
        """
        if gateway is not None:
            pulumi.set(__self__, "gateway", gateway)
        if ip is not None:
            pulumi.set(__self__, "ip", ip)
        if netmask_cidr is not None:
            pulumi.set(__self__, "netmask_cidr", netmask_cidr)

    @_builtins.property
    @pulumi.getter
    def gateway(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Gateway
        """
        return pulumi.get(self, "gateway")

    @gateway.setter
    def gateway(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "gateway", value)

    @_builtins.property
    @pulumi.getter
    def ip(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        IP Address
        """
        return pulumi.get(self, "ip")

    @ip.setter
    def ip(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ip", value)

    @_builtins.property
    @pulumi.getter(name="netmaskCidr")
    def netmask_cidr(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Netmask CIDR
        """
        return pulumi.get(self, "netmask_cidr")

    @netmask_cidr.setter
    def netmask_cidr(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "netmask_cidr", value)


class ObjectStorageAutoScalingArgsDict(TypedDict):
    error_message: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    If the autoscaling is in an error state (see status property), the error message can be seen in this field.
    """
    size_limit_tb: NotRequired[pulumi.Input[Optional[_builtins.float]]]
    """
    Autoscaling size limit for the current object storage.
    """
    state: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    Status of this object storage.  It can be set to `enabled`, `disabled` or `error`.
    """

@pulumi.input_type
class ObjectStorageAutoScalingArgs:
    def __init__(__self__, *,
                 error_message: pulumi.Input[Optional[_builtins.str]] = None,
                 size_limit_tb: pulumi.Input[Optional[_builtins.float]] = None,
                 state: pulumi.Input[Optional[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] error_message: If the autoscaling is in an error state (see status property), the error message can be seen in this field.
        :param pulumi.Input[_builtins.float] size_limit_tb: Autoscaling size limit for the current object storage.
        :param pulumi.Input[_builtins.str] state: Status of this object storage.  It can be set to `enabled`, `disabled` or `error`.
        """
        if error_message is not None:
            pulumi.set(__self__, "error_message", error_message)
        if size_limit_tb is not None:
            pulumi.set(__self__, "size_limit_tb", size_limit_tb)
        if state is not None:
            pulumi.set(__self__, "state", state)

    @_builtins.property
    @pulumi.getter(name="errorMessage")
    def error_message(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        If the autoscaling is in an error state (see status property), the error message can be seen in this field.
        """
        return pulumi.get(self, "error_message")

    @error_message.setter
    def error_message(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "error_message", value)

    @_builtins.property
    @pulumi.getter(name="sizeLimitTb")
    def size_limit_tb(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Autoscaling size limit for the current object storage.
        """
        return pulumi.get(self, "size_limit_tb")

    @size_limit_tb.setter
    def size_limit_tb(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "size_limit_tb", value)

    @_builtins.property
    @pulumi.getter
    def state(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Status of this object storage.  It can be set to `enabled`, `disabled` or `error`.
        """
        return pulumi.get(self, "state")

    @state.setter
    def state(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "state", value)


class PrivateNetworkInstanceArgsDict(TypedDict):
    display_name: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    The instance name chosen by the customer that will be shown in the customer panel.
    """
    error_message: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    If the instance is in an error state (see status property), the error message can be seen in this field.
    """
    instance_id: NotRequired[pulumi.Input[Optional[_builtins.int]]]
    """
    The identifier of the compute instance.
    """
    name: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    Name of the compute instance.
    """
    private_ip_configs: NotRequired[pulumi.Input[Optional[Sequence[pulumi.Input['PrivateNetworkInstancePrivateIpConfigArgsDict']]]]]
    """
    List of all private IP addresses of the compute instance.
    """
    status: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    State of the instance in the Private Network. The status can be one of 'ok', 'restart', 'reinstall', 'reinstallation failed', 'installing'
    """

@pulumi.input_type
class PrivateNetworkInstanceArgs:
    def __init__(__self__, *,
                 display_name: pulumi.Input[Optional[_builtins.str]] = None,
                 error_message: pulumi.Input[Optional[_builtins.str]] = None,
                 instance_id: pulumi.Input[Optional[_builtins.int]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 private_ip_configs: pulumi.Input[Optional[Sequence[pulumi.Input['PrivateNetworkInstancePrivateIpConfigArgs']]]] = None,
                 status: pulumi.Input[Optional[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] display_name: The instance name chosen by the customer that will be shown in the customer panel.
        :param pulumi.Input[_builtins.str] error_message: If the instance is in an error state (see status property), the error message can be seen in this field.
        :param pulumi.Input[_builtins.int] instance_id: The identifier of the compute instance.
        :param pulumi.Input[_builtins.str] name: Name of the compute instance.
        :param pulumi.Input[Sequence[pulumi.Input['PrivateNetworkInstancePrivateIpConfigArgs']]] private_ip_configs: List of all private IP addresses of the compute instance.
        :param pulumi.Input[_builtins.str] status: State of the instance in the Private Network. The status can be one of 'ok', 'restart', 'reinstall', 'reinstallation failed', 'installing'
        """
        if display_name is not None:
            pulumi.set(__self__, "display_name", display_name)
        if error_message is not None:
            pulumi.set(__self__, "error_message", error_message)
        if instance_id is not None:
            pulumi.set(__self__, "instance_id", instance_id)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if private_ip_configs is not None:
            pulumi.set(__self__, "private_ip_configs", private_ip_configs)
        if status is not None:
            pulumi.set(__self__, "status", status)

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The instance name chosen by the customer that will be shown in the customer panel.
        """
        return pulumi.get(self, "display_name")

    @display_name.setter
    def display_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "display_name", value)

    @_builtins.property
    @pulumi.getter(name="errorMessage")
    def error_message(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        If the instance is in an error state (see status property), the error message can be seen in this field.
        """
        return pulumi.get(self, "error_message")

    @error_message.setter
    def error_message(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "error_message", value)

    @_builtins.property
    @pulumi.getter(name="instanceId")
    def instance_id(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        The identifier of the compute instance.
        """
        return pulumi.get(self, "instance_id")

    @instance_id.setter
    def instance_id(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "instance_id", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Name of the compute instance.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="privateIpConfigs")
    def private_ip_configs(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['PrivateNetworkInstancePrivateIpConfigArgs']]]]:
        """
        List of all private IP addresses of the compute instance.
        """
        return pulumi.get(self, "private_ip_configs")

    @private_ip_configs.setter
    def private_ip_configs(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['PrivateNetworkInstancePrivateIpConfigArgs']]]]):
        pulumi.set(self, "private_ip_configs", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        State of the instance in the Private Network. The status can be one of 'ok', 'restart', 'reinstall', 'reinstallation failed', 'installing'
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "status", value)


class PrivateNetworkInstancePrivateIpConfigArgsDict(TypedDict):
    v4s: NotRequired[pulumi.Input[Optional[Sequence[pulumi.Input['PrivateNetworkInstancePrivateIpConfigV4ArgsDict']]]]]

@pulumi.input_type
class PrivateNetworkInstancePrivateIpConfigArgs:
    def __init__(__self__, *,
                 v4s: pulumi.Input[Optional[Sequence[pulumi.Input['PrivateNetworkInstancePrivateIpConfigV4Args']]]] = None):
        if v4s is not None:
            pulumi.set(__self__, "v4s", v4s)

    @_builtins.property
    @pulumi.getter
    def v4s(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['PrivateNetworkInstancePrivateIpConfigV4Args']]]]:
        return pulumi.get(self, "v4s")

    @v4s.setter
    def v4s(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['PrivateNetworkInstancePrivateIpConfigV4Args']]]]):
        pulumi.set(self, "v4s", value)


class PrivateNetworkInstancePrivateIpConfigV4ArgsDict(TypedDict):
    gateway: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    Gateway
    """
    ip: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    IP Address
    """
    netmask_cidr: NotRequired[pulumi.Input[Optional[_builtins.int]]]
    """
    Netmask CIDR
    """

@pulumi.input_type
class PrivateNetworkInstancePrivateIpConfigV4Args:
    def __init__(__self__, *,
                 gateway: pulumi.Input[Optional[_builtins.str]] = None,
                 ip: pulumi.Input[Optional[_builtins.str]] = None,
                 netmask_cidr: pulumi.Input[Optional[_builtins.int]] = None):
        """
        :param pulumi.Input[_builtins.str] gateway: Gateway
        :param pulumi.Input[_builtins.str] ip: IP Address
        :param pulumi.Input[_builtins.int] netmask_cidr: Netmask CIDR
        """
        if gateway is not None:
            pulumi.set(__self__, "gateway", gateway)
        if ip is not None:
            pulumi.set(__self__, "ip", ip)
        if netmask_cidr is not None:
            pulumi.set(__self__, "netmask_cidr", netmask_cidr)

    @_builtins.property
    @pulumi.getter
    def gateway(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Gateway
        """
        return pulumi.get(self, "gateway")

    @gateway.setter
    def gateway(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "gateway", value)

    @_builtins.property
    @pulumi.getter
    def ip(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        IP Address
        """
        return pulumi.get(self, "ip")

    @ip.setter
    def ip(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ip", value)

    @_builtins.property
    @pulumi.getter(name="netmaskCidr")
    def netmask_cidr(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Netmask CIDR
        """
        return pulumi.get(self, "netmask_cidr")

    @netmask_cidr.setter
    def netmask_cidr(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "netmask_cidr", value)


class GetFirewallInstancesStatusArgsDict(TypedDict):
    error_message: _builtins.str
    """
    Status of the instance.
    """
    instance_id: _builtins.int
    """
    The instance
    """
    status: _builtins.str
    """
    Status of the instance.
    """

@pulumi.input_type
class GetFirewallInstancesStatusArgs:
    def __init__(__self__, *,
                 error_message: _builtins.str,
                 instance_id: _builtins.int,
                 status: _builtins.str):
        """
        :param _builtins.str error_message: Status of the instance.
        :param _builtins.int instance_id: The instance
        :param _builtins.str status: Status of the instance.
        """
        pulumi.set(__self__, "error_message", error_message)
        pulumi.set(__self__, "instance_id", instance_id)
        pulumi.set(__self__, "status", status)

    @_builtins.property
    @pulumi.getter(name="errorMessage")
    def error_message(self) -> _builtins.str:
        """
        Status of the instance.
        """
        return pulumi.get(self, "error_message")

    @error_message.setter
    def error_message(self, value: _builtins.str):
        pulumi.set(self, "error_message", value)

    @_builtins.property
    @pulumi.getter(name="instanceId")
    def instance_id(self) -> _builtins.int:
        """
        The instance
        """
        return pulumi.get(self, "instance_id")

    @instance_id.setter
    def instance_id(self, value: _builtins.int):
        pulumi.set(self, "instance_id", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> _builtins.str:
        """
        Status of the instance.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: _builtins.str):
        pulumi.set(self, "status", value)


class GetFirewallRuleArgsDict(TypedDict):
    inbounds: Sequence['GetFirewallRuleInboundArgsDict']
    """
    Inbound rules for this Firewall
    """

@pulumi.input_type
class GetFirewallRuleArgs:
    def __init__(__self__, *,
                 inbounds: Sequence['GetFirewallRuleInboundArgs']):
        """
        :param Sequence['GetFirewallRuleInboundArgs'] inbounds: Inbound rules for this Firewall
        """
        pulumi.set(__self__, "inbounds", inbounds)

    @_builtins.property
    @pulumi.getter
    def inbounds(self) -> Sequence['GetFirewallRuleInboundArgs']:
        """
        Inbound rules for this Firewall
        """
        return pulumi.get(self, "inbounds")

    @inbounds.setter
    def inbounds(self, value: Sequence['GetFirewallRuleInboundArgs']):
        pulumi.set(self, "inbounds", value)


class GetFirewallRuleInboundArgsDict(TypedDict):
    action: _builtins.str
    """
    Action of the rule, currently there is just `accept`.
    """
    protocol: _builtins.str
    """
    Define the protocol for the rule. Allowed protocols are `tcp`, `udp` and `icmp`.
    """
    dest_ports: NotRequired[Sequence[_builtins.str]]
    src_cidrs: NotRequired[Sequence['GetFirewallRuleInboundSrcCidrArgsDict']]
    status: NotRequired[_builtins.str]
    """
    Status of the rule. It can be `active`, or `inactive`.
    """

@pulumi.input_type
class GetFirewallRuleInboundArgs:
    def __init__(__self__, *,
                 action: _builtins.str,
                 protocol: _builtins.str,
                 dest_ports: Optional[Sequence[_builtins.str]] = None,
                 src_cidrs: Optional[Sequence['GetFirewallRuleInboundSrcCidrArgs']] = None,
                 status: Optional[_builtins.str] = None):
        """
        :param _builtins.str action: Action of the rule, currently there is just `accept`.
        :param _builtins.str protocol: Define the protocol for the rule. Allowed protocols are `tcp`, `udp` and `icmp`.
        :param _builtins.str status: Status of the rule. It can be `active`, or `inactive`.
        """
        pulumi.set(__self__, "action", action)
        pulumi.set(__self__, "protocol", protocol)
        if dest_ports is not None:
            pulumi.set(__self__, "dest_ports", dest_ports)
        if src_cidrs is not None:
            pulumi.set(__self__, "src_cidrs", src_cidrs)
        if status is not None:
            pulumi.set(__self__, "status", status)

    @_builtins.property
    @pulumi.getter
    def action(self) -> _builtins.str:
        """
        Action of the rule, currently there is just `accept`.
        """
        return pulumi.get(self, "action")

    @action.setter
    def action(self, value: _builtins.str):
        pulumi.set(self, "action", value)

    @_builtins.property
    @pulumi.getter
    def protocol(self) -> _builtins.str:
        """
        Define the protocol for the rule. Allowed protocols are `tcp`, `udp` and `icmp`.
        """
        return pulumi.get(self, "protocol")

    @protocol.setter
    def protocol(self, value: _builtins.str):
        pulumi.set(self, "protocol", value)

    @_builtins.property
    @pulumi.getter(name="destPorts")
    def dest_ports(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "dest_ports")

    @dest_ports.setter
    def dest_ports(self, value: Optional[Sequence[_builtins.str]]):
        pulumi.set(self, "dest_ports", value)

    @_builtins.property
    @pulumi.getter(name="srcCidrs")
    def src_cidrs(self) -> Optional[Sequence['GetFirewallRuleInboundSrcCidrArgs']]:
        return pulumi.get(self, "src_cidrs")

    @src_cidrs.setter
    def src_cidrs(self, value: Optional[Sequence['GetFirewallRuleInboundSrcCidrArgs']]):
        pulumi.set(self, "src_cidrs", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> Optional[_builtins.str]:
        """
        Status of the rule. It can be `active`, or `inactive`.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: Optional[_builtins.str]):
        pulumi.set(self, "status", value)


class GetFirewallRuleInboundSrcCidrArgsDict(TypedDict):
    ipv4s: NotRequired[Sequence[_builtins.str]]
    """
    Provide allowed IPv4 addresses as string array for this rule
    """
    ipv6s: NotRequired[Sequence[_builtins.str]]
    """
    Provide allowed IPv6 addresses as string array for this rule
    """

@pulumi.input_type
class GetFirewallRuleInboundSrcCidrArgs:
    def __init__(__self__, *,
                 ipv4s: Optional[Sequence[_builtins.str]] = None,
                 ipv6s: Optional[Sequence[_builtins.str]] = None):
        """
        :param Sequence[_builtins.str] ipv4s: Provide allowed IPv4 addresses as string array for this rule
        :param Sequence[_builtins.str] ipv6s: Provide allowed IPv6 addresses as string array for this rule
        """
        if ipv4s is not None:
            pulumi.set(__self__, "ipv4s", ipv4s)
        if ipv6s is not None:
            pulumi.set(__self__, "ipv6s", ipv6s)

    @_builtins.property
    @pulumi.getter
    def ipv4s(self) -> Optional[Sequence[_builtins.str]]:
        """
        Provide allowed IPv4 addresses as string array for this rule
        """
        return pulumi.get(self, "ipv4s")

    @ipv4s.setter
    def ipv4s(self, value: Optional[Sequence[_builtins.str]]):
        pulumi.set(self, "ipv4s", value)

    @_builtins.property
    @pulumi.getter
    def ipv6s(self) -> Optional[Sequence[_builtins.str]]:
        """
        Provide allowed IPv6 addresses as string array for this rule
        """
        return pulumi.get(self, "ipv6s")

    @ipv6s.setter
    def ipv6s(self, value: Optional[Sequence[_builtins.str]]):
        pulumi.set(self, "ipv6s", value)


class GetInstanceAddOnArgsDict(TypedDict):
    id: _builtins.str
    """
    Id of the Addon. Please refer to list [here](https://contabo.com/en/product-list/?show_ids=true).
    """
    quantity: _builtins.int
    """
    The number of Addons you wish to aquire.
    """

@pulumi.input_type
class GetInstanceAddOnArgs:
    def __init__(__self__, *,
                 id: _builtins.str,
                 quantity: _builtins.int):
        """
        :param _builtins.str id: Id of the Addon. Please refer to list [here](https://contabo.com/en/product-list/?show_ids=true).
        :param _builtins.int quantity: The number of Addons you wish to aquire.
        """
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "quantity", quantity)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        Id of the Addon. Please refer to list [here](https://contabo.com/en/product-list/?show_ids=true).
        """
        return pulumi.get(self, "id")

    @id.setter
    def id(self, value: _builtins.str):
        pulumi.set(self, "id", value)

    @_builtins.property
    @pulumi.getter
    def quantity(self) -> _builtins.int:
        """
        The number of Addons you wish to aquire.
        """
        return pulumi.get(self, "quantity")

    @quantity.setter
    def quantity(self, value: _builtins.int):
        pulumi.set(self, "quantity", value)


class GetObjectStorageAutoScalingArgsDict(TypedDict):
    error_message: _builtins.str
    """
    If the autoscaling is in an error state (see status property), the error message can be seen in this field.
    """
    size_limit_tb: _builtins.float
    """
    Autoscaling size limit for the current object storage.
    """
    state: _builtins.str
    """
    Status of this object storage.  It can be set to `enabled`, `disabled` or `error`.
    """

@pulumi.input_type
class GetObjectStorageAutoScalingArgs:
    def __init__(__self__, *,
                 error_message: _builtins.str,
                 size_limit_tb: _builtins.float,
                 state: _builtins.str):
        """
        :param _builtins.str error_message: If the autoscaling is in an error state (see status property), the error message can be seen in this field.
        :param _builtins.float size_limit_tb: Autoscaling size limit for the current object storage.
        :param _builtins.str state: Status of this object storage.  It can be set to `enabled`, `disabled` or `error`.
        """
        pulumi.set(__self__, "error_message", error_message)
        pulumi.set(__self__, "size_limit_tb", size_limit_tb)
        pulumi.set(__self__, "state", state)

    @_builtins.property
    @pulumi.getter(name="errorMessage")
    def error_message(self) -> _builtins.str:
        """
        If the autoscaling is in an error state (see status property), the error message can be seen in this field.
        """
        return pulumi.get(self, "error_message")

    @error_message.setter
    def error_message(self, value: _builtins.str):
        pulumi.set(self, "error_message", value)

    @_builtins.property
    @pulumi.getter(name="sizeLimitTb")
    def size_limit_tb(self) -> _builtins.float:
        """
        Autoscaling size limit for the current object storage.
        """
        return pulumi.get(self, "size_limit_tb")

    @size_limit_tb.setter
    def size_limit_tb(self, value: _builtins.float):
        pulumi.set(self, "size_limit_tb", value)

    @_builtins.property
    @pulumi.getter
    def state(self) -> _builtins.str:
        """
        Status of this object storage.  It can be set to `enabled`, `disabled` or `error`.
        """
        return pulumi.get(self, "state")

    @state.setter
    def state(self, value: _builtins.str):
        pulumi.set(self, "state", value)


