# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['FirewallArgs', 'Firewall']

@pulumi.input_type
class FirewallArgs:
    def __init__(__self__, *,
                 status: pulumi.Input[_builtins.str],
                 created_date: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 instance_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 instances_statuses: pulumi.Input[Optional[Sequence[pulumi.Input['FirewallInstancesStatusArgs']]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 rules: pulumi.Input[Optional[Sequence[pulumi.Input['FirewallRuleArgs']]]] = None):
        """
        The set of arguments for constructing a Firewall resource.

        :param pulumi.Input[_builtins.str] status: Status of the Firewall. It can be `active`, or `inactive`.
        :param pulumi.Input[_builtins.str] created_date: The creation date of the Firewall.
        :param pulumi.Input[_builtins.str] description: The description of the Firewall. There is a limit of 255 characters per Firewall.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.int]]] instance_ids: Add the instace Ids to the firewall here. If you do not add any instance Ids an empty firewall will be created.
        :param pulumi.Input[Sequence[pulumi.Input['FirewallInstancesStatusArgs']]] instances_statuses: The status of every instance in the firewall
        :param pulumi.Input[_builtins.str] name: The name of the Firewall. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Firewall name.
        """
        pulumi.set(__self__, "status", status)
        if created_date is not None:
            pulumi.set(__self__, "created_date", created_date)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if instance_ids is not None:
            pulumi.set(__self__, "instance_ids", instance_ids)
        if instances_statuses is not None:
            pulumi.set(__self__, "instances_statuses", instances_statuses)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if rules is not None:
            pulumi.set(__self__, "rules", rules)

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Input[_builtins.str]:
        """
        Status of the Firewall. It can be `active`, or `inactive`.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter(name="createdDate")
    def created_date(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The creation date of the Firewall.
        """
        return pulumi.get(self, "created_date")

    @created_date.setter
    def created_date(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "created_date", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The description of the Firewall. There is a limit of 255 characters per Firewall.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="instanceIds")
    def instance_ids(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.int]]]]:
        """
        Add the instace Ids to the firewall here. If you do not add any instance Ids an empty firewall will be created.
        """
        return pulumi.get(self, "instance_ids")

    @instance_ids.setter
    def instance_ids(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.int]]]]):
        pulumi.set(self, "instance_ids", value)

    @_builtins.property
    @pulumi.getter(name="instancesStatuses")
    def instances_statuses(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['FirewallInstancesStatusArgs']]]]:
        """
        The status of every instance in the firewall
        """
        return pulumi.get(self, "instances_statuses")

    @instances_statuses.setter
    def instances_statuses(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['FirewallInstancesStatusArgs']]]]):
        pulumi.set(self, "instances_statuses", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the Firewall. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Firewall name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def rules(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['FirewallRuleArgs']]]]:
        return pulumi.get(self, "rules")

    @rules.setter
    def rules(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['FirewallRuleArgs']]]]):
        pulumi.set(self, "rules", value)


@pulumi.input_type
class _FirewallState:
    def __init__(__self__, *,
                 created_date: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 instance_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 instances_statuses: pulumi.Input[Optional[Sequence[pulumi.Input['FirewallInstancesStatusArgs']]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 rules: pulumi.Input[Optional[Sequence[pulumi.Input['FirewallRuleArgs']]]] = None,
                 status: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Firewall resources.

        :param pulumi.Input[_builtins.str] created_date: The creation date of the Firewall.
        :param pulumi.Input[_builtins.str] description: The description of the Firewall. There is a limit of 255 characters per Firewall.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.int]]] instance_ids: Add the instace Ids to the firewall here. If you do not add any instance Ids an empty firewall will be created.
        :param pulumi.Input[Sequence[pulumi.Input['FirewallInstancesStatusArgs']]] instances_statuses: The status of every instance in the firewall
        :param pulumi.Input[_builtins.str] name: The name of the Firewall. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Firewall name.
        :param pulumi.Input[_builtins.str] status: Status of the Firewall. It can be `active`, or `inactive`.
        """
        if created_date is not None:
            pulumi.set(__self__, "created_date", created_date)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if instance_ids is not None:
            pulumi.set(__self__, "instance_ids", instance_ids)
        if instances_statuses is not None:
            pulumi.set(__self__, "instances_statuses", instances_statuses)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if rules is not None:
            pulumi.set(__self__, "rules", rules)
        if status is not None:
            pulumi.set(__self__, "status", status)

    @_builtins.property
    @pulumi.getter(name="createdDate")
    def created_date(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The creation date of the Firewall.
        """
        return pulumi.get(self, "created_date")

    @created_date.setter
    def created_date(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "created_date", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The description of the Firewall. There is a limit of 255 characters per Firewall.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="instanceIds")
    def instance_ids(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.int]]]]:
        """
        Add the instace Ids to the firewall here. If you do not add any instance Ids an empty firewall will be created.
        """
        return pulumi.get(self, "instance_ids")

    @instance_ids.setter
    def instance_ids(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.int]]]]):
        pulumi.set(self, "instance_ids", value)

    @_builtins.property
    @pulumi.getter(name="instancesStatuses")
    def instances_statuses(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['FirewallInstancesStatusArgs']]]]:
        """
        The status of every instance in the firewall
        """
        return pulumi.get(self, "instances_statuses")

    @instances_statuses.setter
    def instances_statuses(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['FirewallInstancesStatusArgs']]]]):
        pulumi.set(self, "instances_statuses", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the Firewall. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Firewall name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def rules(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['FirewallRuleArgs']]]]:
        return pulumi.get(self, "rules")

    @rules.setter
    def rules(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['FirewallRuleArgs']]]]):
        pulumi.set(self, "rules", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Status of the Firewall. It can be `active`, or `inactive`.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "status", value)


@pulumi.type_token("contabo:index/firewall:Firewall")
class Firewall(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 created_date: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 instance_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 instances_statuses: pulumi.Input[Optional[Sequence[pulumi.Input[Union['FirewallInstancesStatusArgs', 'FirewallInstancesStatusArgsDict']]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 rules: pulumi.Input[Optional[Sequence[pulumi.Input[Union['FirewallRuleArgs', 'FirewallRuleArgsDict']]]]] = None,
                 status: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        ## Example Usage


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] created_date: The creation date of the Firewall.
        :param pulumi.Input[_builtins.str] description: The description of the Firewall. There is a limit of 255 characters per Firewall.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.int]]] instance_ids: Add the instace Ids to the firewall here. If you do not add any instance Ids an empty firewall will be created.
        :param pulumi.Input[Sequence[pulumi.Input[Union['FirewallInstancesStatusArgs', 'FirewallInstancesStatusArgsDict']]]] instances_statuses: The status of every instance in the firewall
        :param pulumi.Input[_builtins.str] name: The name of the Firewall. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Firewall name.
        :param pulumi.Input[_builtins.str] status: Status of the Firewall. It can be `active`, or `inactive`.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: FirewallArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        ## Example Usage


        :param str resource_name: The name of the resource.
        :param FirewallArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(FirewallArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 created_date: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 instance_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 instances_statuses: pulumi.Input[Optional[Sequence[pulumi.Input[Union['FirewallInstancesStatusArgs', 'FirewallInstancesStatusArgsDict']]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 rules: pulumi.Input[Optional[Sequence[pulumi.Input[Union['FirewallRuleArgs', 'FirewallRuleArgsDict']]]]] = None,
                 status: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = FirewallArgs.__new__(FirewallArgs)

            __props__.__dict__["created_date"] = created_date
            __props__.__dict__["description"] = description
            __props__.__dict__["instance_ids"] = instance_ids
            __props__.__dict__["instances_statuses"] = instances_statuses
            __props__.__dict__["name"] = name
            __props__.__dict__["rules"] = rules
            if status is None and not opts.urn:
                raise TypeError("Missing required property 'status'")
            __props__.__dict__["status"] = status
        super(Firewall, __self__).__init__(
            'contabo:index/firewall:Firewall',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            created_date: pulumi.Input[Optional[_builtins.str]] = None,
            description: pulumi.Input[Optional[_builtins.str]] = None,
            instance_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.int]]]] = None,
            instances_statuses: pulumi.Input[Optional[Sequence[pulumi.Input[Union['FirewallInstancesStatusArgs', 'FirewallInstancesStatusArgsDict']]]]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            rules: pulumi.Input[Optional[Sequence[pulumi.Input[Union['FirewallRuleArgs', 'FirewallRuleArgsDict']]]]] = None,
            status: pulumi.Input[Optional[_builtins.str]] = None) -> 'Firewall':
        """
        Get an existing Firewall resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] created_date: The creation date of the Firewall.
        :param pulumi.Input[_builtins.str] description: The description of the Firewall. There is a limit of 255 characters per Firewall.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.int]]] instance_ids: Add the instace Ids to the firewall here. If you do not add any instance Ids an empty firewall will be created.
        :param pulumi.Input[Sequence[pulumi.Input[Union['FirewallInstancesStatusArgs', 'FirewallInstancesStatusArgsDict']]]] instances_statuses: The status of every instance in the firewall
        :param pulumi.Input[_builtins.str] name: The name of the Firewall. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Firewall name.
        :param pulumi.Input[_builtins.str] status: Status of the Firewall. It can be `active`, or `inactive`.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _FirewallState.__new__(_FirewallState)

        __props__.__dict__["created_date"] = created_date
        __props__.__dict__["description"] = description
        __props__.__dict__["instance_ids"] = instance_ids
        __props__.__dict__["instances_statuses"] = instances_statuses
        __props__.__dict__["name"] = name
        __props__.__dict__["rules"] = rules
        __props__.__dict__["status"] = status
        return Firewall(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="createdDate")
    def created_date(self) -> pulumi.Output[_builtins.str]:
        """
        The creation date of the Firewall.
        """
        return pulumi.get(self, "created_date")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The description of the Firewall. There is a limit of 255 characters per Firewall.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="instanceIds")
    def instance_ids(self) -> pulumi.Output[Optional[Sequence[_builtins.int]]]:
        """
        Add the instace Ids to the firewall here. If you do not add any instance Ids an empty firewall will be created.
        """
        return pulumi.get(self, "instance_ids")

    @_builtins.property
    @pulumi.getter(name="instancesStatuses")
    def instances_statuses(self) -> pulumi.Output[Sequence['outputs.FirewallInstancesStatus']]:
        """
        The status of every instance in the firewall
        """
        return pulumi.get(self, "instances_statuses")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the Firewall. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Firewall name.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def rules(self) -> pulumi.Output[Sequence['outputs.FirewallRule']]:
        return pulumi.get(self, "rules")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output[_builtins.str]:
        """
        Status of the Firewall. It can be `active`, or `inactive`.
        """
        return pulumi.get(self, "status")

