# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'GetFirewallResult',
    'AwaitableGetFirewallResult',
    'get_firewall',
    'get_firewall_output',
]

@pulumi.output_type
class GetFirewallResult:
    """
    A collection of values returned by getFirewall.
    """
    def __init__(__self__, created_date=None, description=None, id=None, instance_ids=None, instances_statuses=None, name=None, rules=None, status=None):
        if created_date and not isinstance(created_date, str):
            raise TypeError("Expected argument 'created_date' to be a str")
        pulumi.set(__self__, "created_date", created_date)
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if instance_ids and not isinstance(instance_ids, list):
            raise TypeError("Expected argument 'instance_ids' to be a list")
        pulumi.set(__self__, "instance_ids", instance_ids)
        if instances_statuses and not isinstance(instances_statuses, list):
            raise TypeError("Expected argument 'instances_statuses' to be a list")
        pulumi.set(__self__, "instances_statuses", instances_statuses)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if rules and not isinstance(rules, list):
            raise TypeError("Expected argument 'rules' to be a list")
        pulumi.set(__self__, "rules", rules)
        if status and not isinstance(status, str):
            raise TypeError("Expected argument 'status' to be a str")
        pulumi.set(__self__, "status", status)

    @_builtins.property
    @pulumi.getter(name="createdDate")
    def created_date(self) -> _builtins.str:
        """
        The creation date of the Firewall.
        """
        return pulumi.get(self, "created_date")

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[_builtins.str]:
        """
        The description of the Firewall. There is a limit of 255 characters per Firewall.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The identifier of the Firewall. Use it to manage it!
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="instanceIds")
    def instance_ids(self) -> Optional[Sequence[_builtins.int]]:
        """
        Add the instace Ids to the firewall here. If you do not add any instance Ids an empty firewall will be created.
        """
        return pulumi.get(self, "instance_ids")

    @_builtins.property
    @pulumi.getter(name="instancesStatuses")
    def instances_statuses(self) -> Sequence['outputs.GetFirewallInstancesStatusResult']:
        """
        The status of every instance in the firewall
        """
        return pulumi.get(self, "instances_statuses")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The name of the Firewall. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Firewall name.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def rules(self) -> Sequence['outputs.GetFirewallRuleResult']:
        return pulumi.get(self, "rules")

    @_builtins.property
    @pulumi.getter
    def status(self) -> _builtins.str:
        """
        Status of the Firewall. It can be `active`, or `inactive`.
        """
        return pulumi.get(self, "status")


class AwaitableGetFirewallResult(GetFirewallResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetFirewallResult(
            created_date=self.created_date,
            description=self.description,
            id=self.id,
            instance_ids=self.instance_ids,
            instances_statuses=self.instances_statuses,
            name=self.name,
            rules=self.rules,
            status=self.status)


def get_firewall(created_date: Optional[_builtins.str] = None,
                 description: Optional[_builtins.str] = None,
                 instance_ids: Optional[Sequence[_builtins.int]] = None,
                 instances_statuses: Optional[Sequence[Union['GetFirewallInstancesStatusArgs', 'GetFirewallInstancesStatusArgsDict']]] = None,
                 name: Optional[_builtins.str] = None,
                 rules: Optional[Sequence[Union['GetFirewallRuleArgs', 'GetFirewallRuleArgsDict']]] = None,
                 status: Optional[_builtins.str] = None,
                 opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetFirewallResult:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str created_date: The creation date of the Firewall.
    :param _builtins.str description: The description of the Firewall. There is a limit of 255 characters per Firewall.
    :param Sequence[_builtins.int] instance_ids: Add the instace Ids to the firewall here. If you do not add any instance Ids an empty firewall will be created.
    :param Sequence[Union['GetFirewallInstancesStatusArgs', 'GetFirewallInstancesStatusArgsDict']] instances_statuses: The status of every instance in the firewall
    :param _builtins.str name: The name of the Firewall. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Firewall name.
    :param _builtins.str status: Status of the Firewall. It can be `active`, or `inactive`.
    """
    __args__ = dict()
    __args__['createdDate'] = created_date
    __args__['description'] = description
    __args__['instanceIds'] = instance_ids
    __args__['instancesStatuses'] = instances_statuses
    __args__['name'] = name
    __args__['rules'] = rules
    __args__['status'] = status
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('contabo:index/getFirewall:getFirewall', __args__, opts=opts, typ=GetFirewallResult).value

    return AwaitableGetFirewallResult(
        created_date=pulumi.get(__ret__, 'created_date'),
        description=pulumi.get(__ret__, 'description'),
        id=pulumi.get(__ret__, 'id'),
        instance_ids=pulumi.get(__ret__, 'instance_ids'),
        instances_statuses=pulumi.get(__ret__, 'instances_statuses'),
        name=pulumi.get(__ret__, 'name'),
        rules=pulumi.get(__ret__, 'rules'),
        status=pulumi.get(__ret__, 'status'))
def get_firewall_output(created_date: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                        description: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                        instance_ids: pulumi.Input[Optional[Optional[Sequence[_builtins.int]]]] = None,
                        instances_statuses: pulumi.Input[Optional[Optional[Sequence[Union['GetFirewallInstancesStatusArgs', 'GetFirewallInstancesStatusArgsDict']]]]] = None,
                        name: pulumi.Input[Optional[_builtins.str]] = None,
                        rules: pulumi.Input[Optional[Optional[Sequence[Union['GetFirewallRuleArgs', 'GetFirewallRuleArgsDict']]]]] = None,
                        status: pulumi.Input[Optional[_builtins.str]] = None,
                        opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetFirewallResult]:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str created_date: The creation date of the Firewall.
    :param _builtins.str description: The description of the Firewall. There is a limit of 255 characters per Firewall.
    :param Sequence[_builtins.int] instance_ids: Add the instace Ids to the firewall here. If you do not add any instance Ids an empty firewall will be created.
    :param Sequence[Union['GetFirewallInstancesStatusArgs', 'GetFirewallInstancesStatusArgsDict']] instances_statuses: The status of every instance in the firewall
    :param _builtins.str name: The name of the Firewall. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Firewall name.
    :param _builtins.str status: Status of the Firewall. It can be `active`, or `inactive`.
    """
    __args__ = dict()
    __args__['createdDate'] = created_date
    __args__['description'] = description
    __args__['instanceIds'] = instance_ids
    __args__['instancesStatuses'] = instances_statuses
    __args__['name'] = name
    __args__['rules'] = rules
    __args__['status'] = status
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('contabo:index/getFirewall:getFirewall', __args__, opts=opts, typ=GetFirewallResult)
    return __ret__.apply(lambda __response__: GetFirewallResult(
        created_date=pulumi.get(__response__, 'created_date'),
        description=pulumi.get(__response__, 'description'),
        id=pulumi.get(__response__, 'id'),
        instance_ids=pulumi.get(__response__, 'instance_ids'),
        instances_statuses=pulumi.get(__response__, 'instances_statuses'),
        name=pulumi.get(__response__, 'name'),
        rules=pulumi.get(__response__, 'rules'),
        status=pulumi.get(__response__, 'status')))
