# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'GetObjectStorageResult',
    'AwaitableGetObjectStorageResult',
    'get_object_storage',
    'get_object_storage_output',
]

@pulumi.output_type
class GetObjectStorageResult:
    """
    A collection of values returned by getObjectStorage.
    """
    def __init__(__self__, auto_scalings=None, cancel_date=None, created_date=None, customer_id=None, data_center=None, display_name=None, id=None, region=None, s3_tenant_id=None, s3_url=None, status=None, tenant_id=None, total_purchased_space_tb=None):
        if auto_scalings and not isinstance(auto_scalings, list):
            raise TypeError("Expected argument 'auto_scalings' to be a list")
        pulumi.set(__self__, "auto_scalings", auto_scalings)
        if cancel_date and not isinstance(cancel_date, str):
            raise TypeError("Expected argument 'cancel_date' to be a str")
        pulumi.set(__self__, "cancel_date", cancel_date)
        if created_date and not isinstance(created_date, str):
            raise TypeError("Expected argument 'created_date' to be a str")
        pulumi.set(__self__, "created_date", created_date)
        if customer_id and not isinstance(customer_id, str):
            raise TypeError("Expected argument 'customer_id' to be a str")
        pulumi.set(__self__, "customer_id", customer_id)
        if data_center and not isinstance(data_center, str):
            raise TypeError("Expected argument 'data_center' to be a str")
        pulumi.set(__self__, "data_center", data_center)
        if display_name and not isinstance(display_name, str):
            raise TypeError("Expected argument 'display_name' to be a str")
        pulumi.set(__self__, "display_name", display_name)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if region and not isinstance(region, str):
            raise TypeError("Expected argument 'region' to be a str")
        pulumi.set(__self__, "region", region)
        if s3_tenant_id and not isinstance(s3_tenant_id, str):
            raise TypeError("Expected argument 's3_tenant_id' to be a str")
        pulumi.set(__self__, "s3_tenant_id", s3_tenant_id)
        if s3_url and not isinstance(s3_url, str):
            raise TypeError("Expected argument 's3_url' to be a str")
        pulumi.set(__self__, "s3_url", s3_url)
        if status and not isinstance(status, str):
            raise TypeError("Expected argument 'status' to be a str")
        pulumi.set(__self__, "status", status)
        if tenant_id and not isinstance(tenant_id, str):
            raise TypeError("Expected argument 'tenant_id' to be a str")
        pulumi.set(__self__, "tenant_id", tenant_id)
        if total_purchased_space_tb and not isinstance(total_purchased_space_tb, float):
            raise TypeError("Expected argument 'total_purchased_space_tb' to be a float")
        pulumi.set(__self__, "total_purchased_space_tb", total_purchased_space_tb)

    @_builtins.property
    @pulumi.getter(name="autoScalings")
    def auto_scalings(self) -> Sequence['outputs.GetObjectStorageAutoScalingResult']:
        return pulumi.get(self, "auto_scalings")

    @_builtins.property
    @pulumi.getter(name="cancelDate")
    def cancel_date(self) -> _builtins.str:
        """
        The date on which the Object Storage will be cancelled and therefore no longer available.
        """
        return pulumi.get(self, "cancel_date")

    @_builtins.property
    @pulumi.getter(name="createdDate")
    def created_date(self) -> _builtins.str:
        """
        The creation date of the Object Storage.
        """
        return pulumi.get(self, "created_date")

    @_builtins.property
    @pulumi.getter(name="customerId")
    def customer_id(self) -> _builtins.str:
        """
        Your customer number.
        """
        return pulumi.get(self, "customer_id")

    @_builtins.property
    @pulumi.getter(name="dataCenter")
    def data_center(self) -> _builtins.str:
        """
        Data center the object storage is located in.
        """
        return pulumi.get(self, "data_center")

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> Optional[_builtins.str]:
        """
        Display name for object storage. Use it to manage it!
        """
        return pulumi.get(self, "display_name")

    @_builtins.property
    @pulumi.getter
    def id(self) -> Optional[_builtins.str]:
        """
        The identifier of the Object Storage. Use it to manage it!
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def region(self) -> _builtins.str:
        """
        Region where the Object Storage should be located. Default region is the EU. Following regions are available: `EU`,`US-central`, `SIN`.
        """
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter(name="s3TenantId")
    def s3_tenant_id(self) -> _builtins.str:
        """
        Your S3 tenant Id. Only required for public sharing.
        """
        return pulumi.get(self, "s3_tenant_id")

    @_builtins.property
    @pulumi.getter(name="s3Url")
    def s3_url(self) -> _builtins.str:
        """
        S3 URL to connect to your S3 compatible Object Storage.
        """
        return pulumi.get(self, "s3_url")

    @_builtins.property
    @pulumi.getter
    def status(self) -> _builtins.str:
        """
        The object storage status. It can be set to `PROVISIONING`,`READY`,`UPGRADING`,`CANCELLED`,`ERROR` or `DISABLED`.
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter(name="tenantId")
    def tenant_id(self) -> _builtins.str:
        """
        Your customer tenant Id.
        """
        return pulumi.get(self, "tenant_id")

    @_builtins.property
    @pulumi.getter(name="totalPurchasedSpaceTb")
    def total_purchased_space_tb(self) -> _builtins.float:
        """
        Amount of purchased / requested object storage in terabyte.
        """
        return pulumi.get(self, "total_purchased_space_tb")


class AwaitableGetObjectStorageResult(GetObjectStorageResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetObjectStorageResult(
            auto_scalings=self.auto_scalings,
            cancel_date=self.cancel_date,
            created_date=self.created_date,
            customer_id=self.customer_id,
            data_center=self.data_center,
            display_name=self.display_name,
            id=self.id,
            region=self.region,
            s3_tenant_id=self.s3_tenant_id,
            s3_url=self.s3_url,
            status=self.status,
            tenant_id=self.tenant_id,
            total_purchased_space_tb=self.total_purchased_space_tb)


def get_object_storage(auto_scalings: Optional[Sequence[Union['GetObjectStorageAutoScalingArgs', 'GetObjectStorageAutoScalingArgsDict']]] = None,
                       display_name: Optional[_builtins.str] = None,
                       id: Optional[_builtins.str] = None,
                       opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetObjectStorageResult:
    """
    Manage S3 compatible Object Storage. With the Object Storage API you can create Object Storages in different locations. Please note that you can only have one Object Storage per location. Furthermore, you can increase the amount of storage space and control the autoscaling feature which allows you to automatically perform a monthly upgrade of the disk space to the specified maximum. You might also inspect the usage. This API is not the S3 API itself. For accessing the S3 API directly or with S3 compatible tools like `aws` cli and after having created / upgraded your Object Storage please use the S3 URL from this Storage API and refer to the User Mangement API to retrieve the S3 credentials.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_contabo as contabo

    # Search object storage by ID
    example1 = contabo.get_object_storage(id="3a6e5301-fc71-42ce-b60c-49841681c2da")
    # Search object storage by display name
    example2 = contabo.get_object_storage(display_name="example2")
    pulumi.export("myObjectStorage1", example1)
    pulumi.export("myObjectStorage2", example1)
    ```


    :param _builtins.str display_name: Display name for object storage. Use it to manage it!
    :param _builtins.str id: The identifier of the Object Storage. Use it to manage it!
    """
    __args__ = dict()
    __args__['autoScalings'] = auto_scalings
    __args__['displayName'] = display_name
    __args__['id'] = id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('contabo:index/getObjectStorage:getObjectStorage', __args__, opts=opts, typ=GetObjectStorageResult).value

    return AwaitableGetObjectStorageResult(
        auto_scalings=pulumi.get(__ret__, 'auto_scalings'),
        cancel_date=pulumi.get(__ret__, 'cancel_date'),
        created_date=pulumi.get(__ret__, 'created_date'),
        customer_id=pulumi.get(__ret__, 'customer_id'),
        data_center=pulumi.get(__ret__, 'data_center'),
        display_name=pulumi.get(__ret__, 'display_name'),
        id=pulumi.get(__ret__, 'id'),
        region=pulumi.get(__ret__, 'region'),
        s3_tenant_id=pulumi.get(__ret__, 's3_tenant_id'),
        s3_url=pulumi.get(__ret__, 's3_url'),
        status=pulumi.get(__ret__, 'status'),
        tenant_id=pulumi.get(__ret__, 'tenant_id'),
        total_purchased_space_tb=pulumi.get(__ret__, 'total_purchased_space_tb'))
def get_object_storage_output(auto_scalings: pulumi.Input[Optional[Optional[Sequence[Union['GetObjectStorageAutoScalingArgs', 'GetObjectStorageAutoScalingArgsDict']]]]] = None,
                              display_name: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                              id: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                              opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetObjectStorageResult]:
    """
    Manage S3 compatible Object Storage. With the Object Storage API you can create Object Storages in different locations. Please note that you can only have one Object Storage per location. Furthermore, you can increase the amount of storage space and control the autoscaling feature which allows you to automatically perform a monthly upgrade of the disk space to the specified maximum. You might also inspect the usage. This API is not the S3 API itself. For accessing the S3 API directly or with S3 compatible tools like `aws` cli and after having created / upgraded your Object Storage please use the S3 URL from this Storage API and refer to the User Mangement API to retrieve the S3 credentials.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_contabo as contabo

    # Search object storage by ID
    example1 = contabo.get_object_storage(id="3a6e5301-fc71-42ce-b60c-49841681c2da")
    # Search object storage by display name
    example2 = contabo.get_object_storage(display_name="example2")
    pulumi.export("myObjectStorage1", example1)
    pulumi.export("myObjectStorage2", example1)
    ```


    :param _builtins.str display_name: Display name for object storage. Use it to manage it!
    :param _builtins.str id: The identifier of the Object Storage. Use it to manage it!
    """
    __args__ = dict()
    __args__['autoScalings'] = auto_scalings
    __args__['displayName'] = display_name
    __args__['id'] = id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('contabo:index/getObjectStorage:getObjectStorage', __args__, opts=opts, typ=GetObjectStorageResult)
    return __ret__.apply(lambda __response__: GetObjectStorageResult(
        auto_scalings=pulumi.get(__response__, 'auto_scalings'),
        cancel_date=pulumi.get(__response__, 'cancel_date'),
        created_date=pulumi.get(__response__, 'created_date'),
        customer_id=pulumi.get(__response__, 'customer_id'),
        data_center=pulumi.get(__response__, 'data_center'),
        display_name=pulumi.get(__response__, 'display_name'),
        id=pulumi.get(__response__, 'id'),
        region=pulumi.get(__response__, 'region'),
        s3_tenant_id=pulumi.get(__response__, 's3_tenant_id'),
        s3_url=pulumi.get(__response__, 's3_url'),
        status=pulumi.get(__response__, 'status'),
        tenant_id=pulumi.get(__response__, 'tenant_id'),
        total_purchased_space_tb=pulumi.get(__response__, 'total_purchased_space_tb')))
