# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetTagAssignmentResult',
    'AwaitableGetTagAssignmentResult',
    'get_tag_assignment',
    'get_tag_assignment_output',
]

@pulumi.output_type
class GetTagAssignmentResult:
    """
    A collection of values returned by getTagAssignment.
    """
    def __init__(__self__, id=None, resource_id=None, resource_name=None, resource_type=None, tag_id=None, tag_name=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if resource_id and not isinstance(resource_id, str):
            raise TypeError("Expected argument 'resource_id' to be a str")
        pulumi.set(__self__, "resource_id", resource_id)
        if resource_name and not isinstance(resource_name, str):
            raise TypeError("Expected argument 'resource_name' to be a str")
        pulumi.set(__self__, "resource_name", resource_name)
        if resource_type and not isinstance(resource_type, str):
            raise TypeError("Expected argument 'resource_type' to be a str")
        pulumi.set(__self__, "resource_type", resource_type)
        if tag_id and not isinstance(tag_id, int):
            raise TypeError("Expected argument 'tag_id' to be a int")
        pulumi.set(__self__, "tag_id", tag_id)
        if tag_name and not isinstance(tag_name, str):
            raise TypeError("Expected argument 'tag_name' to be a str")
        pulumi.set(__self__, "tag_name", tag_name)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The identifier of the tag assignment. Use it to manage it!
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="resourceId")
    def resource_id(self) -> _builtins.str:
        """
        The resource id.
        """
        return pulumi.get(self, "resource_id")

    @_builtins.property
    @pulumi.getter(name="resourceName")
    def resource_name(self) -> _builtins.str:
        """
        The resource name.
        """
        return pulumi.get(self, "resource_name")

    @_builtins.property
    @pulumi.getter(name="resourceType")
    def resource_type(self) -> _builtins.str:
        """
        The resource type.
        """
        return pulumi.get(self, "resource_type")

    @_builtins.property
    @pulumi.getter(name="tagId")
    def tag_id(self) -> _builtins.int:
        """
        The identifier of the tag.
        """
        return pulumi.get(self, "tag_id")

    @_builtins.property
    @pulumi.getter(name="tagName")
    def tag_name(self) -> _builtins.str:
        """
        The name of the tag.
        """
        return pulumi.get(self, "tag_name")


class AwaitableGetTagAssignmentResult(GetTagAssignmentResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetTagAssignmentResult(
            id=self.id,
            resource_id=self.resource_id,
            resource_name=self.resource_name,
            resource_type=self.resource_type,
            tag_id=self.tag_id,
            tag_name=self.tag_name)


def get_tag_assignment(id: Optional[_builtins.str] = None,
                       resource_id: Optional[_builtins.str] = None,
                       resource_type: Optional[_builtins.str] = None,
                       tag_id: Optional[_builtins.int] = None,
                       opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetTagAssignmentResult:
    """
    Tag assignment marks the specified resource with the specified tag for organizing purposes or to restrict access to that resource.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_contabo as contabo

    # Get a specific tag assignment by tagId_resourceType_resourceId
    default_tag_assignment = contabo.get_tag_assignment(id="178478_image_35ee288f-21ea-420c-a074-ce0a968b59c0")
    pulumi.export("output", default_tag_assignment)
    ```


    :param _builtins.str id: The identifier of the tag assignment. Use it to manage it!
    :param _builtins.str resource_id: The resource id.
    :param _builtins.str resource_type: The resource type.
    :param _builtins.int tag_id: The identifier of the tag.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['resourceId'] = resource_id
    __args__['resourceType'] = resource_type
    __args__['tagId'] = tag_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('contabo:index/getTagAssignment:getTagAssignment', __args__, opts=opts, typ=GetTagAssignmentResult).value

    return AwaitableGetTagAssignmentResult(
        id=pulumi.get(__ret__, 'id'),
        resource_id=pulumi.get(__ret__, 'resource_id'),
        resource_name=pulumi.get(__ret__, 'resource_name'),
        resource_type=pulumi.get(__ret__, 'resource_type'),
        tag_id=pulumi.get(__ret__, 'tag_id'),
        tag_name=pulumi.get(__ret__, 'tag_name'))
def get_tag_assignment_output(id: pulumi.Input[Optional[_builtins.str]] = None,
                              resource_id: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                              resource_type: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                              tag_id: pulumi.Input[Optional[Optional[_builtins.int]]] = None,
                              opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetTagAssignmentResult]:
    """
    Tag assignment marks the specified resource with the specified tag for organizing purposes or to restrict access to that resource.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_contabo as contabo

    # Get a specific tag assignment by tagId_resourceType_resourceId
    default_tag_assignment = contabo.get_tag_assignment(id="178478_image_35ee288f-21ea-420c-a074-ce0a968b59c0")
    pulumi.export("output", default_tag_assignment)
    ```


    :param _builtins.str id: The identifier of the tag assignment. Use it to manage it!
    :param _builtins.str resource_id: The resource id.
    :param _builtins.str resource_type: The resource type.
    :param _builtins.int tag_id: The identifier of the tag.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['resourceId'] = resource_id
    __args__['resourceType'] = resource_type
    __args__['tagId'] = tag_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('contabo:index/getTagAssignment:getTagAssignment', __args__, opts=opts, typ=GetTagAssignmentResult)
    return __ret__.apply(lambda __response__: GetTagAssignmentResult(
        id=pulumi.get(__response__, 'id'),
        resource_id=pulumi.get(__response__, 'resource_id'),
        resource_name=pulumi.get(__response__, 'resource_name'),
        resource_type=pulumi.get(__response__, 'resource_type'),
        tag_id=pulumi.get(__response__, 'tag_id'),
        tag_name=pulumi.get(__response__, 'tag_name')))
