# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'GetInstanceResult',
    'AwaitableGetInstanceResult',
    'get_instance',
    'get_instance_output',
]

@pulumi.output_type
class GetInstanceResult:
    """
    A collection of values returned by getInstance.
    """
    def __init__(__self__, add_ons=None, additional_ips_v4s=None, cancel_date=None, cpu_cores=None, created_date=None, default_user=None, disk_mb=None, display_name=None, error_message=None, id=None, image_id=None, ip_configs=None, last_updated=None, license=None, mac_address=None, name=None, os_type=None, period=None, product_id=None, product_type=None, ram_mb=None, region=None, ssh_keys=None, status=None, user_data=None, v_host_id=None):
        if add_ons and not isinstance(add_ons, list):
            raise TypeError("Expected argument 'add_ons' to be a list")
        pulumi.set(__self__, "add_ons", add_ons)
        if additional_ips_v4s and not isinstance(additional_ips_v4s, list):
            raise TypeError("Expected argument 'additional_ips_v4s' to be a list")
        pulumi.set(__self__, "additional_ips_v4s", additional_ips_v4s)
        if cancel_date and not isinstance(cancel_date, str):
            raise TypeError("Expected argument 'cancel_date' to be a str")
        pulumi.set(__self__, "cancel_date", cancel_date)
        if cpu_cores and not isinstance(cpu_cores, int):
            raise TypeError("Expected argument 'cpu_cores' to be a int")
        pulumi.set(__self__, "cpu_cores", cpu_cores)
        if created_date and not isinstance(created_date, str):
            raise TypeError("Expected argument 'created_date' to be a str")
        pulumi.set(__self__, "created_date", created_date)
        if default_user and not isinstance(default_user, str):
            raise TypeError("Expected argument 'default_user' to be a str")
        pulumi.set(__self__, "default_user", default_user)
        if disk_mb and not isinstance(disk_mb, int):
            raise TypeError("Expected argument 'disk_mb' to be a int")
        pulumi.set(__self__, "disk_mb", disk_mb)
        if display_name and not isinstance(display_name, str):
            raise TypeError("Expected argument 'display_name' to be a str")
        pulumi.set(__self__, "display_name", display_name)
        if error_message and not isinstance(error_message, str):
            raise TypeError("Expected argument 'error_message' to be a str")
        pulumi.set(__self__, "error_message", error_message)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if image_id and not isinstance(image_id, str):
            raise TypeError("Expected argument 'image_id' to be a str")
        pulumi.set(__self__, "image_id", image_id)
        if ip_configs and not isinstance(ip_configs, list):
            raise TypeError("Expected argument 'ip_configs' to be a list")
        pulumi.set(__self__, "ip_configs", ip_configs)
        if last_updated and not isinstance(last_updated, str):
            raise TypeError("Expected argument 'last_updated' to be a str")
        pulumi.set(__self__, "last_updated", last_updated)
        if license and not isinstance(license, str):
            raise TypeError("Expected argument 'license' to be a str")
        pulumi.set(__self__, "license", license)
        if mac_address and not isinstance(mac_address, str):
            raise TypeError("Expected argument 'mac_address' to be a str")
        pulumi.set(__self__, "mac_address", mac_address)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if os_type and not isinstance(os_type, str):
            raise TypeError("Expected argument 'os_type' to be a str")
        pulumi.set(__self__, "os_type", os_type)
        if period and not isinstance(period, int):
            raise TypeError("Expected argument 'period' to be a int")
        pulumi.set(__self__, "period", period)
        if product_id and not isinstance(product_id, str):
            raise TypeError("Expected argument 'product_id' to be a str")
        pulumi.set(__self__, "product_id", product_id)
        if product_type and not isinstance(product_type, str):
            raise TypeError("Expected argument 'product_type' to be a str")
        pulumi.set(__self__, "product_type", product_type)
        if ram_mb and not isinstance(ram_mb, int):
            raise TypeError("Expected argument 'ram_mb' to be a int")
        pulumi.set(__self__, "ram_mb", ram_mb)
        if region and not isinstance(region, str):
            raise TypeError("Expected argument 'region' to be a str")
        pulumi.set(__self__, "region", region)
        if ssh_keys and not isinstance(ssh_keys, list):
            raise TypeError("Expected argument 'ssh_keys' to be a list")
        pulumi.set(__self__, "ssh_keys", ssh_keys)
        if status and not isinstance(status, str):
            raise TypeError("Expected argument 'status' to be a str")
        pulumi.set(__self__, "status", status)
        if user_data and not isinstance(user_data, str):
            raise TypeError("Expected argument 'user_data' to be a str")
        pulumi.set(__self__, "user_data", user_data)
        if v_host_id and not isinstance(v_host_id, int):
            raise TypeError("Expected argument 'v_host_id' to be a int")
        pulumi.set(__self__, "v_host_id", v_host_id)

    @_builtins.property
    @pulumi.getter(name="addOns")
    def add_ons(self) -> Sequence['outputs.GetInstanceAddOnResult']:
        return pulumi.get(self, "add_ons")

    @_builtins.property
    @pulumi.getter(name="additionalIpsV4s")
    def additional_ips_v4s(self) -> Sequence['outputs.GetInstanceAdditionalIpsV4Result']:
        """
        All other additional IP addresses of the instance.
        """
        return pulumi.get(self, "additional_ips_v4s")

    @_builtins.property
    @pulumi.getter(name="cancelDate")
    def cancel_date(self) -> _builtins.str:
        """
        The date on which the instance will be cancelled.
        """
        return pulumi.get(self, "cancel_date")

    @_builtins.property
    @pulumi.getter(name="cpuCores")
    def cpu_cores(self) -> _builtins.int:
        """
        CPU core count of the instance.
        """
        return pulumi.get(self, "cpu_cores")

    @_builtins.property
    @pulumi.getter(name="createdDate")
    def created_date(self) -> _builtins.str:
        """
        The creation date of the compute instance.
        """
        return pulumi.get(self, "created_date")

    @_builtins.property
    @pulumi.getter(name="defaultUser")
    def default_user(self) -> _builtins.str:
        """
        Default user name created for login during (re-)installation with administrative privileges. Allowed values for Linux/BSD are admin (use sudo to apply administrative privileges like root) or root. Allowed values for Windows are admin (has administrative privileges like administrator) or administrator.See our [api documentation](https://api.contabo.com/#tag/Instances/operation/createInstance) for available default users.
        """
        return pulumi.get(self, "default_user")

    @_builtins.property
    @pulumi.getter(name="diskMb")
    def disk_mb(self) -> _builtins.int:
        """
        Image disk size of the instance in megabyte.
        """
        return pulumi.get(self, "disk_mb")

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> _builtins.str:
        """
        Image Id is used to set up the compute instance. Ubuntu 20.04 is the default.
        """
        return pulumi.get(self, "display_name")

    @_builtins.property
    @pulumi.getter(name="errorMessage")
    def error_message(self) -> _builtins.str:
        """
        If the instance is in an error state (see status property), the error message can be seen in this field.
        """
        return pulumi.get(self, "error_message")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The identifier of the compute instance. Use it to manage it!
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="imageId")
    def image_id(self) -> _builtins.str:
        """
        Image Id is used to set up the compute instance. Ubuntu 20.04 is the default.
        """
        return pulumi.get(self, "image_id")

    @_builtins.property
    @pulumi.getter(name="ipConfigs")
    def ip_configs(self) -> Sequence['outputs.GetInstanceIpConfigResult']:
        return pulumi.get(self, "ip_configs")

    @_builtins.property
    @pulumi.getter(name="lastUpdated")
    def last_updated(self) -> _builtins.str:
        """
        Time of the last update of the compute instance.
        """
        return pulumi.get(self, "last_updated")

    @_builtins.property
    @pulumi.getter
    def license(self) -> _builtins.str:
        """
        Additional license in order to enhance your chosen product. It is mainly needed for software licenses on your product (not needed for windows). See our [api documentation](https://api.contabo.com/#tag/Instances/operation/createInstance) for all available licenses.
        """
        return pulumi.get(self, "license")

    @_builtins.property
    @pulumi.getter(name="macAddress")
    def mac_address(self) -> _builtins.str:
        """
        Mac address of the instance.
        """
        return pulumi.get(self, "mac_address")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        Name of the compute instance.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="osType")
    def os_type(self) -> _builtins.str:
        """
        Type of operating system (OS) installed on the instance.
        """
        return pulumi.get(self, "os_type")

    @_builtins.property
    @pulumi.getter
    def period(self) -> _builtins.int:
        """
        Initial contract period in months. Available periods are: 1, 3, 6 and 12 months. The default setting is 1 month.
        """
        return pulumi.get(self, "period")

    @_builtins.property
    @pulumi.getter(name="productId")
    def product_id(self) -> _builtins.str:
        """
        Choose the VPS/VDS product you want to buy. See our products [here](https://api.contabo.com/#tag/Instances/operation/createInstance).
        """
        return pulumi.get(self, "product_id")

    @_builtins.property
    @pulumi.getter(name="productType")
    def product_type(self) -> _builtins.str:
        """
        InsInstance's category depending on Product Id. Following product types are available: `hdd`,`ssd`,`vds`,`nvme`.
        """
        return pulumi.get(self, "product_type")

    @_builtins.property
    @pulumi.getter(name="ramMb")
    def ram_mb(self) -> _builtins.int:
        """
        Image ram size in megabyte.
        """
        return pulumi.get(self, "ram_mb")

    @_builtins.property
    @pulumi.getter
    def region(self) -> _builtins.str:
        """
        Instance Region where the compute instance should be located. Default region is the EU. Following regions are available: `EU`,`US-central`,`US-east`,`US-west`,`SIN`.
        """
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter(name="sshKeys")
    def ssh_keys(self) -> Sequence[_builtins.int]:
        """
        Array of `secretIds` of public SSH keys for logging into as defaultUser with administrator/root privileges. Applies to Linux/BSD systems. Please refer to Secrets Management API.
        """
        return pulumi.get(self, "ssh_keys")

    @_builtins.property
    @pulumi.getter
    def status(self) -> _builtins.str:
        """
        Status of the compute instance. The status can be set to `provisioning`, `uninstalled`, `running`, `stopped`, `error`, `installing`, `unknown`, or `installed`.
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter(name="userData")
    def user_data(self) -> _builtins.str:
        """
        Cloud-Init Config in order to customize during start of compute instance.
        """
        return pulumi.get(self, "user_data")

    @_builtins.property
    @pulumi.getter(name="vHostId")
    def v_host_id(self) -> _builtins.int:
        """
        Identifier of the host system.
        """
        return pulumi.get(self, "v_host_id")


class AwaitableGetInstanceResult(GetInstanceResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetInstanceResult(
            add_ons=self.add_ons,
            additional_ips_v4s=self.additional_ips_v4s,
            cancel_date=self.cancel_date,
            cpu_cores=self.cpu_cores,
            created_date=self.created_date,
            default_user=self.default_user,
            disk_mb=self.disk_mb,
            display_name=self.display_name,
            error_message=self.error_message,
            id=self.id,
            image_id=self.image_id,
            ip_configs=self.ip_configs,
            last_updated=self.last_updated,
            license=self.license,
            mac_address=self.mac_address,
            name=self.name,
            os_type=self.os_type,
            period=self.period,
            product_id=self.product_id,
            product_type=self.product_type,
            ram_mb=self.ram_mb,
            region=self.region,
            ssh_keys=self.ssh_keys,
            status=self.status,
            user_data=self.user_data,
            v_host_id=self.v_host_id)


def get_instance(add_ons: Optional[Sequence[Union['GetInstanceAddOnArgs', 'GetInstanceAddOnArgsDict']]] = None,
                 cancel_date: Optional[_builtins.str] = None,
                 default_user: Optional[_builtins.str] = None,
                 display_name: Optional[_builtins.str] = None,
                 id: Optional[_builtins.str] = None,
                 image_id: Optional[_builtins.str] = None,
                 license: Optional[_builtins.str] = None,
                 product_id: Optional[_builtins.str] = None,
                 region: Optional[_builtins.str] = None,
                 ssh_keys: Optional[Sequence[_builtins.int]] = None,
                 user_data: Optional[_builtins.str] = None,
                 opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetInstanceResult:
    """
    The Compute Management API allows you to manage compute resources (e.g. creation, deletion, starting, stopping) as well as managing snapshots and custom images. It also supports [cloud-init](https://cloud-init.io/) at least on our default images (for custom images you will need to provide cloud-init support packages). The API offers providing cloud-init scripts via the user_data field. Custom images must be provided in .qcow2 or .iso format.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_contabo as contabo

    # Search for a specific instance by ID
    test_instance = contabo.get_instance(id="123455")
    pulumi.export("myTestInstance", test_instance)
    ```


    :param _builtins.str cancel_date: The date on which the instance will be cancelled.
    :param _builtins.str default_user: Default user name created for login during (re-)installation with administrative privileges. Allowed values for Linux/BSD are admin (use sudo to apply administrative privileges like root) or root. Allowed values for Windows are admin (has administrative privileges like administrator) or administrator.See our [api documentation](https://api.contabo.com/#tag/Instances/operation/createInstance) for available default users.
    :param _builtins.str display_name: Image Id is used to set up the compute instance. Ubuntu 20.04 is the default.
    :param _builtins.str id: The identifier of the compute instance. Use it to manage it!
    :param _builtins.str image_id: Image Id is used to set up the compute instance. Ubuntu 20.04 is the default.
    :param _builtins.str license: Additional license in order to enhance your chosen product. It is mainly needed for software licenses on your product (not needed for windows). See our [api documentation](https://api.contabo.com/#tag/Instances/operation/createInstance) for all available licenses.
    :param _builtins.str product_id: Choose the VPS/VDS product you want to buy. See our products [here](https://api.contabo.com/#tag/Instances/operation/createInstance).
    :param _builtins.str region: Instance Region where the compute instance should be located. Default region is the EU. Following regions are available: `EU`,`US-central`,`US-east`,`US-west`,`SIN`.
    :param Sequence[_builtins.int] ssh_keys: Array of `secretIds` of public SSH keys for logging into as defaultUser with administrator/root privileges. Applies to Linux/BSD systems. Please refer to Secrets Management API.
    :param _builtins.str user_data: Cloud-Init Config in order to customize during start of compute instance.
    """
    __args__ = dict()
    __args__['addOns'] = add_ons
    __args__['cancelDate'] = cancel_date
    __args__['defaultUser'] = default_user
    __args__['displayName'] = display_name
    __args__['id'] = id
    __args__['imageId'] = image_id
    __args__['license'] = license
    __args__['productId'] = product_id
    __args__['region'] = region
    __args__['sshKeys'] = ssh_keys
    __args__['userData'] = user_data
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('contabo:index/getInstance:getInstance', __args__, opts=opts, typ=GetInstanceResult).value

    return AwaitableGetInstanceResult(
        add_ons=pulumi.get(__ret__, 'add_ons'),
        additional_ips_v4s=pulumi.get(__ret__, 'additional_ips_v4s'),
        cancel_date=pulumi.get(__ret__, 'cancel_date'),
        cpu_cores=pulumi.get(__ret__, 'cpu_cores'),
        created_date=pulumi.get(__ret__, 'created_date'),
        default_user=pulumi.get(__ret__, 'default_user'),
        disk_mb=pulumi.get(__ret__, 'disk_mb'),
        display_name=pulumi.get(__ret__, 'display_name'),
        error_message=pulumi.get(__ret__, 'error_message'),
        id=pulumi.get(__ret__, 'id'),
        image_id=pulumi.get(__ret__, 'image_id'),
        ip_configs=pulumi.get(__ret__, 'ip_configs'),
        last_updated=pulumi.get(__ret__, 'last_updated'),
        license=pulumi.get(__ret__, 'license'),
        mac_address=pulumi.get(__ret__, 'mac_address'),
        name=pulumi.get(__ret__, 'name'),
        os_type=pulumi.get(__ret__, 'os_type'),
        period=pulumi.get(__ret__, 'period'),
        product_id=pulumi.get(__ret__, 'product_id'),
        product_type=pulumi.get(__ret__, 'product_type'),
        ram_mb=pulumi.get(__ret__, 'ram_mb'),
        region=pulumi.get(__ret__, 'region'),
        ssh_keys=pulumi.get(__ret__, 'ssh_keys'),
        status=pulumi.get(__ret__, 'status'),
        user_data=pulumi.get(__ret__, 'user_data'),
        v_host_id=pulumi.get(__ret__, 'v_host_id'))
def get_instance_output(add_ons: pulumi.Input[Optional[Optional[Sequence[Union['GetInstanceAddOnArgs', 'GetInstanceAddOnArgsDict']]]]] = None,
                        cancel_date: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                        default_user: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                        display_name: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                        id: pulumi.Input[Optional[_builtins.str]] = None,
                        image_id: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                        license: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                        product_id: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                        region: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                        ssh_keys: pulumi.Input[Optional[Optional[Sequence[_builtins.int]]]] = None,
                        user_data: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                        opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetInstanceResult]:
    """
    The Compute Management API allows you to manage compute resources (e.g. creation, deletion, starting, stopping) as well as managing snapshots and custom images. It also supports [cloud-init](https://cloud-init.io/) at least on our default images (for custom images you will need to provide cloud-init support packages). The API offers providing cloud-init scripts via the user_data field. Custom images must be provided in .qcow2 or .iso format.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_contabo as contabo

    # Search for a specific instance by ID
    test_instance = contabo.get_instance(id="123455")
    pulumi.export("myTestInstance", test_instance)
    ```


    :param _builtins.str cancel_date: The date on which the instance will be cancelled.
    :param _builtins.str default_user: Default user name created for login during (re-)installation with administrative privileges. Allowed values for Linux/BSD are admin (use sudo to apply administrative privileges like root) or root. Allowed values for Windows are admin (has administrative privileges like administrator) or administrator.See our [api documentation](https://api.contabo.com/#tag/Instances/operation/createInstance) for available default users.
    :param _builtins.str display_name: Image Id is used to set up the compute instance. Ubuntu 20.04 is the default.
    :param _builtins.str id: The identifier of the compute instance. Use it to manage it!
    :param _builtins.str image_id: Image Id is used to set up the compute instance. Ubuntu 20.04 is the default.
    :param _builtins.str license: Additional license in order to enhance your chosen product. It is mainly needed for software licenses on your product (not needed for windows). See our [api documentation](https://api.contabo.com/#tag/Instances/operation/createInstance) for all available licenses.
    :param _builtins.str product_id: Choose the VPS/VDS product you want to buy. See our products [here](https://api.contabo.com/#tag/Instances/operation/createInstance).
    :param _builtins.str region: Instance Region where the compute instance should be located. Default region is the EU. Following regions are available: `EU`,`US-central`,`US-east`,`US-west`,`SIN`.
    :param Sequence[_builtins.int] ssh_keys: Array of `secretIds` of public SSH keys for logging into as defaultUser with administrator/root privileges. Applies to Linux/BSD systems. Please refer to Secrets Management API.
    :param _builtins.str user_data: Cloud-Init Config in order to customize during start of compute instance.
    """
    __args__ = dict()
    __args__['addOns'] = add_ons
    __args__['cancelDate'] = cancel_date
    __args__['defaultUser'] = default_user
    __args__['displayName'] = display_name
    __args__['id'] = id
    __args__['imageId'] = image_id
    __args__['license'] = license
    __args__['productId'] = product_id
    __args__['region'] = region
    __args__['sshKeys'] = ssh_keys
    __args__['userData'] = user_data
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('contabo:index/getInstance:getInstance', __args__, opts=opts, typ=GetInstanceResult)
    return __ret__.apply(lambda __response__: GetInstanceResult(
        add_ons=pulumi.get(__response__, 'add_ons'),
        additional_ips_v4s=pulumi.get(__response__, 'additional_ips_v4s'),
        cancel_date=pulumi.get(__response__, 'cancel_date'),
        cpu_cores=pulumi.get(__response__, 'cpu_cores'),
        created_date=pulumi.get(__response__, 'created_date'),
        default_user=pulumi.get(__response__, 'default_user'),
        disk_mb=pulumi.get(__response__, 'disk_mb'),
        display_name=pulumi.get(__response__, 'display_name'),
        error_message=pulumi.get(__response__, 'error_message'),
        id=pulumi.get(__response__, 'id'),
        image_id=pulumi.get(__response__, 'image_id'),
        ip_configs=pulumi.get(__response__, 'ip_configs'),
        last_updated=pulumi.get(__response__, 'last_updated'),
        license=pulumi.get(__response__, 'license'),
        mac_address=pulumi.get(__response__, 'mac_address'),
        name=pulumi.get(__response__, 'name'),
        os_type=pulumi.get(__response__, 'os_type'),
        period=pulumi.get(__response__, 'period'),
        product_id=pulumi.get(__response__, 'product_id'),
        product_type=pulumi.get(__response__, 'product_type'),
        ram_mb=pulumi.get(__response__, 'ram_mb'),
        region=pulumi.get(__response__, 'region'),
        ssh_keys=pulumi.get(__response__, 'ssh_keys'),
        status=pulumi.get(__response__, 'status'),
        user_data=pulumi.get(__response__, 'user_data'),
        v_host_id=pulumi.get(__response__, 'v_host_id')))
