# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['PrivateNetworkArgs', 'PrivateNetwork']

@pulumi.input_type
class PrivateNetworkArgs:
    def __init__(__self__, *,
                 created_date: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 instance_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 region: pulumi.Input[Optional[_builtins.str]] = None,
                 region_name: pulumi.Input[Optional[_builtins.str]] = None,
                 updated_at: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a PrivateNetwork resource.

        :param pulumi.Input[_builtins.str] created_date: The creation date of the Private Network.
        :param pulumi.Input[_builtins.str] description: The description of the Private Network. There is a limit of 255 characters per Private Network.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.int]]] instance_ids: Add the instace Ids to the private network here. If you do not add any instance Ids an empty private network will be created.
        :param pulumi.Input[_builtins.str] name: The name of the Private Network. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Private Network name.
        :param pulumi.Input[_builtins.str] region: The region where the Private Network should be located. Default region is the EU.
        :param pulumi.Input[_builtins.str] region_name: The name of the region where the Private Network is located.
        :param pulumi.Input[_builtins.str] updated_at: Time of the last update of the private network.
        """
        if created_date is not None:
            pulumi.set(__self__, "created_date", created_date)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if instance_ids is not None:
            pulumi.set(__self__, "instance_ids", instance_ids)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if region is not None:
            pulumi.set(__self__, "region", region)
        if region_name is not None:
            pulumi.set(__self__, "region_name", region_name)
        if updated_at is not None:
            pulumi.set(__self__, "updated_at", updated_at)

    @_builtins.property
    @pulumi.getter(name="createdDate")
    def created_date(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The creation date of the Private Network.
        """
        return pulumi.get(self, "created_date")

    @created_date.setter
    def created_date(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "created_date", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The description of the Private Network. There is a limit of 255 characters per Private Network.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="instanceIds")
    def instance_ids(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.int]]]]:
        """
        Add the instace Ids to the private network here. If you do not add any instance Ids an empty private network will be created.
        """
        return pulumi.get(self, "instance_ids")

    @instance_ids.setter
    def instance_ids(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.int]]]]):
        pulumi.set(self, "instance_ids", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the Private Network. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Private Network name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The region where the Private Network should be located. Default region is the EU.
        """
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "region", value)

    @_builtins.property
    @pulumi.getter(name="regionName")
    def region_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the region where the Private Network is located.
        """
        return pulumi.get(self, "region_name")

    @region_name.setter
    def region_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "region_name", value)

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Time of the last update of the private network.
        """
        return pulumi.get(self, "updated_at")

    @updated_at.setter
    def updated_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "updated_at", value)


@pulumi.input_type
class _PrivateNetworkState:
    def __init__(__self__, *,
                 available_ips: pulumi.Input[Optional[_builtins.int]] = None,
                 cidr: pulumi.Input[Optional[_builtins.str]] = None,
                 created_date: pulumi.Input[Optional[_builtins.str]] = None,
                 data_center: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 instance_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 instances: pulumi.Input[Optional[Sequence[pulumi.Input['PrivateNetworkInstanceArgs']]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 region: pulumi.Input[Optional[_builtins.str]] = None,
                 region_name: pulumi.Input[Optional[_builtins.str]] = None,
                 updated_at: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering PrivateNetwork resources.

        :param pulumi.Input[_builtins.int] available_ips: The totality of available IPs in the Private Network.
        :param pulumi.Input[_builtins.str] cidr: The cidr range of the Private Network.
        :param pulumi.Input[_builtins.str] created_date: The creation date of the Private Network.
        :param pulumi.Input[_builtins.str] data_center: The specific data center where the Private Network is located.
        :param pulumi.Input[_builtins.str] description: The description of the Private Network. There is a limit of 255 characters per Private Network.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.int]]] instance_ids: Add the instace Ids to the private network here. If you do not add any instance Ids an empty private network will be created.
        :param pulumi.Input[_builtins.str] name: The name of the Private Network. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Private Network name.
        :param pulumi.Input[_builtins.str] region: The region where the Private Network should be located. Default region is the EU.
        :param pulumi.Input[_builtins.str] region_name: The name of the region where the Private Network is located.
        :param pulumi.Input[_builtins.str] updated_at: Time of the last update of the private network.
        """
        if available_ips is not None:
            pulumi.set(__self__, "available_ips", available_ips)
        if cidr is not None:
            pulumi.set(__self__, "cidr", cidr)
        if created_date is not None:
            pulumi.set(__self__, "created_date", created_date)
        if data_center is not None:
            pulumi.set(__self__, "data_center", data_center)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if instance_ids is not None:
            pulumi.set(__self__, "instance_ids", instance_ids)
        if instances is not None:
            pulumi.set(__self__, "instances", instances)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if region is not None:
            pulumi.set(__self__, "region", region)
        if region_name is not None:
            pulumi.set(__self__, "region_name", region_name)
        if updated_at is not None:
            pulumi.set(__self__, "updated_at", updated_at)

    @_builtins.property
    @pulumi.getter(name="availableIps")
    def available_ips(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        The totality of available IPs in the Private Network.
        """
        return pulumi.get(self, "available_ips")

    @available_ips.setter
    def available_ips(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "available_ips", value)

    @_builtins.property
    @pulumi.getter
    def cidr(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The cidr range of the Private Network.
        """
        return pulumi.get(self, "cidr")

    @cidr.setter
    def cidr(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "cidr", value)

    @_builtins.property
    @pulumi.getter(name="createdDate")
    def created_date(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The creation date of the Private Network.
        """
        return pulumi.get(self, "created_date")

    @created_date.setter
    def created_date(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "created_date", value)

    @_builtins.property
    @pulumi.getter(name="dataCenter")
    def data_center(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The specific data center where the Private Network is located.
        """
        return pulumi.get(self, "data_center")

    @data_center.setter
    def data_center(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "data_center", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The description of the Private Network. There is a limit of 255 characters per Private Network.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="instanceIds")
    def instance_ids(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.int]]]]:
        """
        Add the instace Ids to the private network here. If you do not add any instance Ids an empty private network will be created.
        """
        return pulumi.get(self, "instance_ids")

    @instance_ids.setter
    def instance_ids(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.int]]]]):
        pulumi.set(self, "instance_ids", value)

    @_builtins.property
    @pulumi.getter
    def instances(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['PrivateNetworkInstanceArgs']]]]:
        return pulumi.get(self, "instances")

    @instances.setter
    def instances(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['PrivateNetworkInstanceArgs']]]]):
        pulumi.set(self, "instances", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the Private Network. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Private Network name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The region where the Private Network should be located. Default region is the EU.
        """
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "region", value)

    @_builtins.property
    @pulumi.getter(name="regionName")
    def region_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the region where the Private Network is located.
        """
        return pulumi.get(self, "region_name")

    @region_name.setter
    def region_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "region_name", value)

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Time of the last update of the private network.
        """
        return pulumi.get(self, "updated_at")

    @updated_at.setter
    def updated_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "updated_at", value)


@pulumi.type_token("contabo:index/privateNetwork:PrivateNetwork")
class PrivateNetwork(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 created_date: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 instance_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 region: pulumi.Input[Optional[_builtins.str]] = None,
                 region_name: pulumi.Input[Optional[_builtins.str]] = None,
                 updated_at: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Provides a Contabo [Private Network](https://api.contabo.com/#tag/Private-Networks) resource.  Private Networks can contain your compute instances whereby they are able to communicate with each other in full usolation, using private IP addresses.


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] created_date: The creation date of the Private Network.
        :param pulumi.Input[_builtins.str] description: The description of the Private Network. There is a limit of 255 characters per Private Network.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.int]]] instance_ids: Add the instace Ids to the private network here. If you do not add any instance Ids an empty private network will be created.
        :param pulumi.Input[_builtins.str] name: The name of the Private Network. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Private Network name.
        :param pulumi.Input[_builtins.str] region: The region where the Private Network should be located. Default region is the EU.
        :param pulumi.Input[_builtins.str] region_name: The name of the region where the Private Network is located.
        :param pulumi.Input[_builtins.str] updated_at: Time of the last update of the private network.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[PrivateNetworkArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Provides a Contabo [Private Network](https://api.contabo.com/#tag/Private-Networks) resource.  Private Networks can contain your compute instances whereby they are able to communicate with each other in full usolation, using private IP addresses.


        :param str resource_name: The name of the resource.
        :param PrivateNetworkArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(PrivateNetworkArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 created_date: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 instance_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 region: pulumi.Input[Optional[_builtins.str]] = None,
                 region_name: pulumi.Input[Optional[_builtins.str]] = None,
                 updated_at: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = PrivateNetworkArgs.__new__(PrivateNetworkArgs)

            __props__.__dict__["created_date"] = created_date
            __props__.__dict__["description"] = description
            __props__.__dict__["instance_ids"] = instance_ids
            __props__.__dict__["name"] = name
            __props__.__dict__["region"] = region
            __props__.__dict__["region_name"] = region_name
            __props__.__dict__["updated_at"] = updated_at
            __props__.__dict__["available_ips"] = None
            __props__.__dict__["cidr"] = None
            __props__.__dict__["data_center"] = None
            __props__.__dict__["instances"] = None
        super(PrivateNetwork, __self__).__init__(
            'contabo:index/privateNetwork:PrivateNetwork',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            available_ips: pulumi.Input[Optional[_builtins.int]] = None,
            cidr: pulumi.Input[Optional[_builtins.str]] = None,
            created_date: pulumi.Input[Optional[_builtins.str]] = None,
            data_center: pulumi.Input[Optional[_builtins.str]] = None,
            description: pulumi.Input[Optional[_builtins.str]] = None,
            instance_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.int]]]] = None,
            instances: pulumi.Input[Optional[Sequence[pulumi.Input[Union['PrivateNetworkInstanceArgs', 'PrivateNetworkInstanceArgsDict']]]]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            region: pulumi.Input[Optional[_builtins.str]] = None,
            region_name: pulumi.Input[Optional[_builtins.str]] = None,
            updated_at: pulumi.Input[Optional[_builtins.str]] = None) -> 'PrivateNetwork':
        """
        Get an existing PrivateNetwork resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.int] available_ips: The totality of available IPs in the Private Network.
        :param pulumi.Input[_builtins.str] cidr: The cidr range of the Private Network.
        :param pulumi.Input[_builtins.str] created_date: The creation date of the Private Network.
        :param pulumi.Input[_builtins.str] data_center: The specific data center where the Private Network is located.
        :param pulumi.Input[_builtins.str] description: The description of the Private Network. There is a limit of 255 characters per Private Network.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.int]]] instance_ids: Add the instace Ids to the private network here. If you do not add any instance Ids an empty private network will be created.
        :param pulumi.Input[_builtins.str] name: The name of the Private Network. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Private Network name.
        :param pulumi.Input[_builtins.str] region: The region where the Private Network should be located. Default region is the EU.
        :param pulumi.Input[_builtins.str] region_name: The name of the region where the Private Network is located.
        :param pulumi.Input[_builtins.str] updated_at: Time of the last update of the private network.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _PrivateNetworkState.__new__(_PrivateNetworkState)

        __props__.__dict__["available_ips"] = available_ips
        __props__.__dict__["cidr"] = cidr
        __props__.__dict__["created_date"] = created_date
        __props__.__dict__["data_center"] = data_center
        __props__.__dict__["description"] = description
        __props__.__dict__["instance_ids"] = instance_ids
        __props__.__dict__["instances"] = instances
        __props__.__dict__["name"] = name
        __props__.__dict__["region"] = region
        __props__.__dict__["region_name"] = region_name
        __props__.__dict__["updated_at"] = updated_at
        return PrivateNetwork(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="availableIps")
    def available_ips(self) -> pulumi.Output[_builtins.int]:
        """
        The totality of available IPs in the Private Network.
        """
        return pulumi.get(self, "available_ips")

    @_builtins.property
    @pulumi.getter
    def cidr(self) -> pulumi.Output[_builtins.str]:
        """
        The cidr range of the Private Network.
        """
        return pulumi.get(self, "cidr")

    @_builtins.property
    @pulumi.getter(name="createdDate")
    def created_date(self) -> pulumi.Output[_builtins.str]:
        """
        The creation date of the Private Network.
        """
        return pulumi.get(self, "created_date")

    @_builtins.property
    @pulumi.getter(name="dataCenter")
    def data_center(self) -> pulumi.Output[_builtins.str]:
        """
        The specific data center where the Private Network is located.
        """
        return pulumi.get(self, "data_center")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The description of the Private Network. There is a limit of 255 characters per Private Network.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="instanceIds")
    def instance_ids(self) -> pulumi.Output[Optional[Sequence[_builtins.int]]]:
        """
        Add the instace Ids to the private network here. If you do not add any instance Ids an empty private network will be created.
        """
        return pulumi.get(self, "instance_ids")

    @_builtins.property
    @pulumi.getter
    def instances(self) -> pulumi.Output[Sequence['outputs.PrivateNetworkInstance']]:
        return pulumi.get(self, "instances")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the Private Network. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Private Network name.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The region where the Private Network should be located. Default region is the EU.
        """
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter(name="regionName")
    def region_name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the region where the Private Network is located.
        """
        return pulumi.get(self, "region_name")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Output[_builtins.str]:
        """
        Time of the last update of the private network.
        """
        return pulumi.get(self, "updated_at")

