# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['TagAssignmentArgs', 'TagAssignment']

@pulumi.input_type
class TagAssignmentArgs:
    def __init__(__self__, *,
                 resource_id: pulumi.Input[Optional[_builtins.str]] = None,
                 resource_type: pulumi.Input[Optional[_builtins.str]] = None,
                 tag_id: pulumi.Input[Optional[_builtins.int]] = None):
        """
        The set of arguments for constructing a TagAssignment resource.

        :param pulumi.Input[_builtins.str] resource_id: The resource id.
        :param pulumi.Input[_builtins.str] resource_type: The resource type.
        :param pulumi.Input[_builtins.int] tag_id: The identifier of the tag.
        """
        if resource_id is not None:
            pulumi.set(__self__, "resource_id", resource_id)
        if resource_type is not None:
            pulumi.set(__self__, "resource_type", resource_type)
        if tag_id is not None:
            pulumi.set(__self__, "tag_id", tag_id)

    @_builtins.property
    @pulumi.getter(name="resourceId")
    def resource_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The resource id.
        """
        return pulumi.get(self, "resource_id")

    @resource_id.setter
    def resource_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "resource_id", value)

    @_builtins.property
    @pulumi.getter(name="resourceType")
    def resource_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The resource type.
        """
        return pulumi.get(self, "resource_type")

    @resource_type.setter
    def resource_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "resource_type", value)

    @_builtins.property
    @pulumi.getter(name="tagId")
    def tag_id(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        The identifier of the tag.
        """
        return pulumi.get(self, "tag_id")

    @tag_id.setter
    def tag_id(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "tag_id", value)


@pulumi.input_type
class _TagAssignmentState:
    def __init__(__self__, *,
                 resource_id: pulumi.Input[Optional[_builtins.str]] = None,
                 resource_name: pulumi.Input[Optional[_builtins.str]] = None,
                 resource_type: pulumi.Input[Optional[_builtins.str]] = None,
                 tag_id: pulumi.Input[Optional[_builtins.int]] = None,
                 tag_name: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering TagAssignment resources.

        :param pulumi.Input[_builtins.str] resource_id: The resource id.
        :param pulumi.Input[_builtins.str] resource_name: The resource name.
        :param pulumi.Input[_builtins.str] resource_type: The resource type.
        :param pulumi.Input[_builtins.int] tag_id: The identifier of the tag.
        :param pulumi.Input[_builtins.str] tag_name: The name of the tag.
        """
        if resource_id is not None:
            pulumi.set(__self__, "resource_id", resource_id)
        if resource_name is not None:
            pulumi.set(__self__, "resource_name", resource_name)
        if resource_type is not None:
            pulumi.set(__self__, "resource_type", resource_type)
        if tag_id is not None:
            pulumi.set(__self__, "tag_id", tag_id)
        if tag_name is not None:
            pulumi.set(__self__, "tag_name", tag_name)

    @_builtins.property
    @pulumi.getter(name="resourceId")
    def resource_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The resource id.
        """
        return pulumi.get(self, "resource_id")

    @resource_id.setter
    def resource_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "resource_id", value)

    @_builtins.property
    @pulumi.getter(name="resourceName")
    def resource_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The resource name.
        """
        return pulumi.get(self, "resource_name")

    @resource_name.setter
    def resource_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "resource_name", value)

    @_builtins.property
    @pulumi.getter(name="resourceType")
    def resource_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The resource type.
        """
        return pulumi.get(self, "resource_type")

    @resource_type.setter
    def resource_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "resource_type", value)

    @_builtins.property
    @pulumi.getter(name="tagId")
    def tag_id(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        The identifier of the tag.
        """
        return pulumi.get(self, "tag_id")

    @tag_id.setter
    def tag_id(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "tag_id", value)

    @_builtins.property
    @pulumi.getter(name="tagName")
    def tag_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the tag.
        """
        return pulumi.get(self, "tag_name")

    @tag_name.setter
    def tag_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "tag_name", value)


@pulumi.type_token("contabo:index/tagAssignment:TagAssignment")
class TagAssignment(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 resource_id: pulumi.Input[Optional[_builtins.str]] = None,
                 resource_type: pulumi.Input[Optional[_builtins.str]] = None,
                 tag_id: pulumi.Input[Optional[_builtins.int]] = None,
                 __props__=None):
        """
        Tag assignment marks the specified resource with the specified tag for organizing purposes or to restrict access to that resource.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_contabo as contabo

        # Create a new tag assignment
        default_tag_assignment = contabo.TagAssignment("default_tag_assignment",
            tag_id=178478,
            resource_type="image",
            resource_id="35ee288f-21ea-420c-a074-ce0a968b59c0")
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] resource_id: The resource id.
        :param pulumi.Input[_builtins.str] resource_type: The resource type.
        :param pulumi.Input[_builtins.int] tag_id: The identifier of the tag.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[TagAssignmentArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Tag assignment marks the specified resource with the specified tag for organizing purposes or to restrict access to that resource.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_contabo as contabo

        # Create a new tag assignment
        default_tag_assignment = contabo.TagAssignment("default_tag_assignment",
            tag_id=178478,
            resource_type="image",
            resource_id="35ee288f-21ea-420c-a074-ce0a968b59c0")
        ```


        :param str resource_name: The name of the resource.
        :param TagAssignmentArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(TagAssignmentArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 resource_id: pulumi.Input[Optional[_builtins.str]] = None,
                 resource_type: pulumi.Input[Optional[_builtins.str]] = None,
                 tag_id: pulumi.Input[Optional[_builtins.int]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = TagAssignmentArgs.__new__(TagAssignmentArgs)

            __props__.__dict__["resource_id"] = resource_id
            __props__.__dict__["resource_type"] = resource_type
            __props__.__dict__["tag_id"] = tag_id
            __props__.__dict__["resource_name"] = None
            __props__.__dict__["tag_name"] = None
        super(TagAssignment, __self__).__init__(
            'contabo:index/tagAssignment:TagAssignment',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            resource_id: pulumi.Input[Optional[_builtins.str]] = None,
            resource_name_: pulumi.Input[Optional[_builtins.str]] = None,
            resource_type: pulumi.Input[Optional[_builtins.str]] = None,
            tag_id: pulumi.Input[Optional[_builtins.int]] = None,
            tag_name: pulumi.Input[Optional[_builtins.str]] = None) -> 'TagAssignment':
        """
        Get an existing TagAssignment resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] resource_id: The resource id.
        :param pulumi.Input[_builtins.str] resource_name_: The resource name.
        :param pulumi.Input[_builtins.str] resource_type: The resource type.
        :param pulumi.Input[_builtins.int] tag_id: The identifier of the tag.
        :param pulumi.Input[_builtins.str] tag_name: The name of the tag.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _TagAssignmentState.__new__(_TagAssignmentState)

        __props__.__dict__["resource_id"] = resource_id
        __props__.__dict__["resource_name"] = resource_name_
        __props__.__dict__["resource_type"] = resource_type
        __props__.__dict__["tag_id"] = tag_id
        __props__.__dict__["tag_name"] = tag_name
        return TagAssignment(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="resourceId")
    def resource_id(self) -> pulumi.Output[_builtins.str]:
        """
        The resource id.
        """
        return pulumi.get(self, "resource_id")

    @_builtins.property
    @pulumi.getter(name="resourceName")
    def resource_name(self) -> pulumi.Output[_builtins.str]:
        """
        The resource name.
        """
        return pulumi.get(self, "resource_name")

    @_builtins.property
    @pulumi.getter(name="resourceType")
    def resource_type(self) -> pulumi.Output[_builtins.str]:
        """
        The resource type.
        """
        return pulumi.get(self, "resource_type")

    @_builtins.property
    @pulumi.getter(name="tagId")
    def tag_id(self) -> pulumi.Output[_builtins.int]:
        """
        The identifier of the tag.
        """
        return pulumi.get(self, "tag_id")

    @_builtins.property
    @pulumi.getter(name="tagName")
    def tag_name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the tag.
        """
        return pulumi.get(self, "tag_name")

