// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface FirewallInstancesStatus {
    /**
     * Status of the instance.
     */
    errorMessage: string;
    /**
     * The instance
     */
    instanceId: number;
    /**
     * Status of the instance.
     */
    status: string;
}

export interface FirewallRule {
    /**
     * Inbound rules for this Firewall
     */
    inbounds: outputs.FirewallRuleInbound[];
}

export interface FirewallRuleInbound {
    /**
     * Action of the rule, currently there is just `accept`.
     */
    action: string;
    destPorts?: string[];
    /**
     * Define the protocol for the rule. Allowed protocols are `tcp`, `udp` and `icmp`.
     */
    protocol: string;
    srcCidrs?: outputs.FirewallRuleInboundSrcCidr[];
    /**
     * Status of the rule. It can be `active`, or `inactive`.
     */
    status?: string;
}

export interface FirewallRuleInboundSrcCidr {
    /**
     * Provide allowed IPv4 addresses as string array for this rule
     */
    ipv4s?: string[];
    /**
     * Provide allowed IPv6 addresses as string array for this rule
     */
    ipv6s?: string[];
}

export interface GetFirewallInstancesStatus {
    /**
     * Status of the instance.
     */
    errorMessage: string;
    /**
     * The instance
     */
    instanceId: number;
    /**
     * Status of the instance.
     */
    status: string;
}

export interface GetFirewallRule {
    /**
     * Inbound rules for this Firewall
     */
    inbounds: outputs.GetFirewallRuleInbound[];
}

export interface GetFirewallRuleInbound {
    /**
     * Action of the rule, currently there is just `accept`.
     */
    action: string;
    destPorts?: string[];
    /**
     * Define the protocol for the rule. Allowed protocols are `tcp`, `udp` and `icmp`.
     */
    protocol: string;
    srcCidrs?: outputs.GetFirewallRuleInboundSrcCidr[];
    /**
     * Status of the rule. It can be `active`, or `inactive`.
     */
    status?: string;
}

export interface GetFirewallRuleInboundSrcCidr {
    /**
     * Provide allowed IPv4 addresses as string array for this rule
     */
    ipv4s?: string[];
    /**
     * Provide allowed IPv6 addresses as string array for this rule
     */
    ipv6s?: string[];
}

export interface GetInstanceAddOn {
    /**
     * Id of the Addon. Please refer to list [here](https://contabo.com/en/product-list/?show_ids=true).
     */
    id: string;
    /**
     * The number of Addons you wish to aquire.
     */
    quantity: number;
}

export interface GetInstanceAdditionalIpsV4 {
    /**
     * Gateway
     */
    gateway: string;
    /**
     * IP Address
     */
    ip: string;
    /**
     * Netmask CIDR
     */
    netmaskCidr: number;
}

export interface GetInstanceIpConfig {
    v4s: outputs.GetInstanceIpConfigV4[];
    v6s: outputs.GetInstanceIpConfigV6[];
}

export interface GetInstanceIpConfigV4 {
    /**
     * Gateway
     */
    gateway: string;
    /**
     * IP Address
     */
    ip: string;
    /**
     * Netmask CIDR
     */
    netmaskCidr: number;
}

export interface GetInstanceIpConfigV6 {
    /**
     * Gateway
     */
    gateway: string;
    /**
     * IP Address
     */
    ip: string;
    /**
     * Netmask CIDR
     */
    netmaskCidr: number;
}

export interface GetObjectStorageAutoScaling {
    /**
     * If the autoscaling is in an error state (see status property), the error message can be seen in this field.
     */
    errorMessage: string;
    /**
     * Autoscaling size limit for the current object storage.
     */
    sizeLimitTb: number;
    /**
     * Status of this object storage.  It can be set to `enabled`, `disabled` or `error`.
     */
    state: string;
}

export interface GetPrivateNetworkInstance {
    /**
     * The instance name chosen by the customer that will be shown in the customer panel.
     */
    displayName: string;
    /**
     * If the instance is in an error state (see status property), the error message can be seen in this field.
     */
    errorMessage: string;
    /**
     * The identifier of the compute instance.
     */
    instanceId: string;
    /**
     * Name of the compute instance.
     */
    name: string;
    /**
     * List of all private IP addresses of the compute instance.
     */
    privateIpConfigs: outputs.GetPrivateNetworkInstancePrivateIpConfig[];
    /**
     * State of the instance in the Private Network. The status can be one of 'ok', 'restart', 'reinstall', 'reinstallation failed', 'installing'
     */
    status: string;
}

export interface GetPrivateNetworkInstancePrivateIpConfig {
    v4s: outputs.GetPrivateNetworkInstancePrivateIpConfigV4[];
}

export interface GetPrivateNetworkInstancePrivateIpConfigV4 {
    /**
     * Gateway
     */
    gateway: string;
    /**
     * IP Address
     */
    ip: string;
    /**
     * Netmask CIDR
     */
    netmaskCidr: number;
}

export interface InstanceAddOn {
    /**
     * Id of the Addon. Please refer to list [here](https://contabo.com/en/product-list/?show_ids=true).
     */
    id: string;
    /**
     * The number of Addons you wish to aquire.
     */
    quantity: number;
}

export interface InstanceAdditionalIp {
    v4s: outputs.InstanceAdditionalIpV4[];
}

export interface InstanceAdditionalIpV4 {
    /**
     * Gateway
     */
    gateway: string;
    /**
     * IP Address
     */
    ip: string;
    /**
     * Netmask CIDR
     */
    netmaskCidr: number;
}

export interface InstanceIpConfig {
    v4s: outputs.InstanceIpConfigV4[];
    v6s: outputs.InstanceIpConfigV6[];
}

export interface InstanceIpConfigV4 {
    /**
     * Gateway
     */
    gateway: string;
    /**
     * IP Address
     */
    ip: string;
    /**
     * Netmask CIDR
     */
    netmaskCidr: number;
}

export interface InstanceIpConfigV6 {
    /**
     * Gateway
     */
    gateway: string;
    /**
     * IP Address
     */
    ip: string;
    /**
     * Netmask CIDR
     */
    netmaskCidr: number;
}

export interface ObjectStorageAutoScaling {
    /**
     * If the autoscaling is in an error state (see status property), the error message can be seen in this field.
     */
    errorMessage?: string;
    /**
     * Autoscaling size limit for the current object storage.
     */
    sizeLimitTb?: number;
    /**
     * Status of this object storage.  It can be set to `enabled`, `disabled` or `error`.
     */
    state?: string;
}

export interface PrivateNetworkInstance {
    /**
     * The instance name chosen by the customer that will be shown in the customer panel.
     */
    displayName: string;
    /**
     * If the instance is in an error state (see status property), the error message can be seen in this field.
     */
    errorMessage: string;
    /**
     * The identifier of the compute instance.
     */
    instanceId: number;
    /**
     * Name of the compute instance.
     */
    name: string;
    /**
     * List of all private IP addresses of the compute instance.
     */
    privateIpConfigs: outputs.PrivateNetworkInstancePrivateIpConfig[];
    /**
     * State of the instance in the Private Network. The status can be one of 'ok', 'restart', 'reinstall', 'reinstallation failed', 'installing'
     */
    status: string;
}

export interface PrivateNetworkInstancePrivateIpConfig {
    v4s: outputs.PrivateNetworkInstancePrivateIpConfigV4[];
}

export interface PrivateNetworkInstancePrivateIpConfigV4 {
    /**
     * Gateway
     */
    gateway: string;
    /**
     * IP Address
     */
    ip: string;
    /**
     * Netmask CIDR
     */
    netmaskCidr: number;
}

