// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbialy.Contabo.Inputs
{

    public sealed class FirewallInstancesStatusGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Status of the instance.
        /// </summary>
        [Input("errorMessage")]
        public Input<string>? ErrorMessage { get; set; }

        /// <summary>
        /// The instance
        /// </summary>
        [Input("instanceId")]
        public Input<int>? InstanceId { get; set; }

        /// <summary>
        /// Status of the instance.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        public FirewallInstancesStatusGetArgs()
        {
        }
        public static new FirewallInstancesStatusGetArgs Empty => new FirewallInstancesStatusGetArgs();
    }
}
