// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbialy.Contabo.Inputs
{

    public sealed class GetFirewallRuleInboundSrcCidrArgs : global::Pulumi.InvokeArgs
    {
        [Input("ipv4s")]
        private List<string>? _ipv4s;

        /// <summary>
        /// Provide allowed IPv4 addresses as string array for this rule
        /// </summary>
        public List<string> Ipv4s
        {
            get => _ipv4s ?? (_ipv4s = new List<string>());
            set => _ipv4s = value;
        }

        [Input("ipv6s")]
        private List<string>? _ipv6s;

        /// <summary>
        /// Provide allowed IPv6 addresses as string array for this rule
        /// </summary>
        public List<string> Ipv6s
        {
            get => _ipv6s ?? (_ipv6s = new List<string>());
            set => _ipv6s = value;
        }

        public GetFirewallRuleInboundSrcCidrArgs()
        {
        }
        public static new GetFirewallRuleInboundSrcCidrArgs Empty => new GetFirewallRuleInboundSrcCidrArgs();
    }
}
