// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbialy.Contabo.Inputs
{

    public sealed class GetInstanceAddOnArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Id of the Addon. Please refer to list [here](https://contabo.com/en/product-list/?show_ids=true).
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        /// <summary>
        /// The number of Addons you wish to aquire.
        /// </summary>
        [Input("quantity", required: true)]
        public int Quantity { get; set; }

        public GetInstanceAddOnArgs()
        {
        }
        public static new GetInstanceAddOnArgs Empty => new GetInstanceAddOnArgs();
    }
}
