// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbialy.Contabo.Inputs
{

    public sealed class GetObjectStorageAutoScalingArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// If the autoscaling is in an error state (see status property), the error message can be seen in this field.
        /// </summary>
        [Input("errorMessage", required: true)]
        public string ErrorMessage { get; set; } = null!;

        /// <summary>
        /// Autoscaling size limit for the current object storage.
        /// </summary>
        [Input("sizeLimitTb", required: true)]
        public double SizeLimitTb { get; set; }

        /// <summary>
        /// Status of this object storage.  It can be set to `Enabled`, `Disabled` or `Error`.
        /// </summary>
        [Input("state", required: true)]
        public string State { get; set; } = null!;

        public GetObjectStorageAutoScalingArgs()
        {
        }
        public static new GetObjectStorageAutoScalingArgs Empty => new GetObjectStorageAutoScalingArgs();
    }
}
