// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbialy.Contabo.Inputs
{

    public sealed class InstanceAddOnArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Id of the Addon. Please refer to list [here](https://contabo.com/en/product-list/?show_ids=true).
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        /// <summary>
        /// The number of Addons you wish to aquire.
        /// </summary>
        [Input("quantity")]
        public Input<int>? Quantity { get; set; }

        public InstanceAddOnArgs()
        {
        }
        public static new InstanceAddOnArgs Empty => new InstanceAddOnArgs();
    }
}
