// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbialy.Contabo.Inputs
{

    public sealed class InstanceAdditionalIpArgs : global::Pulumi.ResourceArgs
    {
        [Input("v4s")]
        private InputList<Inputs.InstanceAdditionalIpV4Args>? _v4s;
        public InputList<Inputs.InstanceAdditionalIpV4Args> V4s
        {
            get => _v4s ?? (_v4s = new InputList<Inputs.InstanceAdditionalIpV4Args>());
            set => _v4s = value;
        }

        public InstanceAdditionalIpArgs()
        {
        }
        public static new InstanceAdditionalIpArgs Empty => new InstanceAdditionalIpArgs();
    }
}
