// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbialy.Contabo.Inputs
{

    public sealed class InstanceIpConfigArgs : global::Pulumi.ResourceArgs
    {
        [Input("v4s")]
        private InputList<Inputs.InstanceIpConfigV4Args>? _v4s;
        public InputList<Inputs.InstanceIpConfigV4Args> V4s
        {
            get => _v4s ?? (_v4s = new InputList<Inputs.InstanceIpConfigV4Args>());
            set => _v4s = value;
        }

        [Input("v6s")]
        private InputList<Inputs.InstanceIpConfigV6Args>? _v6s;
        public InputList<Inputs.InstanceIpConfigV6Args> V6s
        {
            get => _v6s ?? (_v6s = new InputList<Inputs.InstanceIpConfigV6Args>());
            set => _v6s = value;
        }

        public InstanceIpConfigArgs()
        {
        }
        public static new InstanceIpConfigArgs Empty => new InstanceIpConfigArgs();
    }
}
