// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbialy.Contabo.Inputs
{

    public sealed class PrivateNetworkInstancePrivateIpConfigGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("v4s")]
        private InputList<Inputs.PrivateNetworkInstancePrivateIpConfigV4GetArgs>? _v4s;
        public InputList<Inputs.PrivateNetworkInstancePrivateIpConfigV4GetArgs> V4s
        {
            get => _v4s ?? (_v4s = new InputList<Inputs.PrivateNetworkInstancePrivateIpConfigV4GetArgs>());
            set => _v4s = value;
        }

        public PrivateNetworkInstancePrivateIpConfigGetArgs()
        {
        }
        public static new PrivateNetworkInstancePrivateIpConfigGetArgs Empty => new PrivateNetworkInstancePrivateIpConfigGetArgs();
    }
}
