// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbialy.Contabo.Inputs
{

    public sealed class PrivateNetworkInstanceArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The instance name chosen by the customer that will be shown in the customer panel.
        /// </summary>
        [Input("displayName")]
        public Input<string>? DisplayName { get; set; }

        /// <summary>
        /// If the instance is in an error state (see status property), the error message can be seen in this field.
        /// </summary>
        [Input("errorMessage")]
        public Input<string>? ErrorMessage { get; set; }

        /// <summary>
        /// The identifier of the compute instance.
        /// </summary>
        [Input("instanceId")]
        public Input<int>? InstanceId { get; set; }

        /// <summary>
        /// Name of the compute instance.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("privateIpConfigs")]
        private InputList<Inputs.PrivateNetworkInstancePrivateIpConfigArgs>? _privateIpConfigs;

        /// <summary>
        /// List of all private IP addresses of the compute instance.
        /// </summary>
        public InputList<Inputs.PrivateNetworkInstancePrivateIpConfigArgs> PrivateIpConfigs
        {
            get => _privateIpConfigs ?? (_privateIpConfigs = new InputList<Inputs.PrivateNetworkInstancePrivateIpConfigArgs>());
            set => _privateIpConfigs = value;
        }

        /// <summary>
        /// State of the instance in the Private Network. The status can be one of 'ok', 'restart', 'reinstall', 'reinstallation failed', 'installing'
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        public PrivateNetworkInstanceArgs()
        {
        }
        public static new PrivateNetworkInstanceArgs Empty => new PrivateNetworkInstanceArgs();
    }
}
