// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbialy.Contabo.Inputs
{

    public sealed class PrivateNetworkInstancePrivateIpConfigV4Args : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Gateway
        /// </summary>
        [Input("gateway")]
        public Input<string>? Gateway { get; set; }

        /// <summary>
        /// IP Address
        /// </summary>
        [Input("ip")]
        public Input<string>? Ip { get; set; }

        /// <summary>
        /// Netmask CIDR
        /// </summary>
        [Input("netmaskCidr")]
        public Input<int>? NetmaskCidr { get; set; }

        public PrivateNetworkInstancePrivateIpConfigV4Args()
        {
        }
        public static new PrivateNetworkInstancePrivateIpConfigV4Args Empty => new PrivateNetworkInstancePrivateIpConfigV4Args();
    }
}
