// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as contabo from "@lbialy/contabo";
 *
 * // Search for a specific instance snapshot by ID
 * const testSnapshot = contabo.getInstanceSnapshot({
 *     id: "66abf39a-ba8b-425e-a385-8eb347ceac10",
 * });
 * export const myTestSnapshot = testSnapshot;
 * ```
 */
export function getInstanceSnapshot(args: GetInstanceSnapshotArgs, opts?: pulumi.InvokeOptions): Promise<GetInstanceSnapshotResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("contabo:index/getInstanceSnapshot:getInstanceSnapshot", {
        "description": args.description,
        "id": args.id,
        "instanceId": args.instanceId,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getInstanceSnapshot.
 */
export interface GetInstanceSnapshotArgs {
    /**
     * Description of this snapshot.
     */
    description?: string;
    /**
     * The identifier of the instance snapshot. Use it to manage it!
     */
    id: string;
    /**
     * Instance identifier associated with the snapshot
     */
    instanceId?: string;
    /**
     * Name of the snapshot.
     */
    name?: string;
}

/**
 * A collection of values returned by getInstanceSnapshot.
 */
export interface GetInstanceSnapshotResult {
    /**
     * The date when the snapshot will be autmatically deleted.
     */
    readonly autoDeleteDate: string;
    /**
     * The creation date of this instance snapshot.
     */
    readonly createdDate: string;
    /**
     * Description of this snapshot.
     */
    readonly description?: string;
    /**
     * The identifier of the instance snapshot. Use it to manage it!
     */
    readonly id: string;
    /**
     * Id of the Image the snapshot was taken from.
     */
    readonly imageId: string;
    /**
     * Name of the Image the snapshot was taken from.
     */
    readonly imageName: string;
    /**
     * Instance identifier associated with the snapshot
     */
    readonly instanceId?: string;
    /**
     * Name of the snapshot.
     */
    readonly name?: string;
}
/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as contabo from "@lbialy/contabo";
 *
 * // Search for a specific instance snapshot by ID
 * const testSnapshot = contabo.getInstanceSnapshot({
 *     id: "66abf39a-ba8b-425e-a385-8eb347ceac10",
 * });
 * export const myTestSnapshot = testSnapshot;
 * ```
 */
export function getInstanceSnapshotOutput(args: GetInstanceSnapshotOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetInstanceSnapshotResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("contabo:index/getInstanceSnapshot:getInstanceSnapshot", {
        "description": args.description,
        "id": args.id,
        "instanceId": args.instanceId,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getInstanceSnapshot.
 */
export interface GetInstanceSnapshotOutputArgs {
    /**
     * Description of this snapshot.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The identifier of the instance snapshot. Use it to manage it!
     */
    id: pulumi.Input<string>;
    /**
     * Instance identifier associated with the snapshot
     */
    instanceId?: pulumi.Input<string | undefined>;
    /**
     * Name of the snapshot.
     */
    name?: pulumi.Input<string | undefined>;
}
