// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * In order to provide a custom image, please specify an URL from which the image can be downloaded directly. A custom image must be in either `.iso` or `.qcow2` format. Other formats will be rejected. Please note that downloading can take a while depending on network speed resp. bandwidth and size of image. You can check the status by retrieving information about the image via a GET request. Download will be rejected if you have exceeded your limits.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as contabo from "@lbialy/contabo";
 *
 * // Search for a specific image by ID
 * const debian11 = contabo.getImage({
 *     id: "66abf39a-ba8b-425e-a385-8eb347ceac10",
 * });
 * export const myTestImage = debian11;
 * ```
 */
export function getImage(args: GetImageArgs, opts?: pulumi.InvokeOptions): Promise<GetImageResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("contabo:index/getImage:getImage", {
        "description": args.description,
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getImage.
 */
export interface GetImageArgs {
    /**
     * Description of the image.
     */
    description?: string;
    /**
     * The identifier of the image. Use it to manage it!
     */
    id: string;
}

/**
 * A collection of values returned by getImage.
 */
export interface GetImageResult {
    /**
     * The creation date of the image.
     */
    readonly creationDate: string;
    /**
     * Description of the image.
     */
    readonly description: string;
    /**
     * If the image is in an error state (see status property), the error message can be seen in this field.
     */
    readonly errorMessage: string;
    /**
     * Format of your image `iso` or `qcow`.
     */
    readonly format: string;
    /**
     * The identifier of the image. Use it to manage it!
     */
    readonly id: string;
    /**
     * Time of the last update of the image.
     */
    readonly lastUpdated: string;
    /**
     * Name of the image.
     */
    readonly name: string;
    /**
     * Provided type of operating system (OS). Please specify Windows for MS `Windows` and `Linux` for other OS. Specifying wrong OS type may lead to disfunctional cloud instance.
     */
    readonly osType: string;
    /**
     * Flag indicating that the image is either a standard (true) or a custom image (false).
     */
    readonly standardImage: boolean;
    /**
     * Downloading status of the image (`downloading`, `downloaded` or `error`).
     */
    readonly status: string;
    /**
     * The size of the uploaded image in megabyte.
     */
    readonly uploadedSizeMb: number;
    /**
     * Version number to distinguish the contents of an image e.g. the version of the operating system.
     */
    readonly version: string;
}
/**
 * In order to provide a custom image, please specify an URL from which the image can be downloaded directly. A custom image must be in either `.iso` or `.qcow2` format. Other formats will be rejected. Please note that downloading can take a while depending on network speed resp. bandwidth and size of image. You can check the status by retrieving information about the image via a GET request. Download will be rejected if you have exceeded your limits.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as contabo from "@lbialy/contabo";
 *
 * // Search for a specific image by ID
 * const debian11 = contabo.getImage({
 *     id: "66abf39a-ba8b-425e-a385-8eb347ceac10",
 * });
 * export const myTestImage = debian11;
 * ```
 */
export function getImageOutput(args: GetImageOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetImageResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("contabo:index/getImage:getImage", {
        "description": args.description,
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getImage.
 */
export interface GetImageOutputArgs {
    /**
     * Description of the image.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The identifier of the image. Use it to manage it!
     */
    id: pulumi.Input<string>;
}
