// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Manage S3 compatible Object Storage. With the Object Storage API you can create Object Storages in different locations. Please note that you can only have one Object Storage per location. Furthermore, you can increase the amount of storage space and control the autoscaling feature which allows you to automatically perform a monthly upgrade of the disk space to the specified maximum. You might also inspect the usage. This API is not the S3 API itself. For accessing the S3 API directly or with S3 compatible tools like `aws` cli and after having created / upgraded your Object Storage please use the S3 URL from this Storage API and refer to the User Mangement API to retrieve the S3 credentials.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as contabo from "@lbialy/contabo";
 *
 * // Search object storage by ID
 * const example1 = contabo.getObjectStorage({
 *     id: "3a6e5301-fc71-42ce-b60c-49841681c2da",
 * });
 * // Search object storage by display name
 * const example2 = contabo.getObjectStorage({
 *     displayName: "example2",
 * });
 * export const myObjectStorage1 = example1;
 * export const myObjectStorage2 = example1;
 * ```
 */
export function getObjectStorage(args?: GetObjectStorageArgs, opts?: pulumi.InvokeOptions): Promise<GetObjectStorageResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("contabo:index/getObjectStorage:getObjectStorage", {
        "autoScalings": args.autoScalings,
        "displayName": args.displayName,
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getObjectStorage.
 */
export interface GetObjectStorageArgs {
    autoScalings?: inputs.GetObjectStorageAutoScaling[];
    /**
     * Display name for object storage. Use it to manage it!
     */
    displayName?: string;
    /**
     * The identifier of the Object Storage. Use it to manage it!
     */
    id?: string;
}

/**
 * A collection of values returned by getObjectStorage.
 */
export interface GetObjectStorageResult {
    readonly autoScalings: outputs.GetObjectStorageAutoScaling[];
    /**
     * The date on which the Object Storage will be cancelled and therefore no longer available.
     */
    readonly cancelDate: string;
    /**
     * The creation date of the Object Storage.
     */
    readonly createdDate: string;
    /**
     * Your customer number.
     */
    readonly customerId: string;
    /**
     * Data center the object storage is located in.
     */
    readonly dataCenter: string;
    /**
     * Display name for object storage. Use it to manage it!
     */
    readonly displayName?: string;
    /**
     * The identifier of the Object Storage. Use it to manage it!
     */
    readonly id?: string;
    /**
     * Region where the Object Storage should be located. Default region is the EU. Following regions are available: `EU`,`US-central`, `SIN`.
     */
    readonly region: string;
    /**
     * Your S3 tenant Id. Only required for public sharing.
     */
    readonly s3TenantId: string;
    /**
     * S3 URL to connect to your S3 compatible Object Storage.
     */
    readonly s3Url: string;
    /**
     * The object storage status. It can be set to `PROVISIONING`,`READY`,`UPGRADING`,`CANCELLED`,`ERROR` or `DISABLED`.
     */
    readonly status: string;
    /**
     * Your customer tenant Id.
     */
    readonly tenantId: string;
    /**
     * Amount of purchased / requested object storage in terabyte.
     */
    readonly totalPurchasedSpaceTb: number;
}
/**
 * Manage S3 compatible Object Storage. With the Object Storage API you can create Object Storages in different locations. Please note that you can only have one Object Storage per location. Furthermore, you can increase the amount of storage space and control the autoscaling feature which allows you to automatically perform a monthly upgrade of the disk space to the specified maximum. You might also inspect the usage. This API is not the S3 API itself. For accessing the S3 API directly or with S3 compatible tools like `aws` cli and after having created / upgraded your Object Storage please use the S3 URL from this Storage API and refer to the User Mangement API to retrieve the S3 credentials.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as contabo from "@lbialy/contabo";
 *
 * // Search object storage by ID
 * const example1 = contabo.getObjectStorage({
 *     id: "3a6e5301-fc71-42ce-b60c-49841681c2da",
 * });
 * // Search object storage by display name
 * const example2 = contabo.getObjectStorage({
 *     displayName: "example2",
 * });
 * export const myObjectStorage1 = example1;
 * export const myObjectStorage2 = example1;
 * ```
 */
export function getObjectStorageOutput(args?: GetObjectStorageOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetObjectStorageResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("contabo:index/getObjectStorage:getObjectStorage", {
        "autoScalings": args.autoScalings,
        "displayName": args.displayName,
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getObjectStorage.
 */
export interface GetObjectStorageOutputArgs {
    autoScalings?: pulumi.Input<pulumi.Input<inputs.GetObjectStorageAutoScalingArgs>[] | undefined>;
    /**
     * Display name for object storage. Use it to manage it!
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * The identifier of the Object Storage. Use it to manage it!
     */
    id?: pulumi.Input<string | undefined>;
}
