// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Tag assignment marks the specified resource with the specified tag for organizing purposes or to restrict access to that resource.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as contabo from "@lbialy/contabo";
 *
 * // Get a specific tag assignment by tagId_resourceType_resourceId
 * const defaultTagAssignment = contabo.getTagAssignment({
 *     id: "178478_image_35ee288f-21ea-420c-a074-ce0a968b59c0",
 * });
 * export const output = defaultTagAssignment;
 * ```
 */
export function getTagAssignment(args: GetTagAssignmentArgs, opts?: pulumi.InvokeOptions): Promise<GetTagAssignmentResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("contabo:index/getTagAssignment:getTagAssignment", {
        "id": args.id,
        "resourceId": args.resourceId,
        "resourceType": args.resourceType,
        "tagId": args.tagId,
    }, opts);
}

/**
 * A collection of arguments for invoking getTagAssignment.
 */
export interface GetTagAssignmentArgs {
    /**
     * The identifier of the tag assignment. Use it to manage it!
     */
    id: string;
    /**
     * The resource id.
     */
    resourceId?: string;
    /**
     * The resource type.
     */
    resourceType?: string;
    /**
     * The identifier of the tag.
     */
    tagId?: number;
}

/**
 * A collection of values returned by getTagAssignment.
 */
export interface GetTagAssignmentResult {
    /**
     * The identifier of the tag assignment. Use it to manage it!
     */
    readonly id: string;
    /**
     * The resource id.
     */
    readonly resourceId: string;
    /**
     * The resource name.
     */
    readonly resourceName: string;
    /**
     * The resource type.
     */
    readonly resourceType: string;
    /**
     * The identifier of the tag.
     */
    readonly tagId: number;
    /**
     * The name of the tag.
     */
    readonly tagName: string;
}
/**
 * Tag assignment marks the specified resource with the specified tag for organizing purposes or to restrict access to that resource.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as contabo from "@lbialy/contabo";
 *
 * // Get a specific tag assignment by tagId_resourceType_resourceId
 * const defaultTagAssignment = contabo.getTagAssignment({
 *     id: "178478_image_35ee288f-21ea-420c-a074-ce0a968b59c0",
 * });
 * export const output = defaultTagAssignment;
 * ```
 */
export function getTagAssignmentOutput(args: GetTagAssignmentOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetTagAssignmentResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("contabo:index/getTagAssignment:getTagAssignment", {
        "id": args.id,
        "resourceId": args.resourceId,
        "resourceType": args.resourceType,
        "tagId": args.tagId,
    }, opts);
}

/**
 * A collection of arguments for invoking getTagAssignment.
 */
export interface GetTagAssignmentOutputArgs {
    /**
     * The identifier of the tag assignment. Use it to manage it!
     */
    id: pulumi.Input<string>;
    /**
     * The resource id.
     */
    resourceId?: pulumi.Input<string | undefined>;
    /**
     * The resource type.
     */
    resourceType?: pulumi.Input<string | undefined>;
    /**
     * The identifier of the tag.
     */
    tagId?: pulumi.Input<number | undefined>;
}
