// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Tags are Customer-defined labels which can be attached to any resource in your account. Tag API represent simple CRUD functions and allow you to manage your tags. Use tags to group your resources. For example you can define some user group with tag and give them permission to create compute instance.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as contabo from "@lbialy/contabo";
 *
 * // Get a specific tag by ID
 * const defaultTag = contabo.getTag({
 *     id: "26878",
 * });
 * export const output = defaultTag;
 * ```
 */
export function getTag(args: GetTagArgs, opts?: pulumi.InvokeOptions): Promise<GetTagResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("contabo:index/getTag:getTag", {
        "color": args.color,
        "id": args.id,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getTag.
 */
export interface GetTagArgs {
    /**
     * The tag color.
     */
    color?: string;
    /**
     * The identifier of the tag. Use it to manage it!
     */
    id: string;
    /**
     * The tag name.
     */
    name?: string;
}

/**
 * A collection of values returned by getTag.
 */
export interface GetTagResult {
    /**
     * The tag color.
     */
    readonly color: string;
    /**
     * The identifier of the tag. Use it to manage it!
     */
    readonly id: string;
    /**
     * The tag name.
     */
    readonly name: string;
}
/**
 * Tags are Customer-defined labels which can be attached to any resource in your account. Tag API represent simple CRUD functions and allow you to manage your tags. Use tags to group your resources. For example you can define some user group with tag and give them permission to create compute instance.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as contabo from "@lbialy/contabo";
 *
 * // Get a specific tag by ID
 * const defaultTag = contabo.getTag({
 *     id: "26878",
 * });
 * export const output = defaultTag;
 * ```
 */
export function getTagOutput(args: GetTagOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetTagResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("contabo:index/getTag:getTag", {
        "color": args.color,
        "id": args.id,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getTag.
 */
export interface GetTagOutputArgs {
    /**
     * The tag color.
     */
    color?: pulumi.Input<string | undefined>;
    /**
     * The identifier of the tag. Use it to manage it!
     */
    id: pulumi.Input<string>;
    /**
     * The tag name.
     */
    name?: pulumi.Input<string | undefined>;
}
