// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * In order to provide a custom image, please specify an URL from which the image can be downloaded directly. A custom image must be in either `.iso` or `.qcow2` format. Other formats will be rejected. Please note that downloading can take a while depending on network speed resp. bandwidth and size of image. You can check the status by retrieving information about the image via a GET request. Download will be rejected if you have exceeded your limits.
 */
export class Image extends pulumi.CustomResource {
    /**
     * Get an existing Image resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ImageState, opts?: pulumi.CustomResourceOptions): Image {
        return new Image(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'contabo:index/image:Image';

    /**
     * Returns true if the given object is an instance of Image.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Image {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Image.__pulumiType;
    }

    /**
     * The creation date of the image.
     */
    declare public /*out*/ readonly creationDate: pulumi.Output<string>;
    /**
     * Description of the image.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * If the image is in an error state (see status property), the error message can be seen in this field.
     */
    declare public /*out*/ readonly errorMessage: pulumi.Output<string>;
    /**
     * Format of your image `iso` or `qcow`.
     */
    declare public /*out*/ readonly format: pulumi.Output<string>;
    /**
     * URL from which the image has been downloaded.
     */
    declare public readonly imageUrl: pulumi.Output<string>;
    /**
     * Time of the last update of the image.
     */
    declare public /*out*/ readonly lastUpdated: pulumi.Output<string>;
    /**
     * Name of the image.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Provided type of operating system (OS). Please specify Windows for MS `Windows` and `Linux` for other OS. Specifying wrong OS type may lead to disfunctional cloud instance.
     */
    declare public readonly osType: pulumi.Output<string>;
    /**
     * Flag indicating that the image is either a standard (true) or a custom image (false).
     */
    declare public /*out*/ readonly standardImage: pulumi.Output<boolean>;
    /**
     * Downloading status of the image (`downloading`, `downloaded` or `error`).
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * The size of the uploaded image in megabyte.
     */
    declare public /*out*/ readonly uploadedSizeMb: pulumi.Output<number>;
    /**
     * Version number to distinguish the contents of an image e.g. the version of the operating system.
     */
    declare public readonly version: pulumi.Output<string>;

    /**
     * Create a Image resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ImageArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ImageArgs | ImageState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ImageState | undefined;
            resourceInputs["creationDate"] = state?.creationDate;
            resourceInputs["description"] = state?.description;
            resourceInputs["errorMessage"] = state?.errorMessage;
            resourceInputs["format"] = state?.format;
            resourceInputs["imageUrl"] = state?.imageUrl;
            resourceInputs["lastUpdated"] = state?.lastUpdated;
            resourceInputs["name"] = state?.name;
            resourceInputs["osType"] = state?.osType;
            resourceInputs["standardImage"] = state?.standardImage;
            resourceInputs["status"] = state?.status;
            resourceInputs["uploadedSizeMb"] = state?.uploadedSizeMb;
            resourceInputs["version"] = state?.version;
        } else {
            const args = argsOrState as ImageArgs | undefined;
            if (args?.description === undefined && !opts.urn) {
                throw new Error("Missing required property 'description'");
            }
            if (args?.imageUrl === undefined && !opts.urn) {
                throw new Error("Missing required property 'imageUrl'");
            }
            if (args?.osType === undefined && !opts.urn) {
                throw new Error("Missing required property 'osType'");
            }
            if (args?.version === undefined && !opts.urn) {
                throw new Error("Missing required property 'version'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["imageUrl"] = args?.imageUrl;
            resourceInputs["name"] = args?.name;
            resourceInputs["osType"] = args?.osType;
            resourceInputs["version"] = args?.version;
            resourceInputs["creationDate"] = undefined /*out*/;
            resourceInputs["errorMessage"] = undefined /*out*/;
            resourceInputs["format"] = undefined /*out*/;
            resourceInputs["lastUpdated"] = undefined /*out*/;
            resourceInputs["standardImage"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["uploadedSizeMb"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Image.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Image resources.
 */
export interface ImageState {
    /**
     * The creation date of the image.
     */
    creationDate?: pulumi.Input<string | undefined>;
    /**
     * Description of the image.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * If the image is in an error state (see status property), the error message can be seen in this field.
     */
    errorMessage?: pulumi.Input<string | undefined>;
    /**
     * Format of your image `iso` or `qcow`.
     */
    format?: pulumi.Input<string | undefined>;
    /**
     * URL from which the image has been downloaded.
     */
    imageUrl?: pulumi.Input<string | undefined>;
    /**
     * Time of the last update of the image.
     */
    lastUpdated?: pulumi.Input<string | undefined>;
    /**
     * Name of the image.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Provided type of operating system (OS). Please specify Windows for MS `Windows` and `Linux` for other OS. Specifying wrong OS type may lead to disfunctional cloud instance.
     */
    osType?: pulumi.Input<string | undefined>;
    /**
     * Flag indicating that the image is either a standard (true) or a custom image (false).
     */
    standardImage?: pulumi.Input<boolean | undefined>;
    /**
     * Downloading status of the image (`downloading`, `downloaded` or `error`).
     */
    status?: pulumi.Input<string | undefined>;
    /**
     * The size of the uploaded image in megabyte.
     */
    uploadedSizeMb?: pulumi.Input<number | undefined>;
    /**
     * Version number to distinguish the contents of an image e.g. the version of the operating system.
     */
    version?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Image resource.
 */
export interface ImageArgs {
    /**
     * Description of the image.
     */
    description: pulumi.Input<string>;
    /**
     * URL from which the image has been downloaded.
     */
    imageUrl: pulumi.Input<string>;
    /**
     * Name of the image.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Provided type of operating system (OS). Please specify Windows for MS `Windows` and `Linux` for other OS. Specifying wrong OS type may lead to disfunctional cloud instance.
     */
    osType: pulumi.Input<string>;
    /**
     * Version number to distinguish the contents of an image e.g. the version of the operating system.
     */
    version: pulumi.Input<string>;
}
