// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { FirewallArgs, FirewallState } from "./firewall";
export type Firewall = import("./firewall").Firewall;
export const Firewall: typeof import("./firewall").Firewall = null as any;
utilities.lazyLoad(exports, ["Firewall"], () => require("./firewall"));

export { GetFirewallArgs, GetFirewallResult, GetFirewallOutputArgs } from "./getFirewall";
export const getFirewall: typeof import("./getFirewall").getFirewall = null as any;
export const getFirewallOutput: typeof import("./getFirewall").getFirewallOutput = null as any;
utilities.lazyLoad(exports, ["getFirewall","getFirewallOutput"], () => require("./getFirewall"));

export { GetImageArgs, GetImageResult, GetImageOutputArgs } from "./getImage";
export const getImage: typeof import("./getImage").getImage = null as any;
export const getImageOutput: typeof import("./getImage").getImageOutput = null as any;
utilities.lazyLoad(exports, ["getImage","getImageOutput"], () => require("./getImage"));

export { GetInstanceArgs, GetInstanceResult, GetInstanceOutputArgs } from "./getInstance";
export const getInstance: typeof import("./getInstance").getInstance = null as any;
export const getInstanceOutput: typeof import("./getInstance").getInstanceOutput = null as any;
utilities.lazyLoad(exports, ["getInstance","getInstanceOutput"], () => require("./getInstance"));

export { GetInstanceSnapshotArgs, GetInstanceSnapshotResult, GetInstanceSnapshotOutputArgs } from "./getInstanceSnapshot";
export const getInstanceSnapshot: typeof import("./getInstanceSnapshot").getInstanceSnapshot = null as any;
export const getInstanceSnapshotOutput: typeof import("./getInstanceSnapshot").getInstanceSnapshotOutput = null as any;
utilities.lazyLoad(exports, ["getInstanceSnapshot","getInstanceSnapshotOutput"], () => require("./getInstanceSnapshot"));

export { GetObjectStorageArgs, GetObjectStorageResult, GetObjectStorageOutputArgs } from "./getObjectStorage";
export const getObjectStorage: typeof import("./getObjectStorage").getObjectStorage = null as any;
export const getObjectStorageOutput: typeof import("./getObjectStorage").getObjectStorageOutput = null as any;
utilities.lazyLoad(exports, ["getObjectStorage","getObjectStorageOutput"], () => require("./getObjectStorage"));

export { GetObjectStorageBucketArgs, GetObjectStorageBucketResult, GetObjectStorageBucketOutputArgs } from "./getObjectStorageBucket";
export const getObjectStorageBucket: typeof import("./getObjectStorageBucket").getObjectStorageBucket = null as any;
export const getObjectStorageBucketOutput: typeof import("./getObjectStorageBucket").getObjectStorageBucketOutput = null as any;
utilities.lazyLoad(exports, ["getObjectStorageBucket","getObjectStorageBucketOutput"], () => require("./getObjectStorageBucket"));

export { GetPrivateNetworkArgs, GetPrivateNetworkResult, GetPrivateNetworkOutputArgs } from "./getPrivateNetwork";
export const getPrivateNetwork: typeof import("./getPrivateNetwork").getPrivateNetwork = null as any;
export const getPrivateNetworkOutput: typeof import("./getPrivateNetwork").getPrivateNetworkOutput = null as any;
utilities.lazyLoad(exports, ["getPrivateNetwork","getPrivateNetworkOutput"], () => require("./getPrivateNetwork"));

export { GetSecretArgs, GetSecretResult, GetSecretOutputArgs } from "./getSecret";
export const getSecret: typeof import("./getSecret").getSecret = null as any;
export const getSecretOutput: typeof import("./getSecret").getSecretOutput = null as any;
utilities.lazyLoad(exports, ["getSecret","getSecretOutput"], () => require("./getSecret"));

export { GetTagArgs, GetTagResult, GetTagOutputArgs } from "./getTag";
export const getTag: typeof import("./getTag").getTag = null as any;
export const getTagOutput: typeof import("./getTag").getTagOutput = null as any;
utilities.lazyLoad(exports, ["getTag","getTagOutput"], () => require("./getTag"));

export { GetTagAssignmentArgs, GetTagAssignmentResult, GetTagAssignmentOutputArgs } from "./getTagAssignment";
export const getTagAssignment: typeof import("./getTagAssignment").getTagAssignment = null as any;
export const getTagAssignmentOutput: typeof import("./getTagAssignment").getTagAssignmentOutput = null as any;
utilities.lazyLoad(exports, ["getTagAssignment","getTagAssignmentOutput"], () => require("./getTagAssignment"));

export { ImageArgs, ImageState } from "./image";
export type Image = import("./image").Image;
export const Image: typeof import("./image").Image = null as any;
utilities.lazyLoad(exports, ["Image"], () => require("./image"));

export { InstanceArgs, InstanceState } from "./instance";
export type Instance = import("./instance").Instance;
export const Instance: typeof import("./instance").Instance = null as any;
utilities.lazyLoad(exports, ["Instance"], () => require("./instance"));

export { InstanceSnapshotArgs, InstanceSnapshotState } from "./instanceSnapshot";
export type InstanceSnapshot = import("./instanceSnapshot").InstanceSnapshot;
export const InstanceSnapshot: typeof import("./instanceSnapshot").InstanceSnapshot = null as any;
utilities.lazyLoad(exports, ["InstanceSnapshot"], () => require("./instanceSnapshot"));

export { ObjectStorageArgs, ObjectStorageState } from "./objectStorage";
export type ObjectStorage = import("./objectStorage").ObjectStorage;
export const ObjectStorage: typeof import("./objectStorage").ObjectStorage = null as any;
utilities.lazyLoad(exports, ["ObjectStorage"], () => require("./objectStorage"));

export { ObjectStorageBucketArgs, ObjectStorageBucketState } from "./objectStorageBucket";
export type ObjectStorageBucket = import("./objectStorageBucket").ObjectStorageBucket;
export const ObjectStorageBucket: typeof import("./objectStorageBucket").ObjectStorageBucket = null as any;
utilities.lazyLoad(exports, ["ObjectStorageBucket"], () => require("./objectStorageBucket"));

export { PrivateNetworkArgs, PrivateNetworkState } from "./privateNetwork";
export type PrivateNetwork = import("./privateNetwork").PrivateNetwork;
export const PrivateNetwork: typeof import("./privateNetwork").PrivateNetwork = null as any;
utilities.lazyLoad(exports, ["PrivateNetwork"], () => require("./privateNetwork"));

export * from "./provider";
import { Provider } from "./provider";

export { SecretArgs, SecretState } from "./secret";
export type Secret = import("./secret").Secret;
export const Secret: typeof import("./secret").Secret = null as any;
utilities.lazyLoad(exports, ["Secret"], () => require("./secret"));

export { TagArgs, TagState } from "./tag";
export type Tag = import("./tag").Tag;
export const Tag: typeof import("./tag").Tag = null as any;
utilities.lazyLoad(exports, ["Tag"], () => require("./tag"));

export { TagAssignmentArgs, TagAssignmentState } from "./tagAssignment";
export type TagAssignment = import("./tagAssignment").TagAssignment;
export const TagAssignment: typeof import("./tagAssignment").TagAssignment = null as any;
utilities.lazyLoad(exports, ["TagAssignment"], () => require("./tagAssignment"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "contabo:index/firewall:Firewall":
                return new Firewall(name, <any>undefined, { urn })
            case "contabo:index/image:Image":
                return new Image(name, <any>undefined, { urn })
            case "contabo:index/instance:Instance":
                return new Instance(name, <any>undefined, { urn })
            case "contabo:index/instanceSnapshot:InstanceSnapshot":
                return new InstanceSnapshot(name, <any>undefined, { urn })
            case "contabo:index/objectStorage:ObjectStorage":
                return new ObjectStorage(name, <any>undefined, { urn })
            case "contabo:index/objectStorageBucket:ObjectStorageBucket":
                return new ObjectStorageBucket(name, <any>undefined, { urn })
            case "contabo:index/privateNetwork:PrivateNetwork":
                return new PrivateNetwork(name, <any>undefined, { urn })
            case "contabo:index/secret:Secret":
                return new Secret(name, <any>undefined, { urn })
            case "contabo:index/tag:Tag":
                return new Tag(name, <any>undefined, { urn })
            case "contabo:index/tagAssignment:TagAssignment":
                return new TagAssignment(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("contabo", "index/firewall", _module)
pulumi.runtime.registerResourceModule("contabo", "index/image", _module)
pulumi.runtime.registerResourceModule("contabo", "index/instance", _module)
pulumi.runtime.registerResourceModule("contabo", "index/instanceSnapshot", _module)
pulumi.runtime.registerResourceModule("contabo", "index/objectStorage", _module)
pulumi.runtime.registerResourceModule("contabo", "index/objectStorageBucket", _module)
pulumi.runtime.registerResourceModule("contabo", "index/privateNetwork", _module)
pulumi.runtime.registerResourceModule("contabo", "index/secret", _module)
pulumi.runtime.registerResourceModule("contabo", "index/tag", _module)
pulumi.runtime.registerResourceModule("contabo", "index/tagAssignment", _module)
pulumi.runtime.registerResourcePackage("contabo", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:contabo") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
