// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 */
export class InstanceSnapshot extends pulumi.CustomResource {
    /**
     * Get an existing InstanceSnapshot resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: InstanceSnapshotState, opts?: pulumi.CustomResourceOptions): InstanceSnapshot {
        return new InstanceSnapshot(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'contabo:index/instanceSnapshot:InstanceSnapshot';

    /**
     * Returns true if the given object is an instance of InstanceSnapshot.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is InstanceSnapshot {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === InstanceSnapshot.__pulumiType;
    }

    /**
     * The date when the snapshot will be autmatically deleted.
     */
    declare public /*out*/ readonly autoDeleteDate: pulumi.Output<string>;
    /**
     * The creation date of this instance snapshot.
     */
    declare public readonly createdDate: pulumi.Output<string>;
    /**
     * Description of this snapshot.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Id of the Image the snapshot was taken from.
     */
    declare public /*out*/ readonly imageId: pulumi.Output<string>;
    /**
     * Name of the Image the snapshot was taken from.
     */
    declare public /*out*/ readonly imageName: pulumi.Output<string>;
    /**
     * Instance identifier associated with the snapshot.
     */
    declare public readonly instanceId: pulumi.Output<number | undefined>;
    /**
     * Name of the snapshot.
     */
    declare public readonly name: pulumi.Output<string>;

    /**
     * Create a InstanceSnapshot resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: InstanceSnapshotArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: InstanceSnapshotArgs | InstanceSnapshotState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as InstanceSnapshotState | undefined;
            resourceInputs["autoDeleteDate"] = state?.autoDeleteDate;
            resourceInputs["createdDate"] = state?.createdDate;
            resourceInputs["description"] = state?.description;
            resourceInputs["imageId"] = state?.imageId;
            resourceInputs["imageName"] = state?.imageName;
            resourceInputs["instanceId"] = state?.instanceId;
            resourceInputs["name"] = state?.name;
        } else {
            const args = argsOrState as InstanceSnapshotArgs | undefined;
            resourceInputs["createdDate"] = args?.createdDate;
            resourceInputs["description"] = args?.description;
            resourceInputs["instanceId"] = args?.instanceId;
            resourceInputs["name"] = args?.name;
            resourceInputs["autoDeleteDate"] = undefined /*out*/;
            resourceInputs["imageId"] = undefined /*out*/;
            resourceInputs["imageName"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(InstanceSnapshot.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering InstanceSnapshot resources.
 */
export interface InstanceSnapshotState {
    /**
     * The date when the snapshot will be autmatically deleted.
     */
    autoDeleteDate?: pulumi.Input<string | undefined>;
    /**
     * The creation date of this instance snapshot.
     */
    createdDate?: pulumi.Input<string | undefined>;
    /**
     * Description of this snapshot.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Id of the Image the snapshot was taken from.
     */
    imageId?: pulumi.Input<string | undefined>;
    /**
     * Name of the Image the snapshot was taken from.
     */
    imageName?: pulumi.Input<string | undefined>;
    /**
     * Instance identifier associated with the snapshot.
     */
    instanceId?: pulumi.Input<number | undefined>;
    /**
     * Name of the snapshot.
     */
    name?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a InstanceSnapshot resource.
 */
export interface InstanceSnapshotArgs {
    /**
     * The creation date of this instance snapshot.
     */
    createdDate?: pulumi.Input<string | undefined>;
    /**
     * Description of this snapshot.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Instance identifier associated with the snapshot.
     */
    instanceId?: pulumi.Input<number | undefined>;
    /**
     * Name of the snapshot.
     */
    name?: pulumi.Input<string | undefined>;
}
