// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Provides a Contabo [Private Network](https://api.contabo.com/#tag/Private-Networks) resource.  Private Networks can contain your compute instances whereby they are able to communicate with each other in full usolation, using private IP addresses.
 */
export class PrivateNetwork extends pulumi.CustomResource {
    /**
     * Get an existing PrivateNetwork resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PrivateNetworkState, opts?: pulumi.CustomResourceOptions): PrivateNetwork {
        return new PrivateNetwork(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'contabo:index/privateNetwork:PrivateNetwork';

    /**
     * Returns true if the given object is an instance of PrivateNetwork.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PrivateNetwork {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PrivateNetwork.__pulumiType;
    }

    /**
     * The totality of available IPs in the Private Network.
     */
    declare public /*out*/ readonly availableIps: pulumi.Output<number>;
    /**
     * The cidr range of the Private Network.
     */
    declare public /*out*/ readonly cidr: pulumi.Output<string>;
    /**
     * The creation date of the Private Network.
     */
    declare public readonly createdDate: pulumi.Output<string>;
    /**
     * The specific data center where the Private Network is located.
     */
    declare public /*out*/ readonly dataCenter: pulumi.Output<string>;
    /**
     * The description of the Private Network. There is a limit of 255 characters per Private Network.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Add the instace Ids to the private network here. If you do not add any instance Ids an empty private network will be created.
     */
    declare public readonly instanceIds: pulumi.Output<number[] | undefined>;
    declare public /*out*/ readonly instances: pulumi.Output<outputs.PrivateNetworkInstance[]>;
    /**
     * The name of the Private Network. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Private Network name.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The region where the Private Network should be located. Default region is the EU.
     */
    declare public readonly region: pulumi.Output<string | undefined>;
    /**
     * The name of the region where the Private Network is located.
     */
    declare public readonly regionName: pulumi.Output<string>;
    /**
     * Time of the last update of the private network.
     */
    declare public readonly updatedAt: pulumi.Output<string>;

    /**
     * Create a PrivateNetwork resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: PrivateNetworkArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PrivateNetworkArgs | PrivateNetworkState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PrivateNetworkState | undefined;
            resourceInputs["availableIps"] = state?.availableIps;
            resourceInputs["cidr"] = state?.cidr;
            resourceInputs["createdDate"] = state?.createdDate;
            resourceInputs["dataCenter"] = state?.dataCenter;
            resourceInputs["description"] = state?.description;
            resourceInputs["instanceIds"] = state?.instanceIds;
            resourceInputs["instances"] = state?.instances;
            resourceInputs["name"] = state?.name;
            resourceInputs["region"] = state?.region;
            resourceInputs["regionName"] = state?.regionName;
            resourceInputs["updatedAt"] = state?.updatedAt;
        } else {
            const args = argsOrState as PrivateNetworkArgs | undefined;
            resourceInputs["createdDate"] = args?.createdDate;
            resourceInputs["description"] = args?.description;
            resourceInputs["instanceIds"] = args?.instanceIds;
            resourceInputs["name"] = args?.name;
            resourceInputs["region"] = args?.region;
            resourceInputs["regionName"] = args?.regionName;
            resourceInputs["updatedAt"] = args?.updatedAt;
            resourceInputs["availableIps"] = undefined /*out*/;
            resourceInputs["cidr"] = undefined /*out*/;
            resourceInputs["dataCenter"] = undefined /*out*/;
            resourceInputs["instances"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PrivateNetwork.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering PrivateNetwork resources.
 */
export interface PrivateNetworkState {
    /**
     * The totality of available IPs in the Private Network.
     */
    availableIps?: pulumi.Input<number | undefined>;
    /**
     * The cidr range of the Private Network.
     */
    cidr?: pulumi.Input<string | undefined>;
    /**
     * The creation date of the Private Network.
     */
    createdDate?: pulumi.Input<string | undefined>;
    /**
     * The specific data center where the Private Network is located.
     */
    dataCenter?: pulumi.Input<string | undefined>;
    /**
     * The description of the Private Network. There is a limit of 255 characters per Private Network.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Add the instace Ids to the private network here. If you do not add any instance Ids an empty private network will be created.
     */
    instanceIds?: pulumi.Input<pulumi.Input<number>[] | undefined>;
    instances?: pulumi.Input<pulumi.Input<inputs.PrivateNetworkInstance>[] | undefined>;
    /**
     * The name of the Private Network. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Private Network name.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The region where the Private Network should be located. Default region is the EU.
     */
    region?: pulumi.Input<string | undefined>;
    /**
     * The name of the region where the Private Network is located.
     */
    regionName?: pulumi.Input<string | undefined>;
    /**
     * Time of the last update of the private network.
     */
    updatedAt?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a PrivateNetwork resource.
 */
export interface PrivateNetworkArgs {
    /**
     * The creation date of the Private Network.
     */
    createdDate?: pulumi.Input<string | undefined>;
    /**
     * The description of the Private Network. There is a limit of 255 characters per Private Network.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Add the instace Ids to the private network here. If you do not add any instance Ids an empty private network will be created.
     */
    instanceIds?: pulumi.Input<pulumi.Input<number>[] | undefined>;
    /**
     * The name of the Private Network. It may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per Private Network name.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The region where the Private Network should be located. Default region is the EU.
     */
    region?: pulumi.Input<string | undefined>;
    /**
     * The name of the region where the Private Network is located.
     */
    regionName?: pulumi.Input<string | undefined>;
    /**
     * Time of the last update of the private network.
     */
    updatedAt?: pulumi.Input<string | undefined>;
}
