// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The Secret Management API allows you to store and manage your passwords and ssh-keys. Usage of the Secret Management API is purely optional. As a convenience feature e.g. it allows you to reuse SSH-keys easily.
 */
export class Secret extends pulumi.CustomResource {
    /**
     * Get an existing Secret resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SecretState, opts?: pulumi.CustomResourceOptions): Secret {
        return new Secret(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'contabo:index/secret:Secret';

    /**
     * Returns true if the given object is an instance of Secret.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Secret {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Secret.__pulumiType;
    }

    /**
     * The creation date of the secret.
     */
    declare public readonly createdAt: pulumi.Output<string>;
    /**
     * Name of the secret.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The type of the secret. It will be available only when retrieving secrets, following types are allowed: `ssh`, `password`.
     */
    declare public readonly type: pulumi.Output<string>;
    /**
     * Last updated time of the secret.
     */
    declare public readonly updatedAt: pulumi.Output<string>;
    /**
     * The value of the secret. It will be available only when retrieving a single secret.
     */
    declare public readonly value: pulumi.Output<string>;

    /**
     * Create a Secret resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SecretArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SecretArgs | SecretState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SecretState | undefined;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["name"] = state?.name;
            resourceInputs["type"] = state?.type;
            resourceInputs["updatedAt"] = state?.updatedAt;
            resourceInputs["value"] = state?.value;
        } else {
            const args = argsOrState as SecretArgs | undefined;
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            if (args?.value === undefined && !opts.urn) {
                throw new Error("Missing required property 'value'");
            }
            resourceInputs["createdAt"] = args?.createdAt;
            resourceInputs["name"] = args?.name;
            resourceInputs["type"] = args?.type;
            resourceInputs["updatedAt"] = args?.updatedAt;
            resourceInputs["value"] = args?.value ? pulumi.secret(args.value) : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["value"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Secret.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Secret resources.
 */
export interface SecretState {
    /**
     * The creation date of the secret.
     */
    createdAt?: pulumi.Input<string | undefined>;
    /**
     * Name of the secret.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The type of the secret. It will be available only when retrieving secrets, following types are allowed: `ssh`, `password`.
     */
    type?: pulumi.Input<string | undefined>;
    /**
     * Last updated time of the secret.
     */
    updatedAt?: pulumi.Input<string | undefined>;
    /**
     * The value of the secret. It will be available only when retrieving a single secret.
     */
    value?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Secret resource.
 */
export interface SecretArgs {
    /**
     * The creation date of the secret.
     */
    createdAt?: pulumi.Input<string | undefined>;
    /**
     * Name of the secret.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The type of the secret. It will be available only when retrieving secrets, following types are allowed: `ssh`, `password`.
     */
    type: pulumi.Input<string>;
    /**
     * Last updated time of the secret.
     */
    updatedAt?: pulumi.Input<string | undefined>;
    /**
     * The value of the secret. It will be available only when retrieving a single secret.
     */
    value: pulumi.Input<string>;
}
