// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Tag assignment marks the specified resource with the specified tag for organizing purposes or to restrict access to that resource.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as contabo from "@lbialy/contabo";
 *
 * // Create a new tag assignment
 * const defaultTagAssignment = new contabo.TagAssignment("default_tag_assignment", {
 *     tagId: 178478,
 *     resourceType: "image",
 *     resourceId: "35ee288f-21ea-420c-a074-ce0a968b59c0",
 * });
 * ```
 */
export class TagAssignment extends pulumi.CustomResource {
    /**
     * Get an existing TagAssignment resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TagAssignmentState, opts?: pulumi.CustomResourceOptions): TagAssignment {
        return new TagAssignment(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'contabo:index/tagAssignment:TagAssignment';

    /**
     * Returns true if the given object is an instance of TagAssignment.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TagAssignment {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TagAssignment.__pulumiType;
    }

    /**
     * The resource id.
     */
    declare public readonly resourceId: pulumi.Output<string>;
    /**
     * The resource name.
     */
    declare public /*out*/ readonly resourceName: pulumi.Output<string>;
    /**
     * The resource type.
     */
    declare public readonly resourceType: pulumi.Output<string>;
    /**
     * The identifier of the tag.
     */
    declare public readonly tagId: pulumi.Output<number>;
    /**
     * The name of the tag.
     */
    declare public /*out*/ readonly tagName: pulumi.Output<string>;

    /**
     * Create a TagAssignment resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: TagAssignmentArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TagAssignmentArgs | TagAssignmentState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TagAssignmentState | undefined;
            resourceInputs["resourceId"] = state?.resourceId;
            resourceInputs["resourceName"] = state?.resourceName;
            resourceInputs["resourceType"] = state?.resourceType;
            resourceInputs["tagId"] = state?.tagId;
            resourceInputs["tagName"] = state?.tagName;
        } else {
            const args = argsOrState as TagAssignmentArgs | undefined;
            resourceInputs["resourceId"] = args?.resourceId;
            resourceInputs["resourceType"] = args?.resourceType;
            resourceInputs["tagId"] = args?.tagId;
            resourceInputs["resourceName"] = undefined /*out*/;
            resourceInputs["tagName"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TagAssignment.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering TagAssignment resources.
 */
export interface TagAssignmentState {
    /**
     * The resource id.
     */
    resourceId?: pulumi.Input<string | undefined>;
    /**
     * The resource name.
     */
    resourceName?: pulumi.Input<string | undefined>;
    /**
     * The resource type.
     */
    resourceType?: pulumi.Input<string | undefined>;
    /**
     * The identifier of the tag.
     */
    tagId?: pulumi.Input<number | undefined>;
    /**
     * The name of the tag.
     */
    tagName?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a TagAssignment resource.
 */
export interface TagAssignmentArgs {
    /**
     * The resource id.
     */
    resourceId?: pulumi.Input<string | undefined>;
    /**
     * The resource type.
     */
    resourceType?: pulumi.Input<string | undefined>;
    /**
     * The identifier of the tag.
     */
    tagId?: pulumi.Input<number | undefined>;
}
